--------[vrmod_addmenuphys.lua]Start--------
AddCSLuaFile()
if SERVER then return end
local L = VRModL or function(_, fb) return fb or "" end
local convars, convarValues = vrmod.GetConvars()
hook.Add(
	"VRMod_Menu",
	"addsettingsvrphysgun",
	function(frame)
		if not frame or not frame.DPropertySheet then return end

		local ok, err = pcall(function()
		local sheet = vgui.Create("DPropertySheet")
		sheet:Dock(FILL)
		local physgunmaxrange = GetConVar("physgun_maxrange") or CreateClientConVar("physgun_maxrange", "4096", true, false)
		local MenuTab16 = vgui.Create("DPanel", sheet)
		sheet:AddSheet(L("Physgun Left", "Physgun Left"), MenuTab16, "icon16/brick.png")
		MenuTab16.Paint = function(self, w, h) end
		local title = vgui.Create("DLabel", MenuTab16)
		title:SetText(L("VR Physgun Settings (LEFT HAND)", "VR Physgun Settings (LEFT HAND)"))
		title:SetFont("DermaDefaultBold")
		title:SetTextColor(Color(0, 0, 0))
		title:SetPos(20, 10)
		title:SizeToContents()
		local enableBeam = vgui.Create("DCheckBoxLabel", MenuTab16)
		enableBeam:SetText(L("Enable Physgun Beams", "Enable Physgun Beams"))
		enableBeam:SetConVar("vrmod_left_physgun_beam_enable")
		enableBeam:SetPos(20, 35)
		enableBeam:SizeToContents()
		local beamRange = vgui.Create("DNumSlider", MenuTab16)
		beamRange:SetText(L("Beam Range", "Beam Range"))
		beamRange:SetMin(10)
		beamRange:SetMax(physgunmaxrange:GetFloat())
		beamRange:SetDecimals(0)
		beamRange:SetConVar("vrmod_left_physgun_beam_range")
		beamRange:SetPos(20, 65)
		beamRange:SetSize(370, 20)
		local enableDamage = vgui.Create("DCheckBoxLabel", MenuTab16)
		enableDamage:SetText(L("Enable Beam Damage", "Enable Beam Damage"))
		enableDamage:SetConVar("vrmod_left_physgun_beam_damage_enable")
		enableDamage:SetPos(20, 125)
		enableDamage:SizeToContents()
		local damageAmount = vgui.Create("DNumSlider", MenuTab16)
		damageAmount:SetText(L("Beam Damage Amount", "Beam Damage Amount"))
		damageAmount:SetMin(0.0001)
		damageAmount:SetMax(0.0100)
		damageAmount:SetDecimals(4)
		damageAmount:SetConVar("vrmod_left_physgun_beam_damage")
		damageAmount:SetPos(20, 155)
		damageAmount:SetSize(370, 20)
		local enablePull = vgui.Create("DCheckBoxLabel", MenuTab16)
		enablePull:SetText(L("Enable Pull Feature (Left Secondary Fire Button)", "Enable Pull Feature (Left Secondary Fire Button)"))
		enablePull:SetConVar("vrmod_left_physgun_pull_enable")
		enablePull:SetPos(20, 185)
		enablePull:SizeToContents()
		local enableNoclip = vgui.Create("DCheckBoxLabel", MenuTab16)
		enableNoclip:SetText(L("Noclip Collision (Don't collide with player when pulling)", "Noclip Collision (Don't collide with player when pulling)"))
		enableNoclip:SetConVar("vrmod_left_physgun_noclip_enable")
		enableNoclip:SetPos(20, 215)
		enableNoclip:SizeToContents()
		local offsetX = vgui.Create("DNumSlider", MenuTab16)
		offsetX:SetText(L("Beam Offset X (Forward)", "Beam Offset X (Forward)"))
		offsetX:SetMin(-100)
		offsetX:SetMax(100)
		offsetX:SetDecimals(2)
		offsetX:SetConVar("vrmod_left_physgun_beam_offset_x")
		offsetX:SetPos(20, 245)
		offsetX:SetSize(370, 20)
		local offsetY = vgui.Create("DNumSlider", MenuTab16)
		offsetY:SetText(L("Beam Offset Y (Left/Right)", "Beam Offset Y (Left/Right)"))
		offsetY:SetMin(-100)
		offsetY:SetMax(100)
		offsetY:SetDecimals(2)
		offsetY:SetConVar("vrmod_left_physgun_beam_offset_y")
		offsetY:SetPos(20, 275)
		offsetY:SetSize(370, 20)
		local offsetZ = vgui.Create("DNumSlider", MenuTab16)
		offsetZ:SetText(L("Beam Offset Z (Up/Down)", "Beam Offset Z (Up/Down)"))
		offsetZ:SetMin(-100)
		offsetZ:SetMax(100)
		offsetZ:SetDecimals(2)
		offsetZ:SetConVar("vrmod_left_physgun_beam_offset_z")
		offsetZ:SetPos(20, 305)
		offsetZ:SetSize(370, 20)
		local instructions = vgui.Create("DLabel", MenuTab16)
		instructions:SetText(L("Use the left hand trigger to grab objects and grip button to pull them closer", "Use the left hand trigger to grab objects and grip button to pull them closer"))
		instructions:SetTextColor(Color(0, 0, 0))
		instructions:SetPos(20, 335)
		instructions:SetSize(370, 40)
		instructions:SetWrap(true)
		-- Add Restore Defaults Button (Left Hand)
		local resetButtonLeft = vgui.Create("DButton", MenuTab16)
		resetButtonLeft:SetPos(20, 380)
		resetButtonLeft:SetSize(200, 30)
		resetButtonLeft:SetText(L("Restore Default Settings", "Restore Default Settings"))
		resetButtonLeft.DoClick = function()
			RunConsoleCommand("vrmod_left_physgun_beam_enable", "1")
			RunConsoleCommand("vrmod_left_physgun_beam_range", "4096")
			RunConsoleCommand("vrmod_left_physgun_beam_damage_enable", "0")
			RunConsoleCommand("vrmod_left_physgun_beam_damage", "0.0001")
			RunConsoleCommand("vrmod_left_physgun_pull_enable", "1")
			RunConsoleCommand("vrmod_left_physgun_noclip_enable", "1")
			RunConsoleCommand("vrmod_left_physgun_beam_offset_x", "0")
			RunConsoleCommand("vrmod_left_physgun_beam_offset_y", "0")
			RunConsoleCommand("vrmod_left_physgun_beam_offset_z", "0")
		end
		local MenuTab17 = vgui.Create("DPanel", sheet)
		sheet:AddSheet(L("Physgun Right", "Physgun Right"), MenuTab17, "icon16/brick_add.png")
		MenuTab17.Paint = function(self, w, h) end
		local title = vgui.Create("DLabel", MenuTab17)
		title:SetText(L("VR Physgun Settings (RIGHT HAND)", "VR Physgun Settings (RIGHT HAND)"))
		title:SetFont("DermaDefaultBold")
		title:SetTextColor(Color(0, 0, 0))
		title:SetPos(20, 10)
		title:SizeToContents()
		local enableBeam = vgui.Create("DCheckBoxLabel", MenuTab17)
		enableBeam:SetText(L("Enable Physgun Beams", "Enable Physgun Beams"))
		enableBeam:SetConVar("vrmod_right_physgun_beam_enable")
		enableBeam:SetPos(20, 35)
		enableBeam:SizeToContents()
		local beamRange = vgui.Create("DNumSlider", MenuTab17)
		beamRange:SetText(L("Beam Range", "Beam Range"))
		beamRange:SetMin(10)
		beamRange:SetMax(physgunmaxrange:GetFloat())
		beamRange:SetDecimals(0)
		beamRange:SetConVar("vrmod_right_physgun_beam_range")
		beamRange:SetPos(20, 65)
		beamRange:SetSize(370, 20)
		local enableDamage = vgui.Create("DCheckBoxLabel", MenuTab17)
		enableDamage:SetText(L("Enable Beam Damage", "Enable Beam Damage"))
		enableDamage:SetConVar("vrmod_right_physgun_beam_damage_enable")
		enableDamage:SetPos(20, 125)
		enableDamage:SizeToContents()
		local damageAmount = vgui.Create("DNumSlider", MenuTab17)
		damageAmount:SetText(L("Beam Damage Amount", "Beam Damage Amount"))
		damageAmount:SetMin(0.0001)
		damageAmount:SetMax(0.0100)
		damageAmount:SetDecimals(4)
		damageAmount:SetConVar("vrmod_right_physgun_beam_damage")
		damageAmount:SetPos(20, 155)
		damageAmount:SetSize(370, 20)
		local enablePull = vgui.Create("DCheckBoxLabel", MenuTab17)
		enablePull:SetText(L("Enable Pull Feature (Secondary Fire Button)", "Enable Pull Feature (Secondary Fire Button)"))
		enablePull:SetConVar("vrmod_right_physgun_pull_enable")
		enablePull:SetPos(20, 185)
		enablePull:SizeToContents()
		local enableNoclip = vgui.Create("DCheckBoxLabel", MenuTab17)
		enableNoclip:SetText(L("Noclip Collision (Don't collide with player when pulling)", "Noclip Collision (Don't collide with player when pulling)"))
		enableNoclip:SetConVar("vrmod_right_physgun_noclip_enable")
		enableNoclip:SetPos(20, 215)
		enableNoclip:SizeToContents()
		local offsetX = vgui.Create("DNumSlider", MenuTab17)
		offsetX:SetText(L("Beam Offset X (Forward)", "Beam Offset X (Forward)"))
		offsetX:SetMin(-100)
		offsetX:SetMax(100)
		offsetX:SetDecimals(2)
		offsetX:SetConVar("vrmod_right_physgun_beam_offset_x")
		offsetX:SetPos(20, 245)
		offsetX:SetSize(370, 20)
		local offsetY = vgui.Create("DNumSlider", MenuTab17)
		offsetY:SetText(L("Beam Offset Y (Left/Right)", "Beam Offset Y (Left/Right)"))
		offsetY:SetMin(-100)
		offsetY:SetMax(100)
		offsetY:SetDecimals(2)
		offsetY:SetConVar("vrmod_right_physgun_beam_offset_y")
		offsetY:SetPos(20, 275)
		offsetY:SetSize(370, 20)
		local offsetZ = vgui.Create("DNumSlider", MenuTab17)
		offsetZ:SetText(L("Beam Offset Z (Up/Down)", "Beam Offset Z (Up/Down)"))
		offsetZ:SetMin(-100)
		offsetZ:SetMax(100)
		offsetZ:SetDecimals(2)
		offsetZ:SetConVar("vrmod_right_physgun_beam_offset_z")
		offsetZ:SetPos(20, 305)
		offsetZ:SetSize(370, 20)
		local instructions = vgui.Create("DLabel", MenuTab17)
		instructions:SetText(L("Use the right hand trigger to grab objects and grip button to pull them closer", "Use the right hand trigger to grab objects and grip button to pull them closer"))
		instructions:SetTextColor(Color(0, 0, 0))
		instructions:SetPos(20, 335)
		instructions:SetSize(370, 40)
		instructions:SetWrap(true)

		-- Add Restore Defaults Button
		local resetButton = vgui.Create("DButton", MenuTab17)
		resetButton:SetPos(20, 380)
		resetButton:SetSize(200, 30)
		resetButton:SetText(L("Restore Default Settings", "Restore Default Settings"))
		resetButton.DoClick = function()
			RunConsoleCommand("vrmod_right_physgun_beam_enable", "1")
			RunConsoleCommand("vrmod_right_physgun_beam_range", "4096")
			RunConsoleCommand("vrmod_right_physgun_beam_damage_enable", "0")
			RunConsoleCommand("vrmod_right_physgun_beam_damage", "0.0001")
			RunConsoleCommand("vrmod_right_physgun_pull_enable", "1")
			RunConsoleCommand("vrmod_right_physgun_noclip_enable", "1")
			RunConsoleCommand("vrmod_right_physgun_beam_offset_x", "0")
			RunConsoleCommand("vrmod_right_physgun_beam_offset_y", "0")
			RunConsoleCommand("vrmod_right_physgun_beam_offset_z", "0")
		end

		-- Dual-mode registration
		if frame.Settings02Register then
			local success = frame.Settings02Register("physgun", "VRPhysgun", "icon16/plugin.png", sheet)
			if not success then
				frame.DPropertySheet:AddSheet("VRPhysgun", sheet, "icon16/plugin.png")
			end
		else
			frame.DPropertySheet:AddSheet("VRPhysgun", sheet, "icon16/plugin.png")
		end

		end) -- pcall end
		if not ok then
			print("[VRMod] Menu hook error (addsettingsvrphysgun): " .. tostring(err))
		end
	end
)

hook.Remove("VRMod_Menu", "vrmod_physgun_menu_left")
hook.Remove("VRMod_Menu", "vrmod_physgun_menu_right")
--------[vrmod_addmenuphys.lua]End--------