--------[vrmod_addmenuphys.lua]Start--------
AddCSLuaFile()
if SERVER then return end
local convars, convarValues = vrmod.GetConvars()
hook.Add(
	"VRMod_Menu",
	"addsettingsvrphysgun",
	function(frame)
		local sheet = vgui.Create("DPropertySheet", frame.DPropertySheet)
		frame.DPropertySheet:AddSheet("VRPhysgun", sheet)
		sheet:Dock(FILL)
		local physgunmaxrange = GetConVar("physgun_maxrange") or CreateClientConVar("physgun_maxrange", "4096", true, false)
		local MenuTab16 = vgui.Create("DPanel", sheet)
		sheet:AddSheet("Physgun Left", MenuTab16, "icon16/brick.png")
		MenuTab16.Paint = function(self, w, h) end
		local title = vgui.Create("DLabel", MenuTab16)
		title:SetText("VR Physgun Settings (LEFT HAND)")
		title:SetFont("DermaDefaultBold")
		title:SetTextColor(Color(0, 0, 0))
		title:SetPos(20, 10)
		title:SizeToContents()
		local enableBeam = vgui.Create("DCheckBoxLabel", MenuTab16)
		enableBeam:SetText("Enable Physgun Beams")
		enableBeam:SetConVar("vrmod_left_physgun_beam_enable")
		enableBeam:SetPos(20, 35)
		enableBeam:SizeToContents()
		local beamRange = vgui.Create("DNumSlider", MenuTab16)
		beamRange:SetText("Beam Range")
		beamRange:SetMin(10)
		beamRange:SetMax(physgunmaxrange:GetFloat())
		beamRange:SetDecimals(0)
		beamRange:SetConVar("vrmod_left_physgun_beam_range")
		beamRange:SetPos(20, 65)
		beamRange:SetSize(370, 20)
		local enableDamage = vgui.Create("DCheckBoxLabel", MenuTab16)
		enableDamage:SetText("Enable Beam Damage")
		enableDamage:SetConVar("vrmod_left_physgun_beam_damage_enable")
		enableDamage:SetPos(20, 125)
		enableDamage:SizeToContents()
		local damageAmount = vgui.Create("DNumSlider", MenuTab16)
		damageAmount:SetText("Beam Damage Amount")
		damageAmount:SetMin(0.0001)
		damageAmount:SetMax(0.0100)
		damageAmount:SetDecimals(4)
		damageAmount:SetConVar("vrmod_left_physgun_beam_damage")
		damageAmount:SetPos(20, 155)
		damageAmount:SetSize(370, 20)
		local enablePull = vgui.Create("DCheckBoxLabel", MenuTab16)
		enablePull:SetText("Enable Pull Feature (Left Secondary Fire Button)")
		enablePull:SetConVar("vrmod_left_physgun_pull_enable")
		enablePull:SetPos(20, 185)
		enablePull:SizeToContents()
		local instructions = vgui.Create("DLabel", MenuTab16)
		instructions:SetText("Use the left hand trigger to grab objects and grip button to pull them closer")
		instructions:SetTextColor(Color(0, 0, 0))
		instructions:SetPos(20, 215)
		instructions:SetSize(370, 40)
		instructions:SetWrap(true)
		local MenuTab17 = vgui.Create("DPanel", sheet)
		sheet:AddSheet("Physgun Right", MenuTab17, "icon16/brick_add.png")
		MenuTab17.Paint = function(self, w, h) end
		local title = vgui.Create("DLabel", MenuTab17)
		title:SetText("VR Physgun Settings (RIGHT HAND)")
		title:SetFont("DermaDefaultBold")
		title:SetTextColor(Color(0, 0, 0))
		title:SetPos(20, 10)
		title:SizeToContents()
		local enableBeam = vgui.Create("DCheckBoxLabel", MenuTab17)
		enableBeam:SetText("Enable Physgun Beams")
		enableBeam:SetConVar("vrmod_right_physgun_beam_enable")
		enableBeam:SetPos(20, 35)
		enableBeam:SizeToContents()
		local beamRange = vgui.Create("DNumSlider", MenuTab17)
		beamRange:SetText("Beam Range")
		beamRange:SetMin(10)
		beamRange:SetMax(physgunmaxrange:GetFloat())
		beamRange:SetDecimals(0)
		beamRange:SetConVar("vrmod_right_physgun_beam_range")
		beamRange:SetPos(20, 65)
		beamRange:SetSize(370, 20)
		local enableDamage = vgui.Create("DCheckBoxLabel", MenuTab17)
		enableDamage:SetText("Enable Beam Damage")
		enableDamage:SetConVar("vrmod_right_physgun_beam_damage_enable")
		enableDamage:SetPos(20, 125)
		enableDamage:SizeToContents()
		local damageAmount = vgui.Create("DNumSlider", MenuTab17)
		damageAmount:SetText("Beam Damage Amount")
		damageAmount:SetMin(0.0001)
		damageAmount:SetMax(0.0100)
		damageAmount:SetDecimals(4)
		damageAmount:SetConVar("vrmod_right_physgun_beam_damage")
		damageAmount:SetPos(20, 155)
		damageAmount:SetSize(370, 20)
		local enablePull = vgui.Create("DCheckBoxLabel", MenuTab17)
		enablePull:SetText("Enable Pull Feature (Secondary Fire Button)")
		enablePull:SetConVar("vrmod_right_physgun_pull_enable")
		enablePull:SetPos(20, 185)
		enablePull:SizeToContents()
		local instructions = vgui.Create("DLabel", MenuTab17)
		instructions:SetText("Use the right hand trigger to grab objects and grip button to pull them closer")
		instructions:SetTextColor(Color(0, 0, 0))
		instructions:SetPos(20, 215)
		instructions:SetSize(370, 40)
		instructions:SetWrap(true)
	end
)

hook.Remove("VRMod_Menu", "vrmod_physgun_menu_left")
hook.Remove("VRMod_Menu", "vrmod_physgun_menu_right")
--------[vrmod_addmenuphys.lua]End--------