-- VRMod Beginner Guide - Japanese Language Strings
-- 日本語文字列

AddCSLuaFile()
if SERVER then return end

VRMOD_GUIDE_LANG = VRMOD_GUIDE_LANG or {}
VRMOD_GUIDE_LANG.ja = {

-- ============================================================
-- UI Chrome
-- ============================================================
window_title = "VRMod 初心者ガイド",
search_placeholder = "設定を検索... (ConVar名または説明)",
lang_label = "言語:",
btn_reset_category = "このカテゴリをデフォルトに戻す",
btn_reset_all = "すべての設定をデフォルトに戻す",
btn_open_main_menu = "メインVRModメニューを開く",
btn_open_guide = "初心者ガイドを開く",
btn_yes = "はい",
btn_no = "いいえ",
confirm_title = "リセットの確認",
confirm_reset_all = "本当にすべての設定をデフォルトに戻しますか？",
confirm_reset_category = "このカテゴリの設定をすべてデフォルトに戻しますか？",
help_prefix = "これは何？",
search_results = "検索結果",
no_results = "検索に一致する設定が見つかりません。",
too_many_results = "最初の100件を表示中。検索を絞り込んでください。",
results_found = "件の結果",
status_settings = "設定項目",
status_lang_en = "英語",
status_lang_ja = "日本語",
status_lang_ru = "ロシア語",
status_lang_zh = "中国語",
tip_reset_to = "デフォルトに戻す",
tip_server_setting = "これはサーバー側の設定です。サーバーホストのみ変更可能です。",
guide_tab_desc = "すべてのVRMod機能の初心者向け設定ガイド\n多言語対応の説明付き\n\n対応言語: 英語、日本語、ロシア語、中国語",

-- ============================================================
-- Welcome / Getting Started
-- ============================================================
welcome_title = "VRModへようこそ！",
welcome_desc = "このガイドでは、すべてのVRMod設定をわかりやすい説明付きで調整できます。\n左のサイドバーからカテゴリを選んで始めましょう。\n\nすべての変更は即座に反映されます。「適用」ボタンを押す必要はありません！",
quickstart_title = "クイックスタート",
tip_body = "1. 「体とスケール」で、VRの体を自分の実際の身長に合わせましょう",
tip_gameplay = "2. 「ゲームプレイ」で、テレポートやジャンプなどの基本操作を確認しましょう",
tip_hud = "3. 「HUDとUI」で、インターフェースの位置を快適に調整しましょう",
tip_reset = "4. 各設定にはデフォルトに戻すボタンがあります",
tip_search = "5. 上部の検索バーで、どの設定でもすばやく見つけられます",
vr_status_title = "VRステータス",
vr_status_active = "VRは有効です",
vr_status_inactive = "VRは無効です。メインVRModメニューからVRを開始してください（コンソール: vrmod）",

-- ============================================================
-- Category Names
-- ============================================================
cat_getting_started = "はじめに",
cat_body_scale = "体とスケール",
cat_gameplay = "ゲームプレイ",
cat_movement = "移動",
cat_hud_ui = "HUDとUI",
cat_quickmenu = "クイックメニュー",
cat_melee = "VR近接戦闘",
cat_weapons = "武器",
cat_holster = "ホルスター",
cat_physgun = "物理ガン",
cat_climbing = "クライミング",
cat_vehicles = "車両",
cat_network = "ネットワーク",
cat_optimization = "パフォーマンス",
cat_developer = "開発者",
cat_commands = "コマンド",

-- ============================================================
-- Category Help Texts
-- ============================================================
help_body_scale = "VRの体を実際の身長や体格に合わせます。キャラクターが高すぎたり低すぎたりする場合はここから始めましょう。「スケール」と「目の高さ」が最も重要な設定です。",
help_gameplay = "ジャンプ、テレポート、フラッシュライトの位置、アイテムの拾い方など、基本的なゲームプレイの設定です。",
help_movement = "VRでの移動方法を設定します。ダイレクト移動、ステップ式移動、武器ビューモデルの位置調整などがあります。",
help_hud_ui = "ヘッドアップディスプレイ、UIパネルの位置、VRでのメニュー表示方法を設定します。",
help_quickmenu = "コントローラーのボタンで開けるVRクイックアクセスメニューに表示する項目を選びます。",
help_melee = "VR近接戦闘システム — パンチ、キック、銃での殴打攻撃で、手の物理トラッキングを使用します。ダメージ、ヒットボックス、フィードバックを設定できます。",
help_weapons = "武器の操作機能 — フォアグリップ（両手での照準）とマガジンボーンシステム（リアルなリロード）を設定します。",
help_holster = "武器ホルスターシステム — 体に装着したポーチから武器を収納・取り出しできます。初心者にはタイプ2（シンプルポーチ）がおすすめです。",
help_physgun = "左右の手の物理ガンのビーム設定です。ビームの範囲、ダメージ、オフセットを調整できます。",
help_climbing = "VRクライミングシステム — 壁、出っ張り、表面をつかんでよじ登れます。ウォールランやスライディングの機能も含まれています。",
help_vehicles = "LVS車両の入力モードやシートの動作など、車両関連の設定です。",
help_network = "サーバーのネットワーク設定 — 同期遅延、ティックレート、フレーム保存数です。マルチプレイのスムーズさに影響します。",
help_optimization = "パフォーマンス最適化の設定とコマンドです。ラグが発生する場合にFPSを改善するために使います。",
help_developer = "開発者ツール、デバッグコマンド、緊急停止の設定です。上級者やトラブルシューティング用です。",
help_commands = "すべてのコンソールコマンドをクリックで実行できるボタンです。コンソールに入力する必要はありません！",

-- ============================================================
-- Section Headers
-- ============================================================
section_basic_body = "基本的な体の設定",
section_seated_mode = "着席モード",
section_handedness = "利き手（左手/右手）",
section_character_advanced = "キャラクター詳細設定",
section_animations = "アニメーションの上書き",
section_pickup_server = "ピックアップ設定（サーバー）",
section_viewmodel = "ビューモデルの装着",
section_render_tweaks = "描画の微調整",
section_hud = "HUD表示",
section_ui_panels = "UIパネルの動作",
section_attachment_points = "メニューの装着位置",
section_quickmenu_items = "クイックメニューの項目",
section_melee_enable = "近接戦闘の切替（クライアント）",
section_melee_server = "近接戦闘の切替（サーバー）",
section_melee_damage = "ダメージ設定（サーバー）",
section_melee_client = "クライアント近接設定",
section_melee_fist = "拳の設定",
section_melee_blocking = "ブロックのエミュレーション",
section_melee_commands = "カスタムヒットコマンド",
section_foregrip = "フォアグリップ（両手照準）",
section_foregrip_advanced = "フォアグリップの微調整",
section_magazine = "マガジンボーンの位置",
section_holster_type2 = "ホルスタータイプ2（シンプルポーチ）",
section_pouch_slots = "ポーチスロット 1〜5（右手）",
section_pouch_left_hand = "ポーチスロット 6〜8（左手）",
section_holster_type1_right = "ホルスタータイプ1 — 右手",
section_holster_type1_left = "ホルスタータイプ1 — 左手",
section_physgun_general = "全般",
section_physgun_left = "左手ビーム",
section_physgun_right = "右手ビーム",
section_beam_pickup = "ビームピックアップ",
section_climbing_basic = "クライミングの基本",
section_climbing_surfaces = "登れる表面",
section_climbing_palm = "手のひらオフセット（上級者向け）",
section_wallrun = "ウォールラン",
section_slide = "スライディング",
section_climbing_server = "クライミングサーバー設定",
section_wallrun_server = "ウォールランサーバー設定",
section_slide_server = "スライディングサーバー設定",
section_climbing_debug = "クライミングデバッグ",
section_auto_settings = "自動適用設定",
section_optimization_commands = "最適化コマンド",
section_dev_general = "開発者オプション",
section_emergency_stop = "VR緊急停止",
section_keyguide = "キーガイドHUD",
section_debug_commands = "デバッグコマンド",
section_cmd_general = "一般コマンド",
section_cmd_presets = "プリセット管理",
section_cmd_optimization = "最適化",
section_cmd_holster = "ホルスターリセット",
section_cmd_debug = "デバッグツール",
section_cmd_mock = "モックVR（テスト用）",
section_cmd_misc = "その他",

-- ============================================================
-- Body & Scale ConVars
-- ============================================================
cvar_vrmod_scale = "キャラクタースケール",
tip_vrmod_scale = "VRキャラクターモデルの全体的な大きさです。デフォルト: 38.7。ゲーム内で背が高すぎたり低すぎたりする場合に調整してください。",
cvar_vrmod_characterEyeHeight = "目の高さ",
tip_vrmod_characterEyeHeight = "地面からキャラクターの目までの高さです。自然な動きのために、実際の自分の目の高さに合わせてください。デフォルト: 66.8",
cvar_vrmod_characterHeadToHmdDist = "頭部〜HMD間距離",
tip_vrmod_characterHeadToHmdDist = "キャラクターの頭のボーンからヘッドセットまでの距離です。頭のモデルの位置合わせに影響します。デフォルト: 6.3",
cvar_vrmod_crouchthreshold = "しゃがみしきい値",
tip_vrmod_crouchthreshold = "ゲームがしゃがみと判定するまでに、実際にどれだけしゃがむ必要があるかです。デフォルト: 40",
cvar_vrmod_znear = "近クリップ面（Z-Near）",
tip_vrmod_znear = "これより近いオブジェクトは見えなくなります。自分の頭の中が見える場合は値を上げてください。デフォルト: 1.0",
cvar_vrmod_seated = "着席モードを有効にする",
tip_vrmod_seated = "座ってプレイする場合に有効にします。キャラクターが通常の高さで立つように高さオフセットが追加されます。",
cvar_vrmod_seatedoffset = "着席時の高さオフセット",
tip_vrmod_seatedoffset = "着席モードで追加される高さです。高さ調整メニューから調整してください。",
cvar_vrmod_LeftHand = "左利きモード",
tip_vrmod_LeftHand = "利き手を左手に切り替えます。左のコントローラーがメイン（射撃）手になります。",
cvar_vrmod_lefthandleftfire = "左手で射撃",
tip_vrmod_lefthandleftfire = "左利きモード時に、左トリガーで武器を発射します。",
cvar_vrmod_LeftHandmode = "左手モードのスタイル",
tip_vrmod_LeftHandmode = "左手切替の動作方式です。通常またはミラーモード。",
cvar_vrmod_oldcharacteryaw = "旧キャラクター回転",
tip_vrmod_oldcharacteryaw = "旧方式のキャラクター回転を使用します。一部のプレイヤーモデルの問題修正に役立つ場合があります。",
cvar_vrmod_animation_Enable = "アニメーション有効",
tip_vrmod_animation_Enable = "キャラクターの体のアニメーション（歩行、待機、走り）を有効にします。パフォーマンスが気になる場合は無効にしてください。",
cvar_vrmod_hide_head = "頭のモデルを非表示",
tip_vrmod_hide_head = "キャラクターの頭のモデルを非表示にして、視界を妨げないようにします。",
cvar_vrmod_hide_head_pos_x = "頭の非表示オフセット X",
tip_vrmod_hide_head_pos = "頭を非表示にする位置を微調整します。まだ頭の一部が見える場合に調整してください。",
cvar_vrmod_hide_head_pos_y = "頭の非表示オフセット Y",
cvar_vrmod_hide_head_pos_z = "頭の非表示オフセット Z",
cvar_vrmod_idle_act = "待機アニメーション",
tip_vrmod_idle_act = "静止時のアニメーションシーケンス名です。デフォルト: ACT_HL2MP_IDLE",
cvar_vrmod_walk_act = "歩行アニメーション",
tip_vrmod_walk_act = "歩行時のアニメーションシーケンス名です。デフォルト: ACT_HL2MP_WALK",
cvar_vrmod_run_act = "走りアニメーション",
tip_vrmod_run_act = "走り時のアニメーションシーケンス名です。デフォルト: ACT_HL2MP_RUN",
cvar_vrmod_jump_act = "ジャンプアニメーション",
tip_vrmod_jump_act = "ジャンプ時のアニメーションシーケンス名です。デフォルト: ACT_HL2MP_JUMP_PASSIVE",

-- Dropdown options
opt_lefthandmode_0 = "通常",
opt_lefthandmode_1 = "ミラー",

-- ============================================================
-- Gameplay ConVars
-- ============================================================
cvar_vrmod_autojumpduck = "ジャンプ時に自動しゃがみ",
tip_vrmod_autojumpduck = "ON: ジャンプキーでしゃがみ+ジャンプを同時に送信（より高いジャンプ）。OFF: ジャンプのみ。デフォルト: ON",
cvar_vrmod_allow_teleport_client = "テレポートを有効にする",
tip_vrmod_allow_teleport_client = "テレポート移動を許可します。歩く代わりにポイントしてテレポートできます。デフォルト: ON",
cvar_vrmod_flashlight_attachment = "フラッシュライトの位置",
tip_vrmod_flashlight_attachment = "フラッシュライトの装着場所です。0=右手、1=左手、2=ヘッドセット",
cvar_vrmod_manualpickups = "手動ピックアップモード",
tip_vrmod_manualpickups = "Hugoの手動ピックアップシステムを有効にします。よりリアルなアイテム取得ができます。デフォルト: ON",
cvar_vrmod_pickup_weight = "ピックアップ重量制限",
tip_vrmod_pickup_weight = "持ち上げられるオブジェクトの最大重量です。サーバー設定。デフォルト: 100",
cvar_vrmod_pickup_range = "ピックアップ範囲",
tip_vrmod_pickup_range = "オブジェクトをつかめる距離です。サーバー設定。デフォルト: 1.1",
cvar_vrmod_pickup_limit = "ピックアップ上限",
tip_vrmod_pickup_limit = "同時に持てるオブジェクトの最大数です。サーバー設定。デフォルト: 1",

section_pickup_client = "ピックアップ設定（クライアント）",
cvar_vrmod_unoff_pickup_weight_client = "クライアント重量制限",
tip_vrmod_unoff_pickup_weight_client = "個人の最大ピックアップ重量。0=無効（サーバー制限のみ使用）。設定時の有効制限=min(サーバー値, クライアント値)。デフォルト: 0",
cvar_vrmod_unoff_pickup_limit_client = "クライアントピックアップ制限",
tip_vrmod_unoff_pickup_limit_client = "個人のピックアップフィルターレベル。0=無効、1=標準(VPHYSICSのみ)、2=厳格(移動可能+マルチオブジェクト除外)、3=ピックアップ無効。max(サーバー値, クライアント値)で厳しい方が適用。デフォルト: 0",
cvar_vrmod_unoff_rotate_held_enable = "持ったオブジェクトの回転を有効化",
tip_vrmod_unoff_rotate_held_enable = "セカンダリファイアを押すとオブジェクトの向きが固定されます。ボタンを押しながら手を動かして離すと「持ち直し」ができます。0=元の固定向き。デフォルト: 1",
cvar_vrmod_unoff_rotate_held_speed = "回転速度",
tip_vrmod_unoff_rotate_held_speed = "0=スタビライズ/持ち直し（手を動かしてもオブジェクトは固定）。1=通常追従。1以上=増幅回転。デフォルト: 0",

-- Dropdown options
opt_flashlight_right = "右手",
opt_flashlight_left = "左手",
opt_flashlight_hmd = "ヘッドセット（HMD）",

-- ============================================================
-- Movement ConVars
-- ============================================================
cvar_vrmod_directMovement = "ダイレクト移動",
tip_vrmod_directMovement = "手や頭が向いている方向に移動します。デフォルト: ON",
cvar_vrmod_locomotion_step = "ステップ式移動",
tip_vrmod_locomotion_step = "酔い軽減のためのステップベース移動を有効にします。デフォルト: ON",
cvar_vrmod_noTrigger = "トリガー歩行防止",
tip_vrmod_noTrigger = "トリガーを押しているときに誤って移動するのを防ぎます。デフォルト: ON",
cvar_vrmod_attach_viewmodel = "ビューモデルを装着",
tip_vrmod_attach_viewmodel = "武器のビューモデルを手に装着します。デフォルト: ON",
cvar_vrmod_viewmodel_normal_enable = "通常ビューモデル",
tip_vrmod_viewmodel_normal_enable = "標準的な武器ビューモデルを表示します。デフォルト: ON",
cvar_vrmod_viewmodel_offset_x = "ビューモデルオフセット X",
tip_vrmod_viewmodel_offset = "手に対するビューモデルの位置を微調整します。",
cvar_vrmod_viewmodel_offset_y = "ビューモデルオフセット Y",
cvar_vrmod_viewmodel_offset_z = "ビューモデルオフセット Z",
cvar_vrmod_viewmodel_offset_ang_p = "ビューモデル角度 ピッチ",
tip_vrmod_viewmodel_offset_ang = "手に対するビューモデルの回転を微調整します。",
cvar_vrmod_viewmodel_offset_ang_y = "ビューモデル角度 ヨー",
cvar_vrmod_viewmodel_offset_ang_r = "ビューモデル角度 ロール",
cvar_vrmod_rtWidth_Multiplier = "RT幅の倍率",
tip_vrmod_rtWidth_Multiplier = "レンダーターゲットの幅倍率です。高いほどシャープですが重くなります。デフォルト: 2.0",
cvar_vrmod_rtHeight_Multiplier = "RT高さの倍率",
tip_vrmod_rtHeight_Multiplier = "レンダーターゲットの高さ倍率です。高いほどシャープですが重くなります。デフォルト: 1.0",
cvar_vrmod_error_check_method = "エラーチェック方式",
tip_vrmod_error_check_method = "エラーの検出と処理の方法です。0=無効、1=標準。デフォルト: 1",

-- ============================================================
-- HUD & UI ConVars
-- ============================================================
cvar_vrmod_hud = "HUDを有効にする",
tip_vrmod_hud = "VRでヘッドアップディスプレイを表示します。デフォルト: ON",
cvar_vrmod_hudcurve = "HUDのカーブ",
tip_vrmod_hudcurve = "HUDの曲がり具合です。0=平面、180=完全カーブ。デフォルト: 60",
cvar_vrmod_huddistance = "HUDの距離",
tip_vrmod_huddistance = "顔からHUDまでの距離です。デフォルト: 60",
cvar_vrmod_hudscale = "HUDのスケール",
tip_vrmod_hudscale = "HUD表示の大きさです。デフォルト: 0.05",
cvar_vrmod_hudtestalpha = "HUDテスト透明度",
tip_vrmod_hudtestalpha = "テスト用のHUD透明度です。0=非表示、255=完全不透明。デフォルト: 0",
cvar_vre_ui_attachtohand = "UIを手に装着",
tip_vre_ui_attachtohand = "UIパネルを空中に浮かべる代わりに手に装着します。デフォルト: ON",
cvar_vrmod_ui_outline = "UIアウトライン",
tip_vrmod_ui_outline = "UIパネルの周りにアウトラインを描画して見やすくします。デフォルト: ON",
cvar_vrmod_ui_realtime = "UIリアルタイム更新",
tip_vrmod_ui_realtime = "UIパネルをリアルタイムで更新します。パフォーマンスのために無効にできます。デフォルト: OFF",
cvar_vrmod_cameraoverride = "カメラオーバーライド",
tip_vrmod_cameraoverride = "VRレンダリング用にカメラを上書きします。デフォルト: ON",
cvar_vrmod_keyboard_uichatkey = "チャットキーでUI",
tip_vrmod_keyboard_uichatkey = "チャットキーでVRキーボードを開きます。デフォルト: ON",
cvar_vrmod_hud_visible_quickmenukey = "クイックメニューキーHUD",
tip_vrmod_hud_visible_quickmenukey = "HUDにクイックメニューキーの表示を出します。デフォルト: OFF",
cvar_vrmod_attach_quickmenu = "クイックメニューの位置",
tip_vrmod_attach_quickmenu = "クイックメニューの手の装着位置です（1〜4）。デフォルト: 4",
cvar_vrmod_attach_weaponmenu = "武器メニューの位置",
tip_vrmod_attach_weaponmenu = "武器メニューの手の装着位置です（1〜4）。デフォルト: 3",
cvar_vrmod_attach_popup = "ポップアップの位置",
tip_vrmod_attach_popup = "ポップアップダイアログの手の装着位置です（1〜4）。デフォルト: 4",

-- Dropdown options
opt_attach_1 = "位置 1",
opt_attach_2 = "位置 2",
opt_attach_3 = "位置 3",
opt_attach_4 = "位置 4",

-- ============================================================
-- Quick Menu ConVars
-- ============================================================
cvar_vrmod_quickmenu_use_custom = "カスタムクイックメニューを使用",
tip_vrmod_quickmenu_use_custom = "デフォルトの代わりにカスタムクイックメニューレイアウトを使用します。デフォルト: OFF",
cvar_vrmod_quickmenu_mapbrowser_enable = "マップブラウザ",
tip_vrmod_quickmenu_item = "VRクイックメニューにこの項目を表示/非表示にします。",
cvar_vrmod_quickmenu_exit = "VRを終了",
cvar_vrmod_quickmenu_vgui_reset_menu = "VGUIリセットメニュー",
cvar_vrmod_quickmenu_vre_gbradial_menu = "ラジアルメニュー",
cvar_vrmod_quickmenu_chat = "チャット",
cvar_vrmod_quickmenu_seated_menu = "シートモード",
cvar_vrmod_quickmenu_togglemirror = "ミラー切替",
cvar_vrmod_quickmenu_togglevehiclemode = "車両モード切替",
cvar_vrmod_quickmenu_noclip = "ノークリップ",
cvar_vrmod_quickmenu_spawnmenu = "スポーンメニュー",
cvar_vrmod_quickmenu_contextmenu = "コンテキストメニュー",
cvar_vrmod_quickmenu_arccw = "ArcCWカスタマイズ",

-- ============================================================
-- Melee ConVars
-- ============================================================
cvar_vrmelee_usegunmelee = "銃で殴る（クライアント）",
tip_vrmelee_usegunmelee = "銃を近接武器として振って攻撃する機能を有効にします（クライアント設定）。",
cvar_vrmelee_usefist = "拳を使う（クライアント）",
tip_vrmelee_usefist = "パンチ攻撃を有効にします（クライアント設定）。",
cvar_vrmelee_usekick = "キックを使う（クライアント）",
tip_vrmelee_usekick = "フットトラッカーを使ったキック攻撃を有効にします（クライアント設定）。デフォルト: OFF",
cvar_vrmelee_gunmelee = "銃殴りを許可（サーバー）",
tip_vrmelee_gunmelee = "サーバーが銃での近接攻撃を許可します。デフォルト: ON",
cvar_vrmelee_fist = "拳攻撃を許可（サーバー）",
tip_vrmelee_fist = "サーバーが拳攻撃を許可します。デフォルト: ON",
cvar_vrmelee_kick = "キックを許可（サーバー）",
tip_vrmelee_kick = "サーバーがキック攻撃を許可します。デフォルト: ON",
cvar_vrmelee_damage_low = "低ダメージ",
tip_vrmelee_damage = "この速度帯で与えるダメージです。サーバー設定。",
cvar_vrmelee_damage_medium = "中ダメージ",
cvar_vrmelee_damage_high = "高ダメージ",
cvar_vrmelee_damage_velocity_low = "低速度しきい値",
tip_vrmelee_velocity = "このダメージ帯を発動するために必要な手の速度です。",
cvar_vrmelee_damage_velocity_medium = "中速度しきい値",
cvar_vrmelee_damage_velocity_high = "高速度しきい値",
cvar_vrmelee_impact = "衝撃力",
tip_vrmelee_impact = "ヒット時に加わる物理的な押し力です。デフォルト: 5.0",
cvar_vrmelee_delay = "ヒット遅延",
tip_vrmelee_delay = "接触後にダメージが発生するまでの遅延です。デフォルト: 0.0",
cvar_vrmelee_range = "ヒット範囲",
tip_vrmelee_range = "近接攻撃の最大距離です。デフォルト: 22",
cvar_vrmelee_high_velocity_fire_bullets = "高速弾丸モード",
tip_vrmelee_high_velocity_fire_bullets = "極端な速度の場合、近接の代わりに弾丸トレースを使用します。実験的機能。",
cvar_vrmelee_cooldown = "クールダウン時間",
tip_vrmelee_cooldown = "近接攻撃の最小間隔です。デフォルト: 0.2秒",
cvar_vrmelee_hitbox_width = "ヒットボックス幅",
tip_vrmelee_hitbox = "手に付く見えないヒットボックスの大きさです。",
cvar_vrmelee_hitbox_length = "ヒットボックス長さ",
cvar_vrmelee_hit_feedback = "ヒットフィードバック",
tip_vrmelee_hit_feedback = "何かに当たったときの視覚/触覚フィードバックです。デフォルト: ON",
cvar_vrmelee_hit_sound = "ヒットサウンド",
tip_vrmelee_hit_sound = "ヒット時に効果音を再生します。デフォルト: ON",
cvar_vrmelee_fist_collision = "拳のコリジョンモデル",
tip_vrmelee_fist_collision = "拳に見えるコリジョンモデルを表示します。デバッグに便利です。",
cvar_vrmelee_fist_visible = "拳を表示",
tip_vrmelee_fist_visible = "拳のコリジョンモデルを見えるようにします。デフォルト: OFF",
cvar_vrmelee_fist_collisionmodel = "拳のモデルパス",
tip_vrmelee_fist_collisionmodel = "拳のコリジョンに使用するモデルファイルです。",
cvar_vrmelee_emulateblocking = "ブロックエミュレーション",
tip_vrmelee_emulateblocking = "両手を上げてブロックをエミュレートします（attack2入力を送信）。デフォルト: OFF",
cvar_vrmelee_emulateblockbutton = "ブロックボタン（押下）",
tip_vrmelee_emulateblockbutton = "ブロック姿勢に入ったときに送信されるコンソールコマンドです。",
cvar_vrmelee_emulateblockbutton_release = "ブロックボタン（解除）",
tip_vrmelee_emulateblockbutton_release = "ブロック姿勢を解除したときに送信されるコンソールコマンドです。",
cvar_vrmelee_emulateblock_threshold_low = "ブロック角度（低）",
tip_vrmelee_emulateblock_threshold = "ブロックと判定される手の角度範囲です。",
cvar_vrmelee_emulateblock_threshold_high = "ブロック角度（高）",
cvar_vrmelee_lefthand_command = "左手ヒットコマンド",
tip_vrmelee_hand_command = "この手が何かに当たったときに実行するカスタムコンソールコマンドです。",
cvar_vrmelee_righthand_command = "右手ヒットコマンド",
cvar_vrmelee_leftfoot_command = "左足キックコマンド",
tip_vrmelee_foot_command = "この足でキックしたときに実行するカスタムコンソールコマンドです。",
cvar_vrmelee_rightfoot_command = "右足キックコマンド",
cvar_vrmelee_gunmelee_command = "銃殴りヒットコマンド",
tip_vrmelee_gunmelee_command = "銃で殴ったときに実行するカスタムコンソールコマンドです。",

-- ============================================================
-- Weapons (Foregrip + Magazine)
-- ============================================================
cvar_vrmod_Foregripmode_enable = "フォアグリップを有効にする",
tip_vrmod_Foregripmode_enable = "両手での武器照準です。オフハンドで武器の前方をつかみます。デフォルト: ON",
cvar_vrmod_Foregripmode_range = "フォアグリップ範囲",
tip_vrmod_Foregripmode_range = "つかむためにオフハンドをどれだけ近づける必要があるかです。デフォルト: 30",
cvar_vrmod_Foregripmode_key_leftprimary = "左メインキーでつかむ",
tip_vrmod_Foregripmode_key = "フォアグリップを起動するボタンです。",
cvar_vrmod_Foregripmode_key_leftgrab = "左グラブキーでつかむ",
cvar_vrmod_Foregripmode_rotation_blend = "回転ブレンド",
tip_vrmod_Foregripmode_rotation_blend = "武器がオフハンドに向かって回転する滑らかさです。1.0=即座。デフォルト: 1.0",
cvar_vrmod_Foregripmode_offset_x = "フォアグリップオフセット X",
tip_vrmod_Foregripmode_offset = "フォアグリップのつかみ位置を微調整します。",
cvar_vrmod_Foregripmode_offset_y = "フォアグリップオフセット Y",
cvar_vrmod_Foregripmode_offset_z = "フォアグリップオフセット Z",
cvar_vrmod_Foregripmode_ang_pitch = "フォアグリップ角度 ピッチ",
tip_vrmod_Foregripmode_ang = "フォアグリップのつかみ角度を微調整します。",
cvar_vrmod_Foregripmode_ang_yaw = "フォアグリップ角度 ヨー",
cvar_vrmod_Foregripmode_ang_roll = "フォアグリップ角度 ロール",
cvar_vrmod_mag_pos_x = "マガジン位置 X",
tip_vrmod_mag_pos = "武器上の着脱可能マガジンの位置オフセットです。",
cvar_vrmod_mag_pos_y = "マガジン位置 Y",
cvar_vrmod_mag_pos_z = "マガジン位置 Z",
cvar_vrmod_mag_ang_p = "マガジン角度 ピッチ",
tip_vrmod_mag_ang = "着脱可能マガジンの回転です。",
cvar_vrmod_mag_ang_y = "マガジン角度 ヨー",
cvar_vrmod_mag_ang_r = "マガジン角度 ロール",
cvar_vrmod_mag_bones = "マガジンボーン名",
tip_vrmod_mag_bones = "マガジンとして検出するカンマ区切りのボーン名です。デフォルト: mag,ammo,clip,cylin,shell,magazine",

-- ============================================================
-- Holster ConVars
-- ============================================================
cvar_vrmod_pouch_enabled = "ポーチシステムを有効にする",
tip_vrmod_pouch_enabled = "タイプ2ホルスター（シンプルポーチシステム）を有効にします。デフォルト: ON",
cvar_vrmod_pouch_visiblename = "ポーチ名を表示（3D）",
tip_vrmod_pouch_visiblename = "3D空間でポーチの上に武器名を表示します。",
cvar_vrmod_pouch_visiblename_hud = "ポーチ名を表示（HUD）",
tip_vrmod_pouch_visiblename_hud = "HUD上に武器名を表示します。",
cvar_vrmod_pouch_lefthandwep_enable = "左手武器ポーチ",
tip_vrmod_pouch_lefthandwep_enable = "スロット6〜8で左手用の別武器を有効にします。",
cvar_vrmod_pouch_pickup_sound = "ピックアップ音",
tip_vrmod_pouch_pickup_sound = "ポーチから取り出したときに再生されるサウンドファイルです。",
cvar_pouch_slot_enabled_1 = "スロット 1 有効",
tip_pouch_slot = "このホルスタースロットを有効/無効にします。",
cvar_pouch_weapon_1 = "スロット 1 武器",
tip_pouch_weapon = "このスロットに割り当てる武器クラス名です（例: weapon_pistol）。空欄で任意の武器。",
cvar_pouch_size_1 = "スロット 1 サイズ",
tip_pouch_size = "このポーチスロットの検出範囲です。",
cvar_pouch_slot_enabled_2 = "スロット 2 有効",
cvar_pouch_weapon_2 = "スロット 2 武器",
cvar_pouch_size_2 = "スロット 2 サイズ",
cvar_pouch_slot_enabled_3 = "スロット 3 有効",
cvar_pouch_weapon_3 = "スロット 3 武器",
cvar_pouch_size_3 = "スロット 3 サイズ",
cvar_pouch_slot_enabled_4 = "スロット 4 有効",
cvar_pouch_weapon_4 = "スロット 4 武器",
cvar_pouch_size_4 = "スロット 4 サイズ",
cvar_pouch_slot_enabled_5 = "スロット 5 有効",
cvar_pouch_weapon_5 = "スロット 5 武器",
cvar_pouch_size_5 = "スロット 5 サイズ",
cvar_pouch_slot_enabled_6 = "スロット 6 有効（左）",
cvar_pouch_weapon_6 = "スロット 6 武器（右）",
cvar_pouch_weapon_6_left = "スロット 6 武器（左）",
tip_pouch_weapon_left = "このスロットの左手用武器です。",
cvar_pouch_size_6 = "スロット 6 サイズ",
cvar_pouch_slot_enabled_7 = "スロット 7 有効（左）",
cvar_pouch_weapon_7 = "スロット 7 武器（右）",
cvar_pouch_weapon_7_left = "スロット 7 武器（左）",
cvar_pouch_size_7 = "スロット 7 サイズ",
cvar_pouch_slot_enabled_8 = "スロット 8 有効（左）",
cvar_pouch_weapon_8 = "スロット 8 武器（右）",
cvar_pouch_weapon_8_left = "スロット 8 武器（左）",
cvar_pouch_size_8 = "スロット 8 サイズ",
cvar_vrmod_unoff_dupe_reusable = "複製可能なデュプシステム",
tip_vrmod_unoff_dupe_reusable = "ホルスター設定の複製を許可します。デフォルト: OFF",

-- Holster Type 1
cvar_vrmod_weppouch_Pelvis = "腰スロット（右）",
tip_vrmod_weppouch_slot = "このボディホルスタースロットを有効にします。",
cvar_vrmod_weppouch_weapon_Pelvis = "腰の武器",
tip_vrmod_weppouch_weapon = "このスロットに割り当てる武器クラスです。",
cvar_vrmod_weppouch_weapon_lock_Pelvis = "腰の武器をロック",
tip_vrmod_weppouch_lock = "このスロットを特定の武器にロックします。",
cvar_vrmod_weppouch_dist_Pelvis = "腰の距離",
tip_vrmod_weppouch_dist = "このホルスタースロットの検出距離です。",
cvar_vrmod_weppouch_Head = "頭スロット（右）",
cvar_vrmod_weppouch_weapon_Head = "頭の武器",
cvar_vrmod_weppouch_weapon_lock_Head = "頭の武器をロック",
cvar_vrmod_weppouch_dist_head = "頭の距離",
cvar_vrmod_weppouch_Spine = "背中スロット（右）",
cvar_vrmod_weppouch_weapon_Spine = "背中の武器",
cvar_vrmod_weppouch_weapon_lock_Spine = "背中の武器をロック",
cvar_vrmod_weppouch_dist_spine = "背中の距離",
cvar_vrmod_weppouch_visiblerange = "範囲インジケーターを表示",
tip_vrmod_weppouch_visiblerange = "ホルスターの検出範囲を視覚的に表示します。",
cvar_vrmod_weppouch_visiblename_t1 = "名前を表示（タイプ1）",
tip_vrmod_weppouch_visiblename = "ホルスター位置に武器名を表示します。",
cvar_vrmod_head_visible = "頭ボーン表示",
tip_vrmod_head_visible = "頭のボーンのホルスターマーカーを表示します。",

-- Type 1 Left
cvar_vrmod_weppouch_left_Pelvis = "腰スロット（左）",
cvar_vrmod_weppouch_weapon_left_Pelvis = "腰の武器（左）",
cvar_vrmod_weppouch_weapon_lock_left_Pelvis = "腰をロック（左）",
cvar_vrmod_weppouch_dist_Pelvis_left = "腰の距離（左）",
cvar_vrmod_weppouch_left_Head = "頭スロット（左）",
cvar_vrmod_weppouch_weapon_left_Head = "頭の武器（左）",
cvar_vrmod_weppouch_weapon_lock_left_Head = "頭をロック（左）",
cvar_vrmod_weppouch_dist_head_left = "頭の距離（左）",
cvar_vrmod_weppouch_left_Spine = "背中スロット（左）",
cvar_vrmod_weppouch_weapon_left_Spine = "背中の武器（左）",
cvar_vrmod_weppouch_weapon_lock_left_Spine = "背中をロック（左）",
cvar_vrmod_weppouch_dist_spine_left = "背中の距離（左）",
cvar_vrmod_weppouch_visiblerange_left = "範囲を表示（左）",
cvar_vrmod_weppouch_visiblename_left = "名前を表示（左）",

-- ============================================================
-- Physics Gun & Beam ConVars
-- ============================================================
cvar_vrmod_unoff_physgun_pickup_compat = "物理ガンピックアップ互換",
tip_vrmod_unoff_physgun_pickup_compat = "物理ガンピックアップの互換モードです。デフォルト: OFF",
cvar_vrmod_left_physgun_beam_enable = "左ビーム有効",
tip_vrmod_physgun_beam_enable = "この手の物理ビームを有効にします。",
cvar_vrmod_left_physgun_beam_range = "左ビーム範囲",
tip_vrmod_physgun_beam_range = "ビームが届く最大距離です。",
cvar_vrmod_left_physgun_beam_damage_enable = "左ビームダメージ",
tip_vrmod_physgun_beam_damage_enable = "エンティティへのビームダメージを有効にします。",
cvar_vrmod_left_physgun_beam_damage = "左ビームダメージ量",
tip_vrmod_physgun_beam_damage = "ビームからの1ティックあたりのダメージです。",
cvar_vrmod_left_physgun_pull_enable = "左プル有効",
tip_vrmod_physgun_pull_enable = "ビームでオブジェクトを引き寄せることを許可します。",
cvar_vrmod_left_physgun_noclip_enable = "左ノークリップ有効",
tip_vrmod_physgun_noclip_enable = "この手のビームでノークリップ移動を許可します。",
cvar_vrmod_left_physgun_beam_offset_x = "左ビームオフセット X",
tip_vrmod_physgun_beam_offset = "ビームが手から出る位置を微調整します。",
cvar_vrmod_left_physgun_beam_offset_y = "左ビームオフセット Y",
cvar_vrmod_left_physgun_beam_offset_z = "左ビームオフセット Z",
cvar_vrmod_right_physgun_beam_enable = "右ビーム有効",
cvar_vrmod_right_physgun_beam_range = "右ビーム範囲",
cvar_vrmod_right_physgun_beam_damage_enable = "右ビームダメージ",
cvar_vrmod_right_physgun_beam_damage = "右ビームダメージ量",
cvar_vrmod_right_physgun_pull_enable = "右プル有効",
cvar_vrmod_right_physgun_noclip_enable = "右ノークリップ有効",
cvar_vrmod_right_physgun_beam_offset_x = "右ビームオフセット X",
cvar_vrmod_right_physgun_beam_offset_y = "右ビームオフセット Y",
cvar_vrmod_right_physgun_beam_offset_z = "右ビームオフセット Z",
cvar_vrmod_pickup_beam_enable = "ピックアップアシスト有効",
tip_vrmod_pickup_beam_enable = "球体検知によるピックアップ補助を有効にします。デフォルト: ON",
cvar_vrmod_pickup_beam_cone_range = "ピックアップアシスト範囲",
tip_vrmod_pickup_beam_cone_range = "手の周囲の検知球体半径（units）。デフォルト: 25",
cvar_vrmod_pickup_beam_retry_max = "ピックアップアシスト最大リトライ",
tip_vrmod_pickup_beam_retry_max = "ピックアップアシストの最大リトライ回数（ticks）。デフォルト: 10",
cvar_vrmod_pickup_beam_damage_enable = "ラグドールビームダメージ",
tip_vrmod_pickup_beam_damage_enable = "ピックアップビームからのダメージを有効にします。",
cvar_vrmod_pickup_beam_damage = "ビームダメージ量",
tip_vrmod_pickup_beam_damage = "ピックアップビームが与えるダメージです。",

-- ============================================================
-- Climbing ConVars
-- ============================================================
cvar_vrmod_brushclimb_enable = "クライミングを有効にする",
tip_vrmod_brushclimb_enable = "VRクライミングシステムを有効にします。表面をつかんで引き上がれます。デフォルト: ON",
cvar_vrmod_brushclimb_bind_mode = "グラブモード",
tip_vrmod_brushclimb_bind_mode = "つかみ方の設定: ボタン長押し、またはトグル切替。",
cvar_vrmod_brushclimb_grab_distance = "グラブ距離",
tip_vrmod_brushclimb_grab_distance = "表面をつかむために手が届く距離です。デフォルト: 22",
cvar_vrmod_brushclimb_launch_mult = "射出倍率",
tip_vrmod_brushclimb_launch_mult = "クライミングを離したときのブースト量です。デフォルト: 1.35",
cvar_vrmod_brushclimb_launch_min = "射出最低速度",
tip_vrmod_brushclimb_launch_min = "離したときの最低射出速度です。デフォルト: 120",
cvar_vrmod_brushclimb_launch_max = "射出最高速度",
tip_vrmod_brushclimb_launch_max = "射出速度の上限です。デフォルト: 650",
cvar_vrmod_brushclimb_sounds = "クライミング音",
tip_vrmod_brushclimb_sounds = "クライミング中に効果音を再生します。デフォルト: ON",
cvar_vrmod_brushclimb_sound_volume = "サウンド音量",
tip_vrmod_brushclimb_sound_volume = "クライミング効果音の音量です。デフォルト: 0.8",
cvar_vrmod_brushclimb_camera_collision = "カメラ衝突",
tip_vrmod_brushclimb_camera_collision = "クライミング中にカメラが壁を通り抜けるのを防ぎます。",
cvar_vrmod_brushclimb_allow_walls = "壁を登る",
tip_vrmod_brushclimb_allow_surface = "この表面タイプでのクライミングを許可します。",
cvar_vrmod_brushclimb_allow_ceilings = "天井を登る",
cvar_vrmod_brushclimb_allow_ledges = "出っ張りを登る",
cvar_vrmod_brushclimb_allow_floors = "床を登る",
cvar_vrmod_brushclimb_allow_doors = "ドアを登る",
cvar_vrmod_brushclimb_allow_pushable = "押せるオブジェクトを登る",
cvar_vrmod_brushclimb_allow_toggleable = "切替可能オブジェクトを登る",
cvar_vrmod_brushclimb_allow_ladders = "はしごを登る",
cvar_vrmod_brushclimb_hand_inset = "手の内側オフセット",
tip_vrmod_brushclimb_palm = "上級者向けの手のひら/手の位置調整オフセットです。",
cvar_vrmod_brushclimb_wall_push_dist = "壁押し距離",
cvar_vrmod_brushclimb_palm_fwd = "手のひらオフセット 前方（左）",
cvar_vrmod_brushclimb_palm_right = "手のひらオフセット 右（左）",
cvar_vrmod_brushclimb_palm_up = "手のひらオフセット 上（左）",
cvar_vrmod_brushclimb_palm_fwd_r = "手のひらオフセット 前方（右）",
cvar_vrmod_brushclimb_palm_right_r = "手のひらオフセット 右（右）",
cvar_vrmod_brushclimb_palm_up_r = "手のひらオフセット 上（右）",
opt_bind_mode_0 = "長押しでつかむ",
opt_bind_mode_1 = "トグル",

-- Wallrun
cvar_vrmod_wallrun_hand_range = "ウォールラン手の範囲",
tip_vrmod_wallrun_hand_range = "ウォールランするために手を壁にどれだけ近づける必要があるかです。",
cvar_vrmod_wallrun_bind_mode = "ウォールランバインドモード",
tip_vrmod_wallrun_bind_mode = "ウォールランの起動方法: 長押しまたはトグル。",
cvar_vrmod_wallrun_cooldown = "ウォールランクールダウン",
tip_vrmod_wallrun_cooldown = "ウォールラン間の待ち時間です。デフォルト: 0.5",
cvar_vrmod_wallrun_air_regen = "空中回復時間",
tip_vrmod_wallrun_air_regen = "空中でウォールラン能力が回復する速さです。",
cvar_vrmod_wallrun_look_max_dot = "視線角度制限",
tip_vrmod_wallrun_look_max_dot = "ウォールラン中に壁から目をそらせる最大角度です。",
cvar_vrmod_wallrun_sounds = "ウォールラン音",
tip_vrmod_wallrun_sounds = "ウォールラン中に足音を再生します。",
cvar_vrmod_wallrun_sound_volume = "ウォールラン音量",
tip_vrmod_wallrun_sound_volume = "ウォールラン効果音の音量です。",
cvar_vrmod_wallrun_sound_interval = "サウンド間隔",
tip_vrmod_wallrun_sound_interval = "足音の再生間隔です。",

-- Slide
cvar_vrmod_slide_enable = "スライディングを有効にする",
tip_vrmod_slide_enable = "高速移動中にしゃがむことでスライディングを有効にします。",
cvar_vrmod_slide_head_height = "スライディング頭部高さ",
tip_vrmod_slide_head_height = "スライディングが発動する頭の低さです。",
cvar_vrmod_slide_sounds = "スライディング音",
tip_vrmod_slide_sounds = "スライディング中に効果音を再生します。",
cvar_vrmod_slide_sound_volume = "スライディング音量",
tip_vrmod_slide_sound_volume = "スライディング効果音の音量です。",

-- Climbing server
cvar_sv_vrmod_brushclimb_reduce_collider = "コライダー縮小",
tip_sv_vrmod_climbing = "サーバーのクライミング設定です。ホストのみ変更可能です。",
cvar_sv_vrmod_brushclimb_allow_walls = "壁を許可（サーバー）",
cvar_sv_vrmod_brushclimb_allow_ceilings = "天井を許可（サーバー）",
cvar_sv_vrmod_brushclimb_allow_ledges = "出っ張りを許可（サーバー）",
cvar_sv_vrmod_brushclimb_allow_floors = "床を許可（サーバー）",
cvar_sv_vrmod_brushclimb_allow_doors = "ドアを許可（サーバー）",
cvar_sv_vrmod_brushclimb_allow_pushable = "押せるオブジェクトを許可（サーバー）",
cvar_sv_vrmod_brushclimb_allow_toggleable = "切替可能を許可（サーバー）",
cvar_sv_vrmod_brushclimb_ledge_normal_min = "出っ張り法線最小値",
tip_sv_vrmod_climbing_normals = "クライミング検出の表面角度しきい値です。",
cvar_sv_vrmod_brushclimb_floor_normal_min = "床法線最小値",
cvar_sv_vrmod_brushclimb_ceil_normal_max = "天井法線最大値",

-- Wallrun server
cvar_sv_vrmod_wallrun_jump_force = "ジャンプ力",
tip_sv_vrmod_wallrun = "サーバーのウォールラン設定です。ホストのみ変更可能です。",
cvar_sv_vrmod_wallrun_wall_force = "壁の力",
cvar_sv_vrmod_wallrun_free_time = "フリータイム",
cvar_sv_vrmod_wallrun_fall_rate = "落下速度",
cvar_sv_vrmod_wallrun_max_fall_speed = "最大落下速度",
cvar_sv_vrmod_wallrun_speed_grace = "速度猶予",
cvar_sv_vrmod_wallrun_min_jump_time = "最小ジャンプ時間",

-- Slide server
cvar_sv_vrmod_slide_enable = "スライディングを有効にする（サーバー）",
tip_sv_vrmod_slide = "サーバーのスライディング設定です。ホストのみ変更可能です。",
cvar_sv_vrmod_slide_min_speed = "最低速度",
cvar_sv_vrmod_slide_friction = "摩擦",
cvar_sv_vrmod_slide_air_boost = "空中ブースト",
cvar_sv_vrmod_slide_stop_speed = "停止速度",
cvar_sv_vrmod_slide_entry_boost = "開始ブースト",

-- Debug
cvar_vrmod_brushclimb_debug = "クライミングデバッグ",
tip_vrmod_brushclimb_debug = "クライミングのデバッグ表示を有効にします。",
cvar_vrmod_brushclimb_debug_text = "デバッグテキスト",
tip_vrmod_brushclimb_debug_text = "クライミングのデバッグテキストオーバーレイを表示します。",

-- ============================================================
-- Vehicles
-- ============================================================
cvar_vrmod_lvs_input_mode = "LVS入力モード",
tip_vrmod_lvs_input_mode = "LVS車両のVR入力を有効にします。デフォルト: ON",
opt_lvs_mode_0 = "無効",
opt_lvs_mode_1 = "有効",
cvar_vrmod_sight_bodypart = "サイト用ボディパーツ",
tip_vrmod_sight_bodypart = "照準サイトに使用するボディパーツです。",
cvar_vrmod_pmchange = "プレイヤーモデル変更の処理",
tip_vrmod_pmchange = "VRでのプレイヤーモデル変更を処理します。",
cvar_vrmod_auto_seat_reset = "自動シートリセット",
tip_vrmod_auto_seat_reset = "車両のシートから降りたときに自動的に位置をリセットします。",

-- ============================================================
-- Network
-- ============================================================
cvar_vrmod_net_delay = "ネットワーク遅延",
tip_vrmod_net_delay = "ネットワーク更新の最小遅延です。低いほどスムーズですが帯域を消費します。デフォルト: 0.1",
cvar_vrmod_net_delaymax = "最大ネットワーク遅延",
tip_vrmod_net_delaymax = "遅延の上限値です。デフォルト: 0.2",
cvar_vrmod_net_storedframes = "保存フレーム数",
tip_vrmod_net_storedframes = "補間用に保存する位置フレーム数です。デフォルト: 15",
cvar_vrmod_net_tickrate = "ティックレート",
tip_vrmod_net_tickrate = "VRネットワーキングのティックレートです。高いほどスムーズですがCPU負荷が増えます。デフォルト: 67",
cvar_vrmod_allow_teleport = "テレポートを許可（サーバー）",
tip_vrmod_allow_teleport = "サーバーがプレイヤーにテレポート移動を許可します。デフォルト: ON",

-- ============================================================
-- Optimization
-- ============================================================
cvar_vrmod_scr_alwaysautosetting = "画面自動設定",
tip_vrmod_scr_alwaysautosetting = "最適な画面解像度設定を自動で適用します。デフォルト: ON",
cvar_vrmod_gmod_optimization_auto = "Gmod自動最適化",
tip_vrmod_gmod_optimization_auto = "Gmodのパフォーマンス最適化を自動で適用します。デフォルト: ON",
cvar_vrmod_auto_arc_benchgun = "ARC9自動ベンチガン",
tip_vrmod_auto_arc_benchgun = "VR用のARC9武器設定を自動で構成します。デフォルト: ON",
cvar_vrmod_auto_lvs_keysetings = "LVS自動キー設定",
tip_vrmod_auto_lvs_keysetings = "LVS車両のキーバインドを自動で構成します。デフォルト: ON",

-- ============================================================
-- Developer
-- ============================================================
cvar_vrmod_unoff_developer_mode = "開発者モード",
tip_vrmod_unoff_developer_mode = "開発者向け機能と追加ログを有効にします。デフォルト: OFF",
cvar_vrmod_error_hard = "ハードエラーモード",
tip_vrmod_error_hard = "ソフト警告の代わりにハードエラーをスローします。デバッグ用。デフォルト: OFF",
cvar_vrmod_test_Righthandle = "右ハンドルテスト",
tip_vrmod_test_handle = "デバッグ用のテストハンドル表示を有効にします。",
cvar_vrmod_test_lefthandle = "左ハンドルテスト",
cvar_vrmod_emergencystop_key = "緊急停止キー",
tip_vrmod_emergencystop_key = "VRを緊急終了するためのキーボードキーIDです。デフォルト: KEY_F3 (114)",
cvar_vrmod_emergencystop_time = "緊急停止の長押し時間",
tip_vrmod_emergencystop_time = "VRが停止するまでキーを押し続ける時間です。デフォルト: 3.0秒",
cvar_vrmod_keyguide_mode = "キーガイドモード",
tip_vrmod_keyguide_mode = "キーガイドHUDの表示モードです。0=オフ、1〜3=異なるスタイル。",
cvar_vrmod_keyguide_scale = "キーガイドスケール",
tip_vrmod_keyguide_scale = "キーガイドオーバーレイの大きさです。",
cvar_vrmod_keyguide_opacity = "キーガイド不透明度",
tip_vrmod_keyguide_opacity = "キーガイドオーバーレイの透明度です。",

-- ============================================================
-- Commands
-- ============================================================
cmd_vrmod = "VRModメニューを開く",
tip_cmd_vrmod = "メインのVRMod設定メニューを開きます。",
cmd_vrmod_guide = "初心者ガイドを開く",
tip_cmd_vrmod_guide = "この初心者向けガイドウィンドウを開きます。",
cmd_vrmod_lua_reload_all = "全Luaをリロード",
tip_cmd_vrmod_lua_reload_all = "すべてのVRMod Luaスクリプトをリロードします。変更を加えた後に使用してください。",
cmd_vrmod_keyboard = "VRキーボードを開く",
tip_cmd_vrmod_keyboard = "VR内でバーチャルキーボードを開きます。",
cmd_vrmod_actioneditor = "アクションエディタを開く",
tip_cmd_vrmod_actioneditor = "SteamVRのアクションバインディングエディタを開きます。",
cmd_vrmod_preset_save_current = "プリセットを保存",
tip_cmd_preset = "VRMod設定のプリセットを保存/読み込み/削除します。",
cmd_vrmod_preset_load_preset = "プリセットを読み込む",
cmd_vrmod_preset_delete_preset = "プリセットを削除",
cmd_vrmod_apply_optimization = "最適化を適用",
tip_cmd_vrmod_apply_optimization = "パフォーマンス最適化を今すぐ適用します。",
cmd_vrmod_optimization_reset = "最適化をリセット",
tip_cmd_vrmod_optimization_reset = "最適化をGmodのデフォルトに戻します。",
cmd_vrmod_apply_autosettings = "自動設定を適用",
tip_cmd_vrmod_apply_autosettings = "VR自動設定を適用します。",
cmd_vrmod_lua_reset_holster_system = "ホルスターシステムをリセット",
tip_cmd_reset_holster = "ホルスターシステムをリセットして不具合を修正します。",
cmd_vrmod_lua_reset_lefthand_holster = "左手ホルスターをリセット",
cmd_vrmod_unoff_debug_status = "デバッグステータス",
tip_cmd_debug = "デバッグ情報をコンソールに表示します。",
cmd_vrmod_unoff_debug_panel = "デバッグパネル",
cmd_vrmod_unoff_debug_hooks_list = "全フックを一覧表示",
cmd_vrmod_unoff_debug_record_start = "記録開始",
tip_cmd_debug_record = "デバッグ用にVRトラッキングデータを記録します。",
cmd_vrmod_unoff_debug_record_stop = "記録停止",
cmd_vrmod_unoff_debug_export = "デバッグデータをエクスポート",
tip_cmd_debug_export = "記録したデバッグデータをファイルにエクスポートします。",
cmd_vrmod_unoff_mock_start = "モックVRを開始",
tip_cmd_mock = "ヘッドセットなしでテストするためのモックVRモードを開始/停止します。",
cmd_vrmod_unoff_mock_stop = "モックVRを停止",
cmd_vrmod_unoff_mock_status = "モックVRステータス",
cmd_vrmod_print_devices = "VRデバイスを表示",
tip_cmd_print_devices = "接続されているすべてのVRデバイスとトラッカーを一覧表示します。",
cmd_vrmod_net_debug = "ネットワークデバッグ",
tip_cmd_net_debug = "ネットワークデバッグ出力を切り替えます。",
cmd_vrmod_doordebug = "ドアデバッグ",
tip_cmd_doordebug = "ドアインタラクションのデバッグ情報を切り替えます。",
cmd_vrmod_debuglocomotion = "移動デバッグ",
tip_cmd_debuglocomotion = "移動デバッグ情報を切り替えます。",
cmd_cardboardmod_start = "カードボードVRを開始",
tip_cmd_cardboard = "Google CardboardのVRモードを開始/停止します。",
cmd_cardboardmod_exit = "カードボードVRを終了",
cmd_vrmod_setlang = "言語を設定 (EN)",
tip_cmd_setlang = "VRModメインメニューの言語を変更します。",
}

print("[VRMod] Beginner Guide JA language loaded")
