-- VRMod Beginner Guide - Russian Language Strings
-- Русские строки

AddCSLuaFile()
if SERVER then return end

VRMOD_GUIDE_LANG = VRMOD_GUIDE_LANG or {}
VRMOD_GUIDE_LANG.ru = {

-- ============================================================
-- UI Chrome
-- ============================================================
window_title = "VRMod: Руководство для начинающих",
search_placeholder = "Поиск настроек... (имя ConVar или описание)",
lang_label = "Язык:",
btn_reset_category = "Сбросить эту категорию",
btn_reset_all = "Сбросить ВСЕ настройки",
btn_open_main_menu = "Открыть главное меню VRMod",
btn_open_guide = "Открыть руководство",
btn_yes = "Да",
btn_no = "Нет",
confirm_title = "Подтвердите сброс",
confirm_reset_all = "Вы уверены, что хотите сбросить ВСЕ настройки до значений по умолчанию?",
confirm_reset_category = "Сбросить все настройки этой категории до значений по умолчанию?",
help_prefix = "Что это?",
search_results = "Результаты поиска",
no_results = "Настройки, соответствующие вашему запросу, не найдены.",
too_many_results = "Показаны первые 100 результатов. Уточните поисковый запрос.",
results_found = "результат(ов) найдено",
status_settings = "настроек",
status_lang_en = "Английский",
status_lang_ja = "Японский",
status_lang_ru = "Русский",
status_lang_zh = "Китайский",
tip_reset_to = "Сбросить до значения по умолчанию",
tip_server_setting = "Это серверная настройка. Изменить её может только хост сервера.",
guide_tab_desc = "Удобное руководство по настройкам с\nмногоязычными описаниями всех функций VRMod.\n\nПоддерживаемые языки: английский, японский, русский, китайский",

-- ============================================================
-- Welcome / Getting Started
-- ============================================================
welcome_title = "Добро пожаловать в VRMod!",
welcome_desc = "Это руководство поможет вам настроить все параметры VRMod с понятными описаниями.\nВыберите категорию в левой панели, чтобы начать.\n\nВсе изменения вступают в силу мгновенно — нажимать «Применить» не нужно!",
quickstart_title = "Быстрый старт",
tip_body = "1. Перейдите в «Тело и масштаб», чтобы настроить рост VR-персонажа под ваш реальный рост",
tip_gameplay = "2. Загляните в «Геймплей» — там базовые настройки: телепорт, прыжок и другие",
tip_hud = "3. Настройте «HUD и интерфейс», чтобы расположить элементы управления удобно",
tip_reset = "4. У каждой настройки есть кнопка сброса к значению по умолчанию",
tip_search = "5. Используйте строку поиска вверху, чтобы быстро найти нужную настройку",
vr_status_title = "Статус VR",
vr_status_active = "VR АКТИВЕН",
vr_status_inactive = "VR НЕ активен. Запустите VR из главного меню VRMod (консоль: vrmod)",

-- ============================================================
-- Category Names
-- ============================================================
cat_getting_started = "Начало работы",
cat_body_scale = "Тело и масштаб",
cat_gameplay = "Геймплей",
cat_movement = "Передвижение",
cat_hud_ui = "HUD и интерфейс",
cat_quickmenu = "Быстрое меню",
cat_melee = "Ближний бой VR",
cat_weapons = "Оружие",
cat_holster = "Кобура",
cat_physgun = "Физ-пушка",
cat_climbing = "Карабканье",
cat_vehicles = "Транспорт",
cat_network = "Сеть",
cat_optimization = "Производительность",
cat_developer = "Разработчик",
cat_commands = "Команды",

-- ============================================================
-- Category Help Texts
-- ============================================================
help_body_scale = "Настройте VR-тело под ваш реальный рост и пропорции. Если персонаж кажется слишком высоким или низким — начните здесь. «Масштаб» и «Высота глаз» — самые важные параметры.",
help_gameplay = "Основные игровые настройки: прыжок, телепорт, фонарик и поведение подбора предметов.",
help_movement = "Управление перемещением в VR — прямое движение, шаговая локомоция и позиционирование модели оружия.",
help_hud_ui = "Настройка интерфейса (HUD), расположения UI-панелей и привязки меню к рукам в VR.",
help_quickmenu = "Выбирайте, какие элементы появятся в быстром VR-меню, открываемом кнопкой контроллера.",
help_melee = "Система ближнего боя в VR — удары кулаком, ногой и прикладом с отслеживанием движения рук. Настройка урона, хитбоксов и обратной связи.",
help_weapons = "Функции обращения с оружием — передний хват (двуручное прицеливание) и система магазинных костей для реалистичной перезарядки.",
help_holster = "Система кобуры — храните и доставайте оружие из карманов, прикреплённых к телу. Тип 2 (простые карманы) рекомендуется для новичков.",
help_physgun = "Настройки луча физ-пушки для левой и правой руки. Управление дальностью, уроном и смещением луча.",
help_climbing = "Система карабканья в VR — хватайтесь за стены, выступы и поверхности, чтобы забираться наверх. Включает бег по стенам и скольжение.",
help_vehicles = "Настройки, связанные с транспортом: режим управления LVS и поведение сиденья.",
help_network = "Сетевые серверные настройки — задержка синхронизации, тикрейт и хранилище кадров. Влияют на плавность мультиплеера.",
help_optimization = "Настройки и команды оптимизации производительности. Используйте их для повышения FPS при лагах.",
help_developer = "Инструменты разработчика, отладочные команды и настройка аварийной остановки. Для опытных пользователей и устранения неполадок.",
help_commands = "Все доступные консольные команды в виде кнопок. Не нужно вводить в консоль вручную!",

-- ============================================================
-- Section Headers
-- ============================================================
section_basic_body = "Основные настройки тела",
section_seated_mode = "Сидячий режим",
section_handedness = "Ведущая рука (левая/правая)",
section_character_advanced = "Расширенные настройки персонажа",
section_animations = "Переопределение анимаций",
section_pickup_server = "Настройки подбора (сервер)",
section_viewmodel = "Привязка модели оружия",
section_render_tweaks = "Настройки рендеринга",
section_hud = "Отображение HUD",
section_ui_panels = "Поведение UI-панелей",
section_attachment_points = "Точки привязки меню",
section_quickmenu_items = "Элементы быстрого меню",
section_melee_enable = "Переключатели ближнего боя (клиент)",
section_melee_server = "Переключатели ближнего боя (сервер)",
section_melee_damage = "Настройки урона (сервер)",
section_melee_client = "Клиентские настройки ближнего боя",
section_melee_fist = "Настройки кулаков",
section_melee_blocking = "Эмуляция блокировки",
section_melee_commands = "Пользовательские команды удара",
section_foregrip = "Передний хват (двуручное прицеливание)",
section_foregrip_advanced = "Тонкая настройка переднего хвата",
section_magazine = "Позиция кости магазина",
section_holster_type2 = "Кобура Тип 2 (простые карманы)",
section_pouch_slots = "Слоты карманов 1-5 (правая рука)",
section_pouch_left_hand = "Слоты карманов 6-8 (левая рука)",
section_holster_type1_right = "Кобура Тип 1 — правая рука",
section_holster_type1_left = "Кобура Тип 1 — левая рука",
section_physgun_general = "Общие",
section_physgun_left = "Луч левой руки",
section_physgun_right = "Луч правой руки",
section_beam_pickup = "Подбор лучом",
section_climbing_basic = "Основы карабканья",
section_climbing_surfaces = "Доступные поверхности",
section_climbing_palm = "Смещение ладони (продвинутое)",
section_wallrun = "Бег по стенам",
section_slide = "Скольжение",
section_climbing_server = "Серверные настройки карабканья",
section_wallrun_server = "Серверные настройки бега по стенам",
section_slide_server = "Серверные настройки скольжения",
section_climbing_debug = "Отладка карабканья",
section_auto_settings = "Автоматические настройки",
section_optimization_commands = "Команды оптимизации",
section_dev_general = "Параметры разработчика",
section_emergency_stop = "Аварийная остановка VR",
section_keyguide = "HUD подсказок клавиш",
section_debug_commands = "Отладочные команды",
section_cmd_general = "Общие команды",
section_cmd_presets = "Управление пресетами",
section_cmd_optimization = "Оптимизация",
section_cmd_holster = "Сброс кобуры",
section_cmd_debug = "Инструменты отладки",
section_cmd_mock = "Эмуляция VR (тестирование)",
section_cmd_misc = "Разное",

-- ============================================================
-- Body & Scale ConVars
-- ============================================================
cvar_vrmod_scale = "Масштаб персонажа",
tip_vrmod_scale = "Общий размер вашей VR-модели персонажа. По умолчанию: 38.7. Измените, если ощущаете себя слишком высоким или низким в игре.",
cvar_vrmod_characterEyeHeight = "Высота глаз",
tip_vrmod_characterEyeHeight = "Высота глаз персонажа от земли. Должна соответствовать вашей реальной высоте глаз для естественного ощущения. По умолчанию: 66.8",
cvar_vrmod_characterHeadToHmdDist = "Расстояние голова–шлем",
tip_vrmod_characterHeadToHmdDist = "Расстояние от кости головы персонажа до вашего шлема. Влияет на совмещение модели головы. По умолчанию: 6.3",
cvar_vrmod_crouchthreshold = "Порог приседания",
tip_vrmod_crouchthreshold = "Насколько низко нужно физически присесть, чтобы игра считала вас присевшим. По умолчанию: 40",
cvar_vrmod_znear = "Ближняя плоскость отсечения",
tip_vrmod_znear = "Объекты ближе этого расстояния становятся невидимыми. Увеличьте, если видите внутренности головы. По умолчанию: 1.0",
cvar_vrmod_seated = "Включить сидячий режим",
tip_vrmod_seated = "Включите, если играете сидя. Добавляет смещение по высоте, чтобы персонаж стоял нормально.",
cvar_vrmod_seatedoffset = "Смещение высоты сидя",
tip_vrmod_seatedoffset = "Дополнительная высота в сидячем режиме. Настраивается через меню регулировки высоты.",
cvar_vrmod_LeftHand = "Режим левши",
tip_vrmod_LeftHand = "Меняет ведущую руку на левую. Левый контроллер становится основной (стреляющей) рукой.",
cvar_vrmod_lefthandleftfire = "Стрельба левой рукой",
tip_vrmod_lefthandleftfire = "В режиме левши левый триггер стреляет оружием.",
cvar_vrmod_LeftHandmode = "Стиль режима левши",
tip_vrmod_LeftHandmode = "Как работает смена рук. Обычный или Зеркальный режим.",
cvar_vrmod_oldcharacteryaw = "Старый поворот персонажа",
tip_vrmod_oldcharacteryaw = "Использовать старый метод поворота персонажа. Может исправить проблемы с некоторыми моделями.",
cvar_vrmod_animation_Enable = "Включить анимации",
tip_vrmod_animation_Enable = "Включить анимации тела персонажа (ходьба, стояние, бег). Отключите для повышения производительности.",
cvar_vrmod_hide_head = "Скрыть модель головы",
tip_vrmod_hide_head = "Скрывает модель головы персонажа, чтобы она не загораживала обзор.",
cvar_vrmod_hide_head_pos_x = "Смещение скрытия головы X",
tip_vrmod_hide_head_pos = "Тонкая настройка позиции скрытия головы. Измените, если всё ещё видны части головы.",
cvar_vrmod_hide_head_pos_y = "Смещение скрытия головы Y",
cvar_vrmod_hide_head_pos_z = "Смещение скрытия головы Z",
cvar_vrmod_idle_act = "Анимация стояния",
tip_vrmod_idle_act = "Имя анимации для состояния покоя. По умолчанию: ACT_HL2MP_IDLE",
cvar_vrmod_walk_act = "Анимация ходьбы",
tip_vrmod_walk_act = "Имя анимации для ходьбы. По умолчанию: ACT_HL2MP_WALK",
cvar_vrmod_run_act = "Анимация бега",
tip_vrmod_run_act = "Имя анимации для бега. По умолчанию: ACT_HL2MP_RUN",
cvar_vrmod_jump_act = "Анимация прыжка",
tip_vrmod_jump_act = "Имя анимации для прыжка. По умолчанию: ACT_HL2MP_JUMP_PASSIVE",

-- Dropdown options
opt_lefthandmode_0 = "Обычный",
opt_lefthandmode_1 = "Зеркальный",

-- ============================================================
-- Gameplay ConVars
-- ============================================================
cvar_vrmod_autojumpduck = "Автоприседание при прыжке",
tip_vrmod_autojumpduck = "ВКЛ: Кнопка прыжка отправляет присед+прыжок (для более высоких прыжков). ВЫКЛ: Только прыжок. По умолчанию: ВКЛ",
cvar_vrmod_allow_teleport_client = "Включить телепорт",
tip_vrmod_allow_teleport_client = "Разрешить телепортацию. Наведите и телепортируйтесь вместо ходьбы. По умолчанию: ВКЛ",
cvar_vrmod_flashlight_attachment = "Позиция фонарика",
tip_vrmod_flashlight_attachment = "Куда крепится фонарик. 0=Правая рука, 1=Левая рука, 2=Шлем",
cvar_vrmod_manualpickups = "Ручной подбор предметов",
tip_vrmod_manualpickups = "Включить ручную систему подбора Hugo для более реалистичного захвата предметов. По умолчанию: ВКЛ",
cvar_vrmod_pickup_weight = "Лимит веса подбора",
tip_vrmod_pickup_weight = "Максимальный вес объектов, которые можно поднять. Серверная настройка. По умолчанию: 100",
cvar_vrmod_pickup_range = "Дальность подбора",
tip_vrmod_pickup_range = "Как далеко вы можете дотянуться до объектов. Серверная настройка. По умолчанию: 1.1",
cvar_vrmod_pickup_limit = "Лимит подбора",
tip_vrmod_pickup_limit = "Максимальное количество удерживаемых объектов. Серверная настройка. По умолчанию: 1",

section_pickup_client = "Настройки подбора (Клиент)",
cvar_vrmod_unoff_pickup_weight_client = "Клиентский лимит веса",
tip_vrmod_unoff_pickup_weight_client = "Персональный максимальный вес подбора. 0 = отключено (только серверный лимит). При установке: эффективный лимит = min(сервер, клиент). По умолчанию: 0",
cvar_vrmod_unoff_pickup_limit_client = "Клиентский лимит подбора",
tip_vrmod_unoff_pickup_limit_client = "Уровень фильтра подбора. 0=отключено, 1=стандарт, 2=строгий, 3=отключить подбор. Используется max(сервер, клиент). По умолчанию: 0",
cvar_vrmod_unoff_rotate_held_enable = "Вращение удерживаемого объекта",
tip_vrmod_unoff_rotate_held_enable = "Удерживайте вторичный огонь для стабилизации объекта. Двигайте руку, удерживая кнопку, чтобы перехватить. 0 = оригинальная ориентация. По умолчанию: 1",
cvar_vrmod_unoff_rotate_held_speed = "Скорость вращения",
tip_vrmod_unoff_rotate_held_speed = "0 = стабилизация/перехват. 1 = обычное следование. >1 = усиленное вращение. По умолчанию: 0",

-- Dropdown options
opt_flashlight_right = "Правая рука",
opt_flashlight_left = "Левая рука",
opt_flashlight_hmd = "Шлем (HMD)",

-- ============================================================
-- Movement ConVars
-- ============================================================
cvar_vrmod_directMovement = "Прямое движение",
tip_vrmod_directMovement = "Двигаться в направлении, куда указывает рука/голова. По умолчанию: ВКЛ",
cvar_vrmod_locomotion_step = "Шаговая локомоция",
tip_vrmod_locomotion_step = "Включить пошаговое перемещение для уменьшения укачивания. По умолчанию: ВКЛ",
cvar_vrmod_noTrigger = "Без случайной ходьбы",
tip_vrmod_noTrigger = "Предотвращает случайное перемещение при нажатии триггеров. По умолчанию: ВКЛ",
cvar_vrmod_attach_viewmodel = "Привязать модель оружия",
tip_vrmod_attach_viewmodel = "Привязать модель оружия (viewmodel) к руке. По умолчанию: ВКЛ",
cvar_vrmod_viewmodel_normal_enable = "Обычная модель оружия",
tip_vrmod_viewmodel_normal_enable = "Показывать стандартные модели оружия. По умолчанию: ВКЛ",
cvar_vrmod_viewmodel_offset_x = "Смещение модели X",
tip_vrmod_viewmodel_offset = "Тонкая настройка позиции модели оружия относительно руки.",
cvar_vrmod_viewmodel_offset_y = "Смещение модели Y",
cvar_vrmod_viewmodel_offset_z = "Смещение модели Z",
cvar_vrmod_viewmodel_offset_ang_p = "Угол модели: тангаж",
tip_vrmod_viewmodel_offset_ang = "Тонкая настройка поворота модели оружия относительно руки.",
cvar_vrmod_viewmodel_offset_ang_y = "Угол модели: рыскание",
cvar_vrmod_viewmodel_offset_ang_r = "Угол модели: крен",
cvar_vrmod_rtWidth_Multiplier = "Множитель ширины RT",
tip_vrmod_rtWidth_Multiplier = "Множитель ширины рендер-цели. Больше = чётче, но медленнее. По умолчанию: 2.0",
cvar_vrmod_rtHeight_Multiplier = "Множитель высоты RT",
tip_vrmod_rtHeight_Multiplier = "Множитель высоты рендер-цели. Больше = чётче, но медленнее. По умолчанию: 1.0",
cvar_vrmod_error_check_method = "Метод проверки ошибок",
tip_vrmod_error_check_method = "Способ обнаружения и обработки ошибок. 0=отключено, 1=стандартный. По умолчанию: 1",

-- ============================================================
-- HUD & UI ConVars
-- ============================================================
cvar_vrmod_hud = "Включить HUD",
tip_vrmod_hud = "Показывать интерфейс (HUD) в VR. По умолчанию: ВКЛ",
cvar_vrmod_hudcurve = "Изгиб HUD",
tip_vrmod_hudcurve = "Степень изгиба HUD. 0=плоский, 180=полный изгиб. По умолчанию: 60",
cvar_vrmod_huddistance = "Расстояние до HUD",
tip_vrmod_huddistance = "Как далеко HUD от вашего лица. По умолчанию: 60",
cvar_vrmod_hudscale = "Масштаб HUD",
tip_vrmod_hudscale = "Размер отображения HUD. По умолчанию: 0.05",
cvar_vrmod_hudtestalpha = "Тестовая прозрачность HUD",
tip_vrmod_hudtestalpha = "Прозрачность HUD для тестирования. 0=невидимый, 255=полностью непрозрачный. По умолчанию: 0",
cvar_vre_ui_attachtohand = "Привязать UI к руке",
tip_vre_ui_attachtohand = "Привязать UI-панели к руке вместо свободного парения. По умолчанию: ВКЛ",
cvar_vrmod_ui_outline = "Обводка UI",
tip_vrmod_ui_outline = "Рисовать обводку вокруг UI-панелей для лучшей видимости. По умолчанию: ВКЛ",
cvar_vrmod_ui_realtime = "Обновление UI в реальном времени",
tip_vrmod_ui_realtime = "Обновлять UI-панели в реальном времени. Отключите для производительности. По умолчанию: ВЫКЛ",
cvar_vrmod_cameraoverride = "Переопределение камеры",
tip_vrmod_cameraoverride = "Переопределить камеру для VR-рендеринга. По умолчанию: ВКЛ",
cvar_vrmod_keyboard_uichatkey = "Клавиша чата для UI",
tip_vrmod_keyboard_uichatkey = "Использовать клавишу чата для открытия VR-клавиатуры. По умолчанию: ВКЛ",
cvar_vrmod_hud_visible_quickmenukey = "Индикатор быстрого меню на HUD",
tip_vrmod_hud_visible_quickmenukey = "Показывать индикатор клавиши быстрого меню на HUD. По умолчанию: ВЫКЛ",
cvar_vrmod_attach_quickmenu = "Позиция быстрого меню",
tip_vrmod_attach_quickmenu = "Точка привязки быстрого меню к руке (1-4). По умолчанию: 4",
cvar_vrmod_attach_weaponmenu = "Позиция меню оружия",
tip_vrmod_attach_weaponmenu = "Точка привязки меню оружия к руке (1-4). По умолчанию: 3",
cvar_vrmod_attach_popup = "Позиция всплывающих окон",
tip_vrmod_attach_popup = "Точка привязки всплывающих окон к руке (1-4). По умолчанию: 4",

-- Dropdown options
opt_attach_1 = "Позиция 1",
opt_attach_2 = "Позиция 2",
opt_attach_3 = "Позиция 3",
opt_attach_4 = "Позиция 4",

-- ============================================================
-- Quick Menu ConVars
-- ============================================================
cvar_vrmod_quickmenu_use_custom = "Своё быстрое меню",
tip_vrmod_quickmenu_use_custom = "Использовать собственную раскладку быстрого меню вместо стандартной. По умолчанию: ВЫКЛ",
cvar_vrmod_quickmenu_mapbrowser_enable = "Браузер карт",
tip_vrmod_quickmenu_item = "Показать/скрыть этот элемент в VR быстром меню.",
cvar_vrmod_quickmenu_exit = "Выход из VR",
cvar_vrmod_quickmenu_vgui_reset_menu = "Меню сброса VGUI",
cvar_vrmod_quickmenu_vre_gbradial_menu = "Радиальное меню",
cvar_vrmod_quickmenu_chat = "Чат",
cvar_vrmod_quickmenu_seated_menu = "Сидячий режим",
cvar_vrmod_quickmenu_togglemirror = "Переключить зеркало",
cvar_vrmod_quickmenu_togglevehiclemode = "Переключить режим транспорта",
cvar_vrmod_quickmenu_noclip = "Ноуклип",
cvar_vrmod_quickmenu_spawnmenu = "Меню спауна",
cvar_vrmod_quickmenu_contextmenu = "Контекстное меню",
cvar_vrmod_quickmenu_arccw = "Настройка ArcCW",

-- ============================================================
-- Melee ConVars
-- ============================================================
cvar_vrmelee_usegunmelee = "Удар оружием (клиент)",
tip_vrmelee_usegunmelee = "Включить удары оружием как холодным (предпочтение клиента).",
cvar_vrmelee_usefist = "Кулаки (клиент)",
tip_vrmelee_usefist = "Включить удары кулаками (предпочтение клиента).",
cvar_vrmelee_usekick = "Удары ногами (клиент)",
tip_vrmelee_usekick = "Включить удары ногами с использованием трекеров ног (предпочтение клиента). По умолчанию: ВЫКЛ",
cvar_vrmelee_gunmelee = "Разрешить удар оружием (сервер)",
tip_vrmelee_gunmelee = "Сервер разрешает удары прикладом. По умолчанию: ВКЛ",
cvar_vrmelee_fist = "Разрешить кулаки (сервер)",
tip_vrmelee_fist = "Сервер разрешает удары кулаками. По умолчанию: ВКЛ",
cvar_vrmelee_kick = "Разрешить удары ногами (сервер)",
tip_vrmelee_kick = "Сервер разрешает удары ногами. По умолчанию: ВКЛ",
cvar_vrmelee_damage_low = "Слабый урон",
tip_vrmelee_damage = "Урон при данном уровне скорости. Серверная настройка.",
cvar_vrmelee_damage_medium = "Средний урон",
cvar_vrmelee_damage_high = "Сильный урон",
cvar_vrmelee_damage_velocity_low = "Порог низкой скорости",
tip_vrmelee_velocity = "Скорость руки, необходимая для активации данного уровня урона.",
cvar_vrmelee_damage_velocity_medium = "Порог средней скорости",
cvar_vrmelee_damage_velocity_high = "Порог высокой скорости",
cvar_vrmelee_impact = "Сила удара",
tip_vrmelee_impact = "Физическая сила отталкивания при попадании. По умолчанию: 5.0",
cvar_vrmelee_delay = "Задержка удара",
tip_vrmelee_delay = "Задержка перед регистрацией урона после контакта. По умолчанию: 0.0",
cvar_vrmelee_range = "Дальность удара",
tip_vrmelee_range = "Максимальная дистанция для ударов ближнего боя. По умолчанию: 22",
cvar_vrmelee_high_velocity_fire_bullets = "Режим пули на высокой скорости",
tip_vrmelee_high_velocity_fire_bullets = "При экстремальной скорости используется трассировка пули вместо ближнего боя. Экспериментальная функция.",
cvar_vrmelee_cooldown = "Время перезарядки",
tip_vrmelee_cooldown = "Минимальное время между ударами. По умолчанию: 0.2 секунды",
cvar_vrmelee_hitbox_width = "Ширина хитбокса",
tip_vrmelee_hitbox = "Размер невидимого хитбокса на вашей руке.",
cvar_vrmelee_hitbox_length = "Длина хитбокса",
cvar_vrmelee_hit_feedback = "Обратная связь при ударе",
tip_vrmelee_hit_feedback = "Визуальная/тактильная обратная связь при попадании. По умолчанию: ВКЛ",
cvar_vrmelee_hit_sound = "Звук удара",
tip_vrmelee_hit_sound = "Воспроизводить звуковой эффект при попадании. По умолчанию: ВКЛ",
cvar_vrmelee_fist_collision = "Модель столкновения кулака",
tip_vrmelee_fist_collision = "Показать видимую модель столкновения кулаков. Полезно для отладки.",
cvar_vrmelee_fist_visible = "Видимость кулака",
tip_vrmelee_fist_visible = "Сделать модель столкновения кулака видимой. По умолчанию: ВЫКЛ",
cvar_vrmelee_fist_collisionmodel = "Путь к модели кулака",
tip_vrmelee_fist_collisionmodel = "Файл модели, используемый для столкновения кулака.",
cvar_vrmelee_emulateblocking = "Эмуляция блокировки",
tip_vrmelee_emulateblocking = "Поднимите руки вверх для эмуляции блока (отправляет ввод attack2). По умолчанию: ВЫКЛ",
cvar_vrmelee_emulateblockbutton = "Кнопка блока (нажатие)",
tip_vrmelee_emulateblockbutton = "Консольная команда, отправляемая при входе в стойку блока.",
cvar_vrmelee_emulateblockbutton_release = "Кнопка блока (отпускание)",
tip_vrmelee_emulateblockbutton_release = "Консольная команда, отправляемая при выходе из стойки блока.",
cvar_vrmelee_emulateblock_threshold_low = "Угол блока (нижний)",
tip_vrmelee_emulateblock_threshold = "Диапазон углов руки, считающийся блокировкой.",
cvar_vrmelee_emulateblock_threshold_high = "Угол блока (верхний)",
cvar_vrmelee_lefthand_command = "Команда удара левой рукой",
tip_vrmelee_hand_command = "Пользовательская консольная команда, выполняемая при ударе этой рукой.",
cvar_vrmelee_righthand_command = "Команда удара правой рукой",
cvar_vrmelee_leftfoot_command = "Команда удара левой ногой",
tip_vrmelee_foot_command = "Пользовательская консольная команда, выполняемая при ударе этой ногой.",
cvar_vrmelee_rightfoot_command = "Команда удара правой ногой",
cvar_vrmelee_gunmelee_command = "Команда удара прикладом",
tip_vrmelee_gunmelee_command = "Пользовательская консольная команда, выполняемая при ударе прикладом.",

-- ============================================================
-- Weapons (Foregrip + Magazine)
-- ============================================================
cvar_vrmod_Foregripmode_enable = "Включить передний хват",
tip_vrmod_Foregripmode_enable = "Двуручное прицеливание оружия. Схватите переднюю часть оружия второй рукой. По умолчанию: ВКЛ",
cvar_vrmod_Foregripmode_range = "Дальность переднего хвата",
tip_vrmod_Foregripmode_range = "Как близко должна быть вторая рука для захвата. По умолчанию: 30",
cvar_vrmod_Foregripmode_key_leftprimary = "Захват основной кнопкой",
tip_vrmod_Foregripmode_key = "Какая кнопка активирует передний хват.",
cvar_vrmod_Foregripmode_key_leftgrab = "Захват кнопкой «схватить»",
cvar_vrmod_Foregripmode_rotation_blend = "Плавность поворота",
tip_vrmod_Foregripmode_rotation_blend = "Насколько плавно оружие поворачивается к второй руке. 1.0=мгновенно. По умолчанию: 1.0",
cvar_vrmod_Foregripmode_offset_x = "Смещение хвата X",
tip_vrmod_Foregripmode_offset = "Тонкая настройка позиции точки захвата.",
cvar_vrmod_Foregripmode_offset_y = "Смещение хвата Y",
cvar_vrmod_Foregripmode_offset_z = "Смещение хвата Z",
cvar_vrmod_Foregripmode_ang_pitch = "Угол хвата: тангаж",
tip_vrmod_Foregripmode_ang = "Тонкая настройка поворота точки захвата.",
cvar_vrmod_Foregripmode_ang_yaw = "Угол хвата: рыскание",
cvar_vrmod_Foregripmode_ang_roll = "Угол хвата: крен",
cvar_vrmod_mag_pos_x = "Позиция магазина X",
tip_vrmod_mag_pos = "Смещение позиции отсоединяемого магазина на оружии.",
cvar_vrmod_mag_pos_y = "Позиция магазина Y",
cvar_vrmod_mag_pos_z = "Позиция магазина Z",
cvar_vrmod_mag_ang_p = "Угол магазина: тангаж",
tip_vrmod_mag_ang = "Поворот отсоединяемого магазина.",
cvar_vrmod_mag_ang_y = "Угол магазина: рыскание",
cvar_vrmod_mag_ang_r = "Угол магазина: крен",
cvar_vrmod_mag_bones = "Названия костей магазина",
tip_vrmod_mag_bones = "Имена костей через запятую для обнаружения магазинов. По умолчанию: mag,ammo,clip,cylin,shell,magazine",

-- ============================================================
-- Holster ConVars
-- ============================================================
cvar_vrmod_pouch_enabled = "Включить систему карманов",
tip_vrmod_pouch_enabled = "Включить кобуру Типа 2 (простые карманы). По умолчанию: ВКЛ",
cvar_vrmod_pouch_visiblename = "Показывать названия карманов (3D)",
tip_vrmod_pouch_visiblename = "Отображать названия оружия над карманами в 3D-пространстве.",
cvar_vrmod_pouch_visiblename_hud = "Показывать названия карманов (HUD)",
tip_vrmod_pouch_visiblename_hud = "Отображать названия оружия на HUD.",
cvar_vrmod_pouch_lefthandwep_enable = "Карманы для левой руки",
tip_vrmod_pouch_lefthandwep_enable = "Включить отдельное оружие для левой руки в слотах 6-8.",
cvar_vrmod_pouch_pickup_sound = "Звук подбора",
tip_vrmod_pouch_pickup_sound = "Звуковой файл, воспроизводимый при подборе из кармана.",
cvar_pouch_slot_enabled_1 = "Слот 1 включён",
tip_pouch_slot = "Включить/отключить этот слот кобуры.",
cvar_pouch_weapon_1 = "Слот 1: оружие",
tip_pouch_weapon = "Класс оружия для этого слота (например, weapon_pistol). Оставьте пустым для любого.",
cvar_pouch_size_1 = "Слот 1: размер",
tip_pouch_size = "Радиус обнаружения этого слота кармана.",
cvar_pouch_slot_enabled_2 = "Слот 2 включён",
cvar_pouch_weapon_2 = "Слот 2: оружие",
cvar_pouch_size_2 = "Слот 2: размер",
cvar_pouch_slot_enabled_3 = "Слот 3 включён",
cvar_pouch_weapon_3 = "Слот 3: оружие",
cvar_pouch_size_3 = "Слот 3: размер",
cvar_pouch_slot_enabled_4 = "Слот 4 включён",
cvar_pouch_weapon_4 = "Слот 4: оружие",
cvar_pouch_size_4 = "Слот 4: размер",
cvar_pouch_slot_enabled_5 = "Слот 5 включён",
cvar_pouch_weapon_5 = "Слот 5: оружие",
cvar_pouch_size_5 = "Слот 5: размер",
cvar_pouch_slot_enabled_6 = "Слот 6 включён (лев.)",
cvar_pouch_weapon_6 = "Слот 6: оружие (прав.)",
cvar_pouch_weapon_6_left = "Слот 6: оружие (лев.)",
tip_pouch_weapon_left = "Оружие для левой руки в этом слоте.",
cvar_pouch_size_6 = "Слот 6: размер",
cvar_pouch_slot_enabled_7 = "Слот 7 включён (лев.)",
cvar_pouch_weapon_7 = "Слот 7: оружие (прав.)",
cvar_pouch_weapon_7_left = "Слот 7: оружие (лев.)",
cvar_pouch_size_7 = "Слот 7: размер",
cvar_pouch_slot_enabled_8 = "Слот 8 включён (лев.)",
cvar_pouch_weapon_8 = "Слот 8: оружие (прав.)",
cvar_pouch_weapon_8_left = "Слот 8: оружие (лев.)",
cvar_pouch_size_8 = "Слот 8: размер",
cvar_vrmod_unoff_dupe_reusable = "Система копирования конфигурации",
tip_vrmod_unoff_dupe_reusable = "Разрешить копирование настроек кобуры. По умолчанию: ВЫКЛ",

-- Holster Type 1
cvar_vrmod_weppouch_Pelvis = "Слот на тазу (прав.)",
tip_vrmod_weppouch_slot = "Включить этот слот кобуры на теле.",
cvar_vrmod_weppouch_weapon_Pelvis = "Оружие на тазу",
tip_vrmod_weppouch_weapon = "Класс оружия для этого слота.",
cvar_vrmod_weppouch_weapon_lock_Pelvis = "Закрепить оружие на тазу",
tip_vrmod_weppouch_lock = "Закрепить этот слот за конкретным оружием.",
cvar_vrmod_weppouch_dist_Pelvis = "Расстояние до таза",
tip_vrmod_weppouch_dist = "Расстояние обнаружения для этого слота кобуры.",
cvar_vrmod_weppouch_Head = "Слот на голове (прав.)",
cvar_vrmod_weppouch_weapon_Head = "Оружие на голове",
cvar_vrmod_weppouch_weapon_lock_Head = "Закрепить оружие на голове",
cvar_vrmod_weppouch_dist_head = "Расстояние до головы",
cvar_vrmod_weppouch_Spine = "Слот на спине (прав.)",
cvar_vrmod_weppouch_weapon_Spine = "Оружие на спине",
cvar_vrmod_weppouch_weapon_lock_Spine = "Закрепить оружие на спине",
cvar_vrmod_weppouch_dist_spine = "Расстояние до спины",
cvar_vrmod_weppouch_visiblerange = "Показать индикатор дальности",
tip_vrmod_weppouch_visiblerange = "Визуализировать радиус обнаружения кобуры.",
cvar_vrmod_weppouch_visiblename_t1 = "Показать названия (Тип 1)",
tip_vrmod_weppouch_visiblename = "Отображать названия оружия в позициях кобуры.",
cvar_vrmod_head_visible = "Видимость кости головы",
tip_vrmod_head_visible = "Показать маркер слота кобуры на голове.",

-- Type 1 Left
cvar_vrmod_weppouch_left_Pelvis = "Слот на тазу (лев.)",
cvar_vrmod_weppouch_weapon_left_Pelvis = "Оружие на тазу (лев.)",
cvar_vrmod_weppouch_weapon_lock_left_Pelvis = "Закрепить оружие на тазу (лев.)",
cvar_vrmod_weppouch_dist_Pelvis_left = "Расстояние до таза (лев.)",
cvar_vrmod_weppouch_left_Head = "Слот на голове (лев.)",
cvar_vrmod_weppouch_weapon_left_Head = "Оружие на голове (лев.)",
cvar_vrmod_weppouch_weapon_lock_left_Head = "Закрепить оружие на голове (лев.)",
cvar_vrmod_weppouch_dist_head_left = "Расстояние до головы (лев.)",
cvar_vrmod_weppouch_left_Spine = "Слот на спине (лев.)",
cvar_vrmod_weppouch_weapon_left_Spine = "Оружие на спине (лев.)",
cvar_vrmod_weppouch_weapon_lock_left_Spine = "Закрепить оружие на спине (лев.)",
cvar_vrmod_weppouch_dist_spine_left = "Расстояние до спины (лев.)",
cvar_vrmod_weppouch_visiblerange_left = "Показать дальность (лев.)",
cvar_vrmod_weppouch_visiblename_left = "Показать названия (лев.)",

-- ============================================================
-- Physics Gun & Beam ConVars
-- ============================================================
cvar_vrmod_unoff_physgun_pickup_compat = "Совместимость физ-пушки",
tip_vrmod_unoff_physgun_pickup_compat = "Режим совместимости подбора физ-пушкой. По умолчанию: ВЫКЛ",
cvar_vrmod_left_physgun_beam_enable = "Луч левой руки: вкл.",
tip_vrmod_physgun_beam_enable = "Включить физический луч для этой руки.",
cvar_vrmod_left_physgun_beam_range = "Луч левой руки: дальность",
tip_vrmod_physgun_beam_range = "Максимальная дальность действия луча.",
cvar_vrmod_left_physgun_beam_damage_enable = "Луч левой руки: урон вкл.",
tip_vrmod_physgun_beam_damage_enable = "Включить урон лучом по объектам.",
cvar_vrmod_left_physgun_beam_damage = "Луч левой руки: величина урона",
tip_vrmod_physgun_beam_damage = "Урон за тик от луча.",
cvar_vrmod_left_physgun_pull_enable = "Левая рука: притягивание вкл.",
tip_vrmod_physgun_pull_enable = "Разрешить притягивание объектов лучом.",
cvar_vrmod_left_physgun_noclip_enable = "Левая рука: ноуклип вкл.",
tip_vrmod_physgun_noclip_enable = "Разрешить свободный полёт (noclip) лучом этой руки.",
cvar_vrmod_left_physgun_beam_offset_x = "Луч левой руки: смещение X",
tip_vrmod_physgun_beam_offset = "Тонкая настройка точки выхода луча из руки.",
cvar_vrmod_left_physgun_beam_offset_y = "Луч левой руки: смещение Y",
cvar_vrmod_left_physgun_beam_offset_z = "Луч левой руки: смещение Z",
cvar_vrmod_right_physgun_beam_enable = "Луч правой руки: вкл.",
cvar_vrmod_right_physgun_beam_range = "Луч правой руки: дальность",
cvar_vrmod_right_physgun_beam_damage_enable = "Луч правой руки: урон вкл.",
cvar_vrmod_right_physgun_beam_damage = "Луч правой руки: величина урона",
cvar_vrmod_right_physgun_pull_enable = "Правая рука: притягивание вкл.",
cvar_vrmod_right_physgun_noclip_enable = "Правая рука: ноуклип вкл.",
cvar_vrmod_right_physgun_beam_offset_x = "Луч правой руки: смещение X",
cvar_vrmod_right_physgun_beam_offset_y = "Луч правой руки: смещение Y",
cvar_vrmod_right_physgun_beam_offset_z = "Луч правой руки: смещение Z",
cvar_vrmod_pickup_beam_enable = "Помощь подбора: вкл.",
tip_vrmod_pickup_beam_enable = "Включить сферический помощник подбора. По умолчанию: ВКЛ",
cvar_vrmod_pickup_beam_cone_range = "Радиус помощи подбора",
tip_vrmod_pickup_beam_cone_range = "Радиус сферы обнаружения вокруг руки (ед.). По умолчанию: 25",
cvar_vrmod_pickup_beam_retry_max = "Макс. повторов помощи подбора",
tip_vrmod_pickup_beam_retry_max = "Макс. повторов помощника подбора (тиков). По умолчанию: 10",
cvar_vrmod_pickup_beam_damage_enable = "Урон лучом подбора",
tip_vrmod_pickup_beam_damage_enable = "Включить урон от луча подбора.",
cvar_vrmod_pickup_beam_damage = "Величина урона лучом подбора",
tip_vrmod_pickup_beam_damage = "Урон, наносимый лучом подбора.",

-- ============================================================
-- Climbing ConVars
-- ============================================================
cvar_vrmod_brushclimb_enable = "Включить карабканье",
tip_vrmod_brushclimb_enable = "Включить систему карабканья в VR. Хватайтесь за поверхности, чтобы подтягиваться. По умолчанию: ВКЛ",
cvar_vrmod_brushclimb_bind_mode = "Режим захвата",
tip_vrmod_brushclimb_bind_mode = "Как работает захват: Удерживать кнопку или Переключатель.",
cvar_vrmod_brushclimb_grab_distance = "Дальность захвата",
tip_vrmod_brushclimb_grab_distance = "Как далеко рука может дотянуться до поверхности. По умолчанию: 22",
cvar_vrmod_brushclimb_launch_mult = "Множитель подброса",
tip_vrmod_brushclimb_launch_mult = "Сила ускорения при отпускании поверхности. По умолчанию: 1.35",
cvar_vrmod_brushclimb_launch_min = "Мин. скорость подброса",
tip_vrmod_brushclimb_launch_min = "Минимальная скорость при отпускании. По умолчанию: 120",
cvar_vrmod_brushclimb_launch_max = "Макс. скорость подброса",
tip_vrmod_brushclimb_launch_max = "Максимальный предел скорости. По умолчанию: 650",
cvar_vrmod_brushclimb_sounds = "Звуки карабканья",
tip_vrmod_brushclimb_sounds = "Воспроизводить звуки при карабканье. По умолчанию: ВКЛ",
cvar_vrmod_brushclimb_sound_volume = "Громкость звуков",
tip_vrmod_brushclimb_sound_volume = "Громкость звуков карабканья. По умолчанию: 0.8",
cvar_vrmod_brushclimb_camera_collision = "Столкновение камеры",
tip_vrmod_brushclimb_camera_collision = "Не давать камере проходить сквозь стены при карабканье.",
cvar_vrmod_brushclimb_allow_walls = "Карабканье по стенам",
tip_vrmod_brushclimb_allow_surface = "Разрешить карабканье по этому типу поверхности.",
cvar_vrmod_brushclimb_allow_ceilings = "Карабканье по потолкам",
cvar_vrmod_brushclimb_allow_ledges = "Карабканье по выступам",
cvar_vrmod_brushclimb_allow_floors = "Карабканье по полу",
cvar_vrmod_brushclimb_allow_doors = "Карабканье по дверям",
cvar_vrmod_brushclimb_allow_pushable = "Карабканье по толкаемым объектам",
cvar_vrmod_brushclimb_allow_toggleable = "Карабканье по переключаемым объектам",
cvar_vrmod_brushclimb_allow_ladders = "Карабканье по лестницам",
cvar_vrmod_brushclimb_hand_inset = "Погружение руки",
tip_vrmod_brushclimb_palm = "Продвинутые настройки смещения ладони/руки.",
cvar_vrmod_brushclimb_wall_push_dist = "Расстояние отталкивания от стены",
cvar_vrmod_brushclimb_palm_fwd = "Смещение ладони вперёд (Л)",
cvar_vrmod_brushclimb_palm_right = "Смещение ладони вправо (Л)",
cvar_vrmod_brushclimb_palm_up = "Смещение ладони вверх (Л)",
cvar_vrmod_brushclimb_palm_fwd_r = "Смещение ладони вперёд (П)",
cvar_vrmod_brushclimb_palm_right_r = "Смещение ладони вправо (П)",
cvar_vrmod_brushclimb_palm_up_r = "Смещение ладони вверх (П)",
opt_bind_mode_0 = "Удерживать",
opt_bind_mode_1 = "Переключатель",

-- Wallrun
cvar_vrmod_wallrun_hand_range = "Бег по стене: дальность руки",
tip_vrmod_wallrun_hand_range = "Как близко рука должна быть к стене для бега по ней.",
cvar_vrmod_wallrun_bind_mode = "Бег по стене: режим активации",
tip_vrmod_wallrun_bind_mode = "Как активируется бег по стене: Удерживать или Переключатель.",
cvar_vrmod_wallrun_cooldown = "Бег по стене: перезарядка",
tip_vrmod_wallrun_cooldown = "Время между забегами по стене. По умолчанию: 0.5",
cvar_vrmod_wallrun_air_regen = "Время восстановления в воздухе",
tip_vrmod_wallrun_air_regen = "Как быстро восстанавливается способность бега по стене в воздухе.",
cvar_vrmod_wallrun_look_max_dot = "Ограничение угла взгляда",
tip_vrmod_wallrun_look_max_dot = "Максимальный угол отклонения взгляда от стены во время бега по ней.",
cvar_vrmod_wallrun_sounds = "Звуки бега по стене",
tip_vrmod_wallrun_sounds = "Воспроизводить звуки шагов при беге по стене.",
cvar_vrmod_wallrun_sound_volume = "Громкость бега по стене",
tip_vrmod_wallrun_sound_volume = "Громкость звуков бега по стене.",
cvar_vrmod_wallrun_sound_interval = "Интервал звуков",
tip_vrmod_wallrun_sound_interval = "Время между звуками шагов.",

-- Slide
cvar_vrmod_slide_enable = "Включить скольжение",
tip_vrmod_slide_enable = "Включить скольжение при приседании на большой скорости.",
cvar_vrmod_slide_head_height = "Высота головы для скольжения",
tip_vrmod_slide_head_height = "Как низко должна быть голова для активации скольжения.",
cvar_vrmod_slide_sounds = "Звуки скольжения",
tip_vrmod_slide_sounds = "Воспроизводить звуки при скольжении.",
cvar_vrmod_slide_sound_volume = "Громкость скольжения",
tip_vrmod_slide_sound_volume = "Громкость звуков скольжения.",

-- Climbing server
cvar_sv_vrmod_brushclimb_reduce_collider = "Уменьшить коллайдер",
tip_sv_vrmod_climbing = "Серверная настройка карабканья. Изменить может только хост.",
cvar_sv_vrmod_brushclimb_allow_walls = "Разрешить стены (сервер)",
cvar_sv_vrmod_brushclimb_allow_ceilings = "Разрешить потолки (сервер)",
cvar_sv_vrmod_brushclimb_allow_ledges = "Разрешить выступы (сервер)",
cvar_sv_vrmod_brushclimb_allow_floors = "Разрешить полы (сервер)",
cvar_sv_vrmod_brushclimb_allow_doors = "Разрешить двери (сервер)",
cvar_sv_vrmod_brushclimb_allow_pushable = "Разрешить толкаемые (сервер)",
cvar_sv_vrmod_brushclimb_allow_toggleable = "Разрешить переключаемые (сервер)",
cvar_sv_vrmod_brushclimb_ledge_normal_min = "Мин. нормаль выступа",
tip_sv_vrmod_climbing_normals = "Пороговый угол поверхности для обнаружения карабканья.",
cvar_sv_vrmod_brushclimb_floor_normal_min = "Мин. нормаль пола",
cvar_sv_vrmod_brushclimb_ceil_normal_max = "Макс. нормаль потолка",

-- Wallrun server
cvar_sv_vrmod_wallrun_jump_force = "Сила прыжка",
tip_sv_vrmod_wallrun = "Серверная настройка бега по стенам. Изменить может только хост.",
cvar_sv_vrmod_wallrun_wall_force = "Сила стены",
cvar_sv_vrmod_wallrun_free_time = "Свободное время",
cvar_sv_vrmod_wallrun_fall_rate = "Скорость падения",
cvar_sv_vrmod_wallrun_max_fall_speed = "Макс. скорость падения",
cvar_sv_vrmod_wallrun_speed_grace = "Запас скорости",
cvar_sv_vrmod_wallrun_min_jump_time = "Мин. время прыжка",

-- Slide server
cvar_sv_vrmod_slide_enable = "Включить скольжение (сервер)",
tip_sv_vrmod_slide = "Серверная настройка скольжения. Изменить может только хост.",
cvar_sv_vrmod_slide_min_speed = "Мин. скорость",
cvar_sv_vrmod_slide_friction = "Трение",
cvar_sv_vrmod_slide_air_boost = "Воздушное ускорение",
cvar_sv_vrmod_slide_stop_speed = "Скорость остановки",
cvar_sv_vrmod_slide_entry_boost = "Начальное ускорение",

-- Debug
cvar_vrmod_brushclimb_debug = "Отладка карабканья",
tip_vrmod_brushclimb_debug = "Показать отладочную визуализацию карабканья.",
cvar_vrmod_brushclimb_debug_text = "Отладочный текст",
tip_vrmod_brushclimb_debug_text = "Показать текстовый оверлей отладки карабканья.",

-- ============================================================
-- Vehicles
-- ============================================================
cvar_vrmod_lvs_input_mode = "Режим управления LVS",
tip_vrmod_lvs_input_mode = "Включить VR-управление для транспорта LVS. По умолчанию: ВКЛ",
opt_lvs_mode_0 = "Отключено",
opt_lvs_mode_1 = "Включено",
cvar_vrmod_sight_bodypart = "Часть тела для прицела",
tip_vrmod_sight_bodypart = "Какая часть тела используется для прицеливания.",
cvar_vrmod_pmchange = "Обработка смены модели",
tip_vrmod_pmchange = "Обрабатывать смену модели игрока в VR.",
cvar_vrmod_auto_seat_reset = "Авто-сброс сиденья",
tip_vrmod_auto_seat_reset = "Автоматически сбрасывать позицию при выходе из сиденья транспорта.",

-- ============================================================
-- Network
-- ============================================================
cvar_vrmod_net_delay = "Сетевая задержка",
tip_vrmod_net_delay = "Минимальная задержка между сетевыми обновлениями. Меньше = плавнее, но больше трафика. По умолчанию: 0.1",
cvar_vrmod_net_delaymax = "Макс. сетевая задержка",
tip_vrmod_net_delaymax = "Максимальный предел задержки. По умолчанию: 0.2",
cvar_vrmod_net_storedframes = "Хранимые кадры",
tip_vrmod_net_storedframes = "Количество кадров позиции для интерполяции. По умолчанию: 15",
cvar_vrmod_net_tickrate = "Тикрейт",
tip_vrmod_net_tickrate = "Тикрейт VR-сети. Больше = плавнее, но больше нагрузка на CPU. По умолчанию: 67",
cvar_vrmod_allow_teleport = "Разрешить телепорт (сервер)",
tip_vrmod_allow_teleport = "Сервер разрешает игрокам использовать телепортацию. По умолчанию: ВКЛ",

-- ============================================================
-- Optimization
-- ============================================================
cvar_vrmod_scr_alwaysautosetting = "Авто-настройки экрана",
tip_vrmod_scr_alwaysautosetting = "Автоматически применять оптимальные настройки разрешения экрана. По умолчанию: ВКЛ",
cvar_vrmod_gmod_optimization_auto = "Авто-оптимизация Gmod",
tip_vrmod_gmod_optimization_auto = "Автоматически применять оптимизации производительности Gmod. По умолчанию: ВКЛ",
cvar_vrmod_auto_arc_benchgun = "Авто-настройка ARC9",
tip_vrmod_auto_arc_benchgun = "Автоматически настраивать параметры оружия ARC9 для VR. По умолчанию: ВКЛ",
cvar_vrmod_auto_lvs_keysetings = "Авто-настройка клавиш LVS",
tip_vrmod_auto_lvs_keysetings = "Автоматически настраивать привязки клавиш LVS. По умолчанию: ВКЛ",

-- ============================================================
-- Developer
-- ============================================================
cvar_vrmod_unoff_developer_mode = "Режим разработчика",
tip_vrmod_unoff_developer_mode = "Включить функции разработчика и расширенное логирование. По умолчанию: ВЫКЛ",
cvar_vrmod_error_hard = "Жёсткие ошибки",
tip_vrmod_error_hard = "Вызывать жёсткие ошибки вместо мягких предупреждений. Для отладки. По умолчанию: ВЫКЛ",
cvar_vrmod_test_Righthandle = "Тестовый маркер правой руки",
tip_vrmod_test_handle = "Включить визуализацию тестового маркера для отладки.",
cvar_vrmod_test_lefthandle = "Тестовый маркер левой руки",
cvar_vrmod_emergencystop_key = "Клавиша аварийной остановки",
tip_vrmod_emergencystop_key = "ID клавиши для экстренного выхода из VR. По умолчанию: KEY_F3 (114)",
cvar_vrmod_emergencystop_time = "Время удержания аварийной остановки",
tip_vrmod_emergencystop_time = "Как долго нужно удерживать клавишу до остановки VR. По умолчанию: 3.0 секунды",
cvar_vrmod_keyguide_mode = "Режим подсказок клавиш",
tip_vrmod_keyguide_mode = "Режим отображения подсказок клавиш на HUD. 0=выкл, 1-3=разные стили.",
cvar_vrmod_keyguide_scale = "Масштаб подсказок клавиш",
tip_vrmod_keyguide_scale = "Размер оверлея подсказок клавиш.",
cvar_vrmod_keyguide_opacity = "Прозрачность подсказок клавиш",
tip_vrmod_keyguide_opacity = "Прозрачность оверлея подсказок клавиш.",

-- ============================================================
-- Commands
-- ============================================================
cmd_vrmod = "Открыть меню VRMod",
tip_cmd_vrmod = "Открыть главное меню настроек VRMod.",
cmd_vrmod_guide = "Открыть руководство",
tip_cmd_vrmod_guide = "Открыть это удобное руководство для начинающих.",
cmd_vrmod_lua_reload_all = "Перезагрузить весь Lua",
tip_cmd_vrmod_lua_reload_all = "Перезагрузить все Lua-скрипты VRMod. Используйте после внесения изменений.",
cmd_vrmod_keyboard = "Открыть VR-клавиатуру",
tip_cmd_vrmod_keyboard = "Открыть виртуальную клавиатуру в VR.",
cmd_vrmod_actioneditor = "Открыть редактор действий",
tip_cmd_vrmod_actioneditor = "Открыть редактор привязок действий SteamVR.",
cmd_vrmod_preset_save_current = "Сохранить пресет",
tip_cmd_preset = "Сохранить/загрузить/удалить пресеты настроек VRMod.",
cmd_vrmod_preset_load_preset = "Загрузить пресет",
cmd_vrmod_preset_delete_preset = "Удалить пресет",
cmd_vrmod_apply_optimization = "Применить оптимизацию",
tip_cmd_vrmod_apply_optimization = "Применить оптимизации производительности прямо сейчас.",
cmd_vrmod_optimization_reset = "Сбросить оптимизацию",
tip_cmd_vrmod_optimization_reset = "Сбросить оптимизации до стандартных настроек Gmod.",
cmd_vrmod_apply_autosettings = "Применить авто-настройки",
tip_cmd_vrmod_apply_autosettings = "Применить автоматические VR-настройки.",
cmd_vrmod_lua_reset_holster_system = "Сбросить систему кобуры",
tip_cmd_reset_holster = "Сбросить систему кобуры для устранения сбоев.",
cmd_vrmod_lua_reset_lefthand_holster = "Сбросить кобуру лев. руки",
cmd_vrmod_unoff_debug_status = "Статус отладки",
tip_cmd_debug = "Показать отладочную информацию в консоли.",
cmd_vrmod_unoff_debug_panel = "Панель отладки",
cmd_vrmod_unoff_debug_hooks_list = "Список всех хуков",
cmd_vrmod_unoff_debug_record_start = "Начать запись",
tip_cmd_debug_record = "Записать данные VR-трекинга для отладки.",
cmd_vrmod_unoff_debug_record_stop = "Остановить запись",
cmd_vrmod_unoff_debug_export = "Экспорт отладочных данных",
tip_cmd_debug_export = "Экспортировать записанные отладочные данные в файл.",
cmd_vrmod_unoff_mock_start = "Запустить эмуляцию VR",
tip_cmd_mock = "Запустить/остановить эмуляцию VR для тестирования без шлема.",
cmd_vrmod_unoff_mock_stop = "Остановить эмуляцию VR",
cmd_vrmod_unoff_mock_status = "Статус эмуляции VR",
cmd_vrmod_print_devices = "Список VR-устройств",
tip_cmd_print_devices = "Вывести список всех подключённых VR-устройств и трекеров.",
cmd_vrmod_net_debug = "Отладка сети",
tip_cmd_net_debug = "Переключить вывод отладки сети.",
cmd_vrmod_doordebug = "Отладка дверей",
tip_cmd_doordebug = "Переключить отладочную информацию о дверях.",
cmd_vrmod_debuglocomotion = "Отладка локомоции",
tip_cmd_debuglocomotion = "Переключить отладочную информацию о перемещении.",
cmd_cardboardmod_start = "Запустить Cardboard VR",
tip_cmd_cardboard = "Запустить/остановить режим Google Cardboard VR.",
cmd_cardboardmod_exit = "Выйти из Cardboard VR",
cmd_vrmod_setlang = "Установить язык (EN)",
tip_cmd_setlang = "Изменить язык главного меню VRMod.",
}

print("[VRMod] Beginner Guide RU language loaded")
