-- --------[vrmod_lvs_beta.lua]Start--------
-- -- vrmod_lvs_beta.luaは同じ (サーバー側の処理は変更なし) --
-- if SERVER then
--     if not LVS then return end
--     if not g_VR then return end
--     local lvssingle = CreateClientConVar("vrmod_lvs_input_mode", "0", true, FCVAR_ARCHIVE, "Enable LVS single player mode for VRMod.")
--     if lvssingle:GetBool() == false then return end
--     function vrmod_lvs_server_singleplay()
--         util.AddNetworkString("lvs_setinput")
--         -- ネットワークメッセージを受け取る
--         net.Receive(
--             "lvs_setinput",
--             function(len, ply)
--                 local inputName = net.ReadString()
--                 local inputValue = net.ReadBool()
--                 if IsValid(ply) then
--                     local vehicle = ply:lvsGetVehicle()
--                     ply:lvsSetInput(inputName, inputValue)
--                     if inputName == "EXIT" and inputValue == true then
--                         ply:ExitVehicle()
--                     end
--                 end
--             end
--         )
--     end

--     vrmod_lvs_server_singleplay()
-- end
-- --------[vrmod_lvs_beta.lua]End--------