-- VRMod Semi-Official - Sub-Addon Localization Extension (Batch 2)
-- Extends VRMOD_LANG tables for sub-addon UI strings
-- Addons: timecrisis, melee, realmech, expression, puppeteer, desktop_mirror

if SERVER then return end
if not VRMOD_LANG then return end

local function AddSettings(lang, entries)
    if not VRMOD_LANG[lang] then return end
    for k, v in pairs(entries) do
        VRMOD_LANG[lang][k] = v
    end
end

-- ============================================================================
-- Japanese / 日本語
-- ============================================================================

-- ----- vrmod_timecrisis -----
AddSettings("ja", {
    ["TIME CRISIS System"] = "TIME CRISISシステム",
    ["Crouch in VR to enter cover mode:"] = "VRでしゃがんでカバーモードに入る:",
    ["You become invincible while crouching"] = "しゃがんでいる間は無敵になる",
    ["You CANNOT attack while in cover"] = "カバー中は攻撃できない",
    ["4 ground holsters appear in a fan pattern"] = "扇状に4つの地面ホルスターが出現",
    ["Stand up to fight normally"] = "立ち上がって通常戦闘",
    ["Inspired by TIME CRISIS arcade game."] = "TIME CRISISアーケードゲームに触発されました。",
    ["Enable Time Crisis Mode"] = "Time Crisisモード有効化",
    ["Block movement while in cover"] = "カバー中の移動をブロック",
    ["Ground Holster Settings"] = "地面ホルスター設定",
    ["Holster distance"] = "ホルスター距離",
    ["Detection radius"] = "検出半径",
    ["Holster Slot Contents"] = "ホルスタースロット内容",
    ["Store weapons by crouching and using the pickup button near a slot."] = "しゃがんでスロット近くでピックアップボタンを使い武器を格納。",
    ["Clear a slot with the button below."] = "下のボタンでスロットをクリア。",
    ["[ Empty ]"] = "[ 空 ]",
    ["Clear"] = "クリア",
    ["Console Commands"] = "コンソールコマンド",
    ["COVER"] = "カバー",
})

-- ----- vrmod_melee -----
AddSettings("ja", {
    ["Basic Settings"] = "基本設定",
    ["Use Gun Melee"] = "銃近接攻撃を使用",
    ["Use Fist Attacks"] = "拳攻撃を使用",
    ["Use Kick Attacks [FBT]"] = "キック攻撃を使用 [FBT]",
    ["Play Hit Sounds"] = "ヒット音を再生",
    ["Enable Hit Feedback"] = "ヒットフィードバック有効化",
    ["Attack Range"] = "攻撃範囲",
    ["Fist Collision Effects"] = "拳衝突エフェクト",
    ["Visible Collision Model"] = "衝突モデル表示",
    ["Damage Settings"] = "ダメージ設定",
    ["Damage (Low)"] = "ダメージ (低)",
    ["Damage (Medium)"] = "ダメージ (中)",
    ["Damage (High)"] = "ダメージ (高)",
    ["Velocity Threshold (Low)"] = "速度閾値 (低)",
    ["Velocity Threshold (Medium)"] = "速度閾値 (中)",
    ["Velocity Threshold (High)"] = "速度閾値 (高)",
    ["Impact Force"] = "衝撃力",
    ["Attack Delay"] = "攻撃遅延",
    ["Attack Cooldown"] = "攻撃クールダウン",
    ["Hitbox Width"] = "ヒットボックス幅",
    ["Hitbox Length"] = "ヒットボックス長さ",
    ["Reset to Defaults"] = "デフォルトにリセット",
    ["Advanced Settings"] = "詳細設定",
    ["Left Hand Hit Command"] = "左手ヒットコマンド",
    ["Right Hand Hit Command"] = "右手ヒットコマンド",
    ["Left Foot Hit Command"] = "左足ヒットコマンド",
    ["Right Foot Hit Command"] = "右足ヒットコマンド",
    ["Gun Hit Command"] = "銃ヒットコマンド",
    ["Collision Effect Model"] = "衝突エフェクトモデル",
    ["Enable Blocking"] = "ブロック有効化",
    ["Block Button"] = "ブロックボタン",
    ["Block Release"] = "ブロック解除",
    ["Block Angle Min"] = "ブロック角度 最小",
    ["Block Angle Max"] = "ブロック角度 最大",
    ["Server Settings"] = "サーバー設定",
    ["NOTE: Server settings require admin/server owner privileges to change."] = "注意: サーバー設定の変更には管理者権限が必要です。",
    ["Allow Gun Melee"] = "銃近接攻撃を許可",
    ["Allow Fist Attacks"] = "拳攻撃を許可",
    ["Allow Kick Attacks (FBT)"] = "キック攻撃を許可 (FBT)",
    ["Enable/disable different types of melee attacks"] = "各種近接攻撃の有効/無効",
    ["Damage (Low Velocity)"] = "ダメージ (低速度)",
    ["Damage (Medium Velocity)"] = "ダメージ (中速度)",
    ["Damage (High Velocity)"] = "ダメージ (高速度)",
    ["Damage values for different velocity levels"] = "速度レベル別のダメージ値",
    ["Velocity thresholds to determine damage level"] = "ダメージレベル判定の速度閾値",
    ["Other server-side melee settings"] = "その他のサーバー側近接設定",
    ["High Velocity Fire Bullets"] = "高速度時に弾丸発射",
    ["Enable bullet firing for high velocity attacks (compatibility mode)"] = "高速攻撃時に弾丸発射を有効化 (互換モード)",
    ["Reset Server Settings to Defaults"] = "サーバー設定をデフォルトにリセット",
    ["Server melee settings reset to defaults"] = "サーバー近接設定をデフォルトにリセットしました",
    ["VR Melee settings have been reset to defaults."] = "VR近接戦闘設定をデフォルトにリセットしました。",
})

-- ----- vrmod_realmech -----
AddSettings("ja", {
    ["RealMech - Realistic Gun Mechanics"] = "RealMech - リアル銃メカニクス",
    ["Automatically detects weapon bones and adds realistic animations."] = "武器ボーンを自動検出しリアルなアニメーションを追加。",
    ["Master Control"] = "マスターコントロール",
    ["Enable RealMech"] = "RealMech有効化",
    ["Slide / Bolt"] = "スライド / ボルト",
    ["Slide Blowback Animation"] = "スライドブローバックアニメーション",
    ["Slide Return Speed"] = "スライド戻り速度",
    ["Default Blowback Distance"] = "デフォルトブローバック距離",
    ["VR Slide Grab"] = "VRスライドグラブ",
    ["Slide Grab Range"] = "スライドグラブ範囲",
    ["Trigger"] = "トリガー",
    ["Trigger Pull Animation"] = "トリガープルアニメーション",
    ["Trigger Pull Angle"] = "トリガープル角度",
    ["Animation Interact Reload"] = "アニメーション操作リロード",
    ["Enable Reload Animation Interact"] = "リロードアニメーション操作有効化",
    ["vrmod_magbone not found - Reload system disabled"] = "vrmod_magboneが見つかりません - リロードシステム無効",
    ["Freeze Delay (seconds)"] = "フリーズ遅延 (秒)",
    ["Freeze Playback Rate"] = "フリーズ再生速度",
    ["Return to Idle on VRMag Pickup (ON=pistol, OFF=revolver/break-action)"] = "VRMagピックアップ時にアイドルに戻る (ON=ピストル, OFF=リボルバー/中折式)",
    ["Reload animation plays, then freezes.\nPick up VRMag to insert. Press Reload again to cancel.\nOFF: keeps frozen pose during insert (revolver/break-action)."] = "リロードアニメーション再生後フリーズ。\nVRMagをピックアップして挿入。リロードで再度押してキャンセル。\nOFF: 挿入中もフリーズポーズを維持 (リボルバー/中折式)。",
    ["Other Mechanics"] = "その他のメカニクス",
    ["Bullet Bone Visibility"] = "弾丸ボーン表示",
    ["Hammer Animation"] = "ハンマーアニメーション",
    ["Fire Selector Animation"] = "セレクターアニメーション",
    ["Advanced"] = "詳細",
    ["Slide Direction Override (auto, -x, +x, -y, +y, -z, +z)"] = "スライド方向オーバーライド (auto, -x, +x, -y, +y, -z, +z)",
    ["Debug Tools"] = "デバッグツール",
    ["Debug: Log Detected Bones"] = "デバッグ: 検出ボーンをログ出力",
    ["Print Detected Bones to Console"] = "検出ボーンをコンソールに出力",
    ["Refresh Bone Cache"] = "ボーンキャッシュを更新",
    ["Restore Default Settings"] = "デフォルト設定に戻す",
    ["RealMech settings reset to defaults."] = "RealMech設定をデフォルトにリセットしました。",
    ["Note: RealMech auto-detects bones from weapon viewmodels.\nArcVR weapons and VR-class weapons are automatically excluded."] = "注意: RealMechは武器ビューモデルからボーンを自動検出します。\nArcVR武器とVRクラス武器は自動的に除外されます。",
})

-- ----- vrmod_expression -----
AddSettings("ja", {
    ["Expression Settings"] = "表情設定",
    ["Enable Expression System"] = "表情システム有効化",
    ["Enables VRChat-style facial expressions driven by VR controller gestures.\nYour character's face will change based on hand poses (peace sign, fist, thumbs up, etc.)."] = "VRコントローラーのジェスチャーで駆動するVRChat風表情システム。\nハンドポーズ (ピースサイン、グー、サムズアップ等) に基づきキャラクターの表情が変化します。",
    ["Auto-detect gestures (finger tracking)"] = "ジェスチャー自動検出 (指トラッキング)",
    ["ON: Automatically detect hand gestures from finger tracking data (best with Index controllers).\nOFF: Use only manual expression selection."] = "ON: 指トラッキングデータからハンドジェスチャーを自動検出 (Indexコントローラー推奨)。\nOFF: 手動表情選択のみ使用。",
    ["Detection Sensitivity"] = "検出感度",
    ["Low (wide dead zone)"] = "低 (広いデッドゾーン)",
    ["Medium (default)"] = "中 (デフォルト)",
    ["High (narrow dead zone)"] = "高 (狭いデッドゾーン)",
    ["Adjusts how easily gestures are triggered.\nLow = harder to trigger (fewer false positives).\nHigh = easier to trigger (more responsive)."] = "ジェスチャーの発動しやすさを調整。\n低 = 発動しにくい (誤検出が少ない)。\n高 = 発動しやすい (レスポンスが良い)。",
    ["Expression Intensity (%)"] = "表情強度 (%)",
    ["Maximum expression intensity when gesture is fully matched.\n100% = normal, 200%+ = exaggerated (GMod broken face style).\nWorks as analog blend with Index controllers."] = "ジェスチャー完全一致時の最大表情強度。\n100% = 通常、200%以上 = 誇張 (GMod顔崩壊スタイル)。\nIndexコントローラーでアナログブレンド対応。",
    ["Manual Expression Select"] = "手動表情選択",
    ["Expression Override"] = "表情オーバーライド",
    ["Select an expression manually, or choose Auto to use gesture detection.\nManual selection overrides gesture detection until Auto is selected again."] = "表情を手動選択するか、自動を選んでジェスチャー検出を使用。\n手動選択は自動が再選択されるまでジェスチャー検出を上書きします。",
    ["Flex Editor (per gesture)"] = "Flexエディタ (ジェスチャー別)",
    ["Expand a gesture to edit its flex weights. Changes are saved automatically."] = "ジェスチャーを展開してflex weightを編集。変更は自動保存されます。",
    ["Reset to Default"] = "デフォルトにリセット",
    ["Reset All Expressions to Default"] = "全表情をデフォルトにリセット",
    ["All expressions reset to default.\nReopen the menu to see changes."] = "全表情をデフォルトにリセットしました。\nメニューを再度開いて変更を確認してください。",
    ["Expression Reset"] = "表情リセット",
})

-- ----- vrmod_puppeteer -----
AddSettings("ja", {
    ["VR Ragdoll Puppeteer (Experimental)"] = "VRラグドールパペッティア (実験的)",
    ["Control a ragdoll puppet with VR tracking.\nDriven bones follow VR (kinematic). Free bones use physics (ragdoll).\nRigging settings are saved to data/vrmod/puppeteer_rig.json."] = "VRトラッキングでラグドール人形を操作。\n駆動ボーンはVRに追従 (キネマティック)。フリーボーンは物理演算 (ラグドール)。\nリグ設定はdata/vrmod/puppeteer_rig.jsonに保存。",
    ["Puppet Control"] = "パペット操作",
    ["Toggle Puppet ON/OFF"] = "パペットON/OFF切替",
    ["Force ON"] = "強制ON",
    ["Force OFF"] = "強制OFF",
    ["Freeze All Bones (Pose Mode)"] = "全ボーンフリーズ (ポーズモード)",
    ["Unfreeze (Resume Rigging)"] = "フリーズ解除 (リグ再開)",
    ["Enable Module"] = "モジュール有効化",
    ["Show in Quick Menu"] = "クイックメニューに表示",
    ["Hide Player Model"] = "プレイヤーモデルを非表示",
    ["Leg Animation (auto: procedural walk / FBT IK)"] = "脚アニメーション (自動: プロシージャルウォーク / FBT IK)",
    ["Physics Affects Player (momentum)"] = "物理がプレイヤーに影響 (運動量)",
    ["Body Tuning"] = "ボディチューニング",
    ["Pelvis Offset (from HMD)"] = "骨盤オフセット (HMDから)",
    ["Shoulder Half-Width"] = "肩半幅",
    ["Momentum Scale"] = "運動量スケール",
    ["VR Input Binding"] = "VR入力バインド",
    ["Toggle Action"] = "トグルアクション",
    ["Head Hiding (VR First Person)"] = "頭非表示 (VR一人称)",
    ["Hide the puppet's head from your VR view to prevent it blocking your vision.\nOther players and desktop view will still see the head normally."] = "VR視界でパペットの頭を非表示にして視界の遮りを防止。\n他プレイヤーとデスクトップ表示では頭は通常通り表示されます。",
    ["Hide Head Mode"] = "頭非表示モード",
    ["Scale (hide completely)"] = "スケール (完全非表示)",
    ["Offset (push behind)"] = "オフセット (後ろに押す)",
    ["Disabled (show head)"] = "無効 (頭を表示)",
    ["Show HUD Indicator"] = "HUDインジケーター表示",
    ["Bone Rigging (Driven vs Physics)"] = "ボーンリグ (駆動 vs 物理)",
    ["DRIVEN (checked) = follows VR tracking, stable\nPHYSICS (unchecked) = ragdoll physics, dangles\nChanges auto-save and apply immediately."] = "駆動 (チェック) = VRトラッキングに追従、安定\n物理 (未チェック) = ラグドール物理、ぶら下がる\n変更は自動保存・即時適用。",
    ["Quick Actions"] = "クイックアクション",
    ["All DRIVEN"] = "全て駆��",
    ["All PHYSICS (full ragdoll)"] = "全て物理 (フルラグドール)",
    ["Head + Hands Only (recommended)"] = "頭+手のみ (推奨)",
})

-- ----- vrmod_desktop_mirror -----
AddSettings("ja", {
    ["Enable Desktop Mirror"] = "デスクトップミラー有効化",
})


-- ============================================================================
-- Chinese Simplified / 简体中文
-- ============================================================================

-- ----- vrmod_timecrisis -----
AddSettings("zh", {
    ["TIME CRISIS System"] = "TIME CRISIS系统",
    ["Crouch in VR to enter cover mode:"] = "在VR中蹲下进入掩体模式:",
    ["You become invincible while crouching"] = "蹲下时变为无敌",
    ["You CANNOT attack while in cover"] = "掩体中无法攻击",
    ["4 ground holsters appear in a fan pattern"] = "扇形出现4个地面枪套",
    ["Stand up to fight normally"] = "站起来正常战斗",
    ["Inspired by TIME CRISIS arcade game."] = "灵感来自TIME CRISIS街机游戏。",
    ["Enable Time Crisis Mode"] = "启用Time Crisis模式",
    ["Block movement while in cover"] = "掩体中阻止移动",
    ["Ground Holster Settings"] = "地面枪套设置",
    ["Holster distance"] = "枪套距离",
    ["Detection radius"] = "检测半径",
    ["Holster Slot Contents"] = "枪套槽位内容",
    ["Store weapons by crouching and using the pickup button near a slot."] = "蹲下并在槽位附近按拾取键存放武器。",
    ["Clear a slot with the button below."] = "用下方按钮清空槽位。",
    ["[ Empty ]"] = "[ 空 ]",
    ["Clear"] = "清空",
    ["Console Commands"] = "控制台命令",
    ["COVER"] = "掩护",
})

-- ----- vrmod_melee -----
AddSettings("zh", {
    ["Basic Settings"] = "基本设置",
    ["Use Gun Melee"] = "使用枪械近战",
    ["Use Fist Attacks"] = "使用拳头攻击",
    ["Use Kick Attacks [FBT]"] = "使用踢击 [FBT]",
    ["Play Hit Sounds"] = "播放命中音效",
    ["Enable Hit Feedback"] = "启用命中反馈",
    ["Attack Range"] = "攻击范围",
    ["Fist Collision Effects"] = "拳头碰撞特效",
    ["Visible Collision Model"] = "显示碰撞模型",
    ["Damage Settings"] = "伤害设置",
    ["Damage (Low)"] = "伤害 (低)",
    ["Damage (Medium)"] = "伤害 (中)",
    ["Damage (High)"] = "伤害 (高)",
    ["Velocity Threshold (Low)"] = "速度阈值 (低)",
    ["Velocity Threshold (Medium)"] = "速度阈值 (中)",
    ["Velocity Threshold (High)"] = "速度阈值 (高)",
    ["Impact Force"] = "冲击力",
    ["Attack Delay"] = "攻击延迟",
    ["Attack Cooldown"] = "攻击冷却",
    ["Hitbox Width"] = "碰撞箱宽度",
    ["Hitbox Length"] = "碰撞箱长度",
    ["Reset to Defaults"] = "恢复默认",
    ["Advanced Settings"] = "高级设置",
    ["Left Hand Hit Command"] = "左手命中命令",
    ["Right Hand Hit Command"] = "右手命中命令",
    ["Left Foot Hit Command"] = "左脚命中命令",
    ["Right Foot Hit Command"] = "右脚命中命令",
    ["Gun Hit Command"] = "枪械命中命令",
    ["Collision Effect Model"] = "碰撞效果模型",
    ["Enable Blocking"] = "启用格挡",
    ["Block Button"] = "格挡按钮",
    ["Block Release"] = "格挡释放",
    ["Block Angle Min"] = "格挡角度最小值",
    ["Block Angle Max"] = "格挡角度最大值",
    ["Server Settings"] = "服务器设置",
    ["NOTE: Server settings require admin/server owner privileges to change."] = "注意：更改服务器设置需要管理员权限。",
    ["Allow Gun Melee"] = "允许枪械近战",
    ["Allow Fist Attacks"] = "允许拳头攻击",
    ["Allow Kick Attacks (FBT)"] = "允许踢击 (FBT)",
    ["Enable/disable different types of melee attacks"] = "启用/禁用各类近战攻击",
    ["Damage (Low Velocity)"] = "伤害 (低速)",
    ["Damage (Medium Velocity)"] = "伤害 (中速)",
    ["Damage (High Velocity)"] = "伤害 (高速)",
    ["Damage values for different velocity levels"] = "不同速度级别的伤害值",
    ["Velocity thresholds to determine damage level"] = "确定伤害级别的速度阈值",
    ["Other server-side melee settings"] = "其他服务器端近战设置",
    ["High Velocity Fire Bullets"] = "高速时发射子弹",
    ["Enable bullet firing for high velocity attacks (compatibility mode)"] = "高速攻击时启用子弹发射 (兼容模式)",
    ["Reset Server Settings to Defaults"] = "重置服务器设置为默认值",
    ["Server melee settings reset to defaults"] = "服务器近战设置已重置为默认值",
    ["VR Melee settings have been reset to defaults."] = "VR近战设置已重置为默认值。",
})

-- ----- vrmod_realmech -----
AddSettings("zh", {
    ["RealMech - Realistic Gun Mechanics"] = "RealMech - 真实枪械机制",
    ["Automatically detects weapon bones and adds realistic animations."] = "自动检测武器骨骼并添加真实动画。",
    ["Master Control"] = "主控制",
    ["Enable RealMech"] = "启用RealMech",
    ["Slide / Bolt"] = "滑套 / 枪栓",
    ["Slide Blowback Animation"] = "滑套后座动画",
    ["Slide Return Speed"] = "滑套回位速度",
    ["Default Blowback Distance"] = "默认后座距离",
    ["VR Slide Grab"] = "VR滑套抓握",
    ["Slide Grab Range"] = "滑套抓握范围",
    ["Trigger"] = "扳机",
    ["Trigger Pull Animation"] = "扳机扣压动画",
    ["Trigger Pull Angle"] = "扳机扣压角度",
    ["Animation Interact Reload"] = "动画交互换弹",
    ["Enable Reload Animation Interact"] = "启用换弹动画交互",
    ["vrmod_magbone not found - Reload system disabled"] = "未找到vrmod_magbone - 换弹系统已禁用",
    ["Freeze Delay (seconds)"] = "冻结延迟 (秒)",
    ["Freeze Playback Rate"] = "冻结播放速率",
    ["Return to Idle on VRMag Pickup (ON=pistol, OFF=revolver/break-action)"] = "VRMag拾取时回到待机 (ON=手枪, OFF=左轮/折叠式)",
    ["Reload animation plays, then freezes.\nPick up VRMag to insert. Press Reload again to cancel.\nOFF: keeps frozen pose during insert (revolver/break-action)."] = "换弹动画播放后冻结。\n拾取VRMag插入弹匣。再次按换弹取消。\nOFF：插入时保持冻结姿势 (左轮/折叠式)。",
    ["Other Mechanics"] = "其他机制",
    ["Bullet Bone Visibility"] = "子弹骨骼可见性",
    ["Hammer Animation"] = "击锤动画",
    ["Fire Selector Animation"] = "射击选择器动画",
    ["Advanced"] = "高级",
    ["Slide Direction Override (auto, -x, +x, -y, +y, -z, +z)"] = "滑套方向覆盖 (auto, -x, +x, -y, +y, -z, +z)",
    ["Debug Tools"] = "调试工具",
    ["Debug: Log Detected Bones"] = "调试：记录检测到的骨骼",
    ["Print Detected Bones to Console"] = "将检测到的骨骼输出到控制台",
    ["Refresh Bone Cache"] = "刷新骨骼缓存",
    ["Restore Default Settings"] = "恢复默认设置",
    ["RealMech settings reset to defaults."] = "RealMech设置已重置为默认值。",
    ["Note: RealMech auto-detects bones from weapon viewmodels.\nArcVR weapons and VR-class weapons are automatically excluded."] = "注意：RealMech从武器视角模型自动检测骨骼。\nArcVR武器和VR类武器将自动排除。",
})

-- ----- vrmod_expression -----
AddSettings("zh", {
    ["Expression Settings"] = "表情设置",
    ["Enable Expression System"] = "启用表情系统",
    ["Enables VRChat-style facial expressions driven by VR controller gestures.\nYour character's face will change based on hand poses (peace sign, fist, thumbs up, etc.)."] = "启用由VR控制器手势驱动的VRChat风格面部表情。\n角色的面部会根据手势改变 (剪刀手、握拳、竖拇指等)。",
    ["Auto-detect gestures (finger tracking)"] = "自动检测手势 (手指追踪)",
    ["ON: Automatically detect hand gestures from finger tracking data (best with Index controllers).\nOFF: Use only manual expression selection."] = "ON：从手指追踪数据自动检测手势 (Index控制器最佳)。\nOFF：仅使用手动表情选择。",
    ["Detection Sensitivity"] = "检测灵敏度",
    ["Low (wide dead zone)"] = "低 (宽死区)",
    ["Medium (default)"] = "中 (默认)",
    ["High (narrow dead zone)"] = "高 (窄死区)",
    ["Adjusts how easily gestures are triggered.\nLow = harder to trigger (fewer false positives).\nHigh = easier to trigger (more responsive)."] = "调整手势触发的灵敏度。\n低 = 更难触发 (误触少)。\n高 = 更容易触发 (响应更快)。",
    ["Expression Intensity (%)"] = "表情强度 (%)",
    ["Maximum expression intensity when gesture is fully matched.\n100% = normal, 200%+ = exaggerated (GMod broken face style).\nWorks as analog blend with Index controllers."] = "手势完全匹配时的最大表情强度。\n100% = 正常，200%以上 = 夸张 (GMod崩脸风格)。\n支持Index控制器模拟混合。",
    ["Manual Expression Select"] = "手动表情选择",
    ["Expression Override"] = "表情覆盖",
    ["Select an expression manually, or choose Auto to use gesture detection.\nManual selection overrides gesture detection until Auto is selected again."] = "手动选择表情，或选择自动使用手势检测。\n手动选择将覆盖手势检测，直到再次选择自动。",
    ["Flex Editor (per gesture)"] = "Flex编辑器 (按手势)",
    ["Expand a gesture to edit its flex weights. Changes are saved automatically."] = "展开手势以编辑其flex权重。更改自动保存。",
    ["Reset to Default"] = "恢复默认",
    ["Reset All Expressions to Default"] = "重置所有表情为默认值",
    ["All expressions reset to default.\nReopen the menu to see changes."] = "所有表情已重置为默认值。\n重新打开菜单查看更改。",
    ["Expression Reset"] = "表情重置",
})

-- ----- vrmod_puppeteer -----
AddSettings("zh", {
    ["VR Ragdoll Puppeteer (Experimental)"] = "VR布娃娃操控 (实验性)",
    ["Control a ragdoll puppet with VR tracking.\nDriven bones follow VR (kinematic). Free bones use physics (ragdoll).\nRigging settings are saved to data/vrmod/puppeteer_rig.json."] = "使用VR追踪控制布娃娃。\n驱动骨骼跟随VR (运动学)。自由骨骼使用物理 (布娃娃)。\n绑定设置保存到data/vrmod/puppeteer_rig.json。",
    ["Puppet Control"] = "操控面板",
    ["Toggle Puppet ON/OFF"] = "切换操控ON/OFF",
    ["Force ON"] = "强制ON",
    ["Force OFF"] = "强制OFF",
    ["Freeze All Bones (Pose Mode)"] = "冻结所有骨骼 (姿势模式)",
    ["Unfreeze (Resume Rigging)"] = "解冻 (恢复绑定)",
    ["Enable Module"] = "启用模块",
    ["Show in Quick Menu"] = "在快捷菜单中显示",
    ["Hide Player Model"] = "隐藏玩家模型",
    ["Leg Animation (auto: procedural walk / FBT IK)"] = "腿部动画 (自动：程序化行走 / FBT IK)",
    ["Physics Affects Player (momentum)"] = "物理影响玩家 (动量)",
    ["Body Tuning"] = "身体调节",
    ["Pelvis Offset (from HMD)"] = "骨盆偏移 (从HMD)",
    ["Shoulder Half-Width"] = "肩部半宽",
    ["Momentum Scale"] = "动量比例",
    ["VR Input Binding"] = "VR输入绑定",
    ["Toggle Action"] = "切换动作",
    ["Head Hiding (VR First Person)"] = "头部隐藏 (VR第一人称)",
    ["Hide the puppet's head from your VR view to prevent it blocking your vision.\nOther players and desktop view will still see the head normally."] = "在VR视图中隐藏人偶头部以防遮挡视线。\n其他玩家和桌面视图仍会正常看到头部。",
    ["Hide Head Mode"] = "隐藏头部模式",
    ["Scale (hide completely)"] = "缩放 (完全隐藏)",
    ["Offset (push behind)"] = "偏移 (向后推)",
    ["Disabled (show head)"] = "禁用 (显示头部)",
    ["Show HUD Indicator"] = "显示HUD指示器",
    ["Bone Rigging (Driven vs Physics)"] = "骨骼绑定 (驱动 vs 物理)",
    ["DRIVEN (checked) = follows VR tracking, stable\nPHYSICS (unchecked) = ragdoll physics, dangles\nChanges auto-save and apply immediately."] = "驱动 (勾选) = 跟随VR追踪，稳定\n物理 (未勾选) = 布娃娃物理，悬挂\n更改自动保存并立即生效。",
    ["Quick Actions"] = "快捷操作",
    ["All DRIVEN"] = "全部驱动",
    ["All PHYSICS (full ragdoll)"] = "全部物理 (完全布娃娃)",
    ["Head + Hands Only (recommended)"] = "仅头+手 (推荐)",
})

-- ----- vrmod_desktop_mirror -----
AddSettings("zh", {
    ["Enable Desktop Mirror"] = "启用桌面镜像",
})


-- ============================================================================
-- Russian / Русский
-- ============================================================================

-- ----- vrmod_timecrisis -----
AddSettings("ru", {
    ["TIME CRISIS System"] = "Система TIME CRISIS",
    ["Crouch in VR to enter cover mode:"] = "Присядьте в VR для режима укрытия:",
    ["You become invincible while crouching"] = "Вы становитесь неуязвимым в присяде",
    ["You CANNOT attack while in cover"] = "В укрытии нельзя атаковать",
    ["4 ground holsters appear in a fan pattern"] = "4 напольных кобуры появляются веером",
    ["Stand up to fight normally"] = "Встаньте для обычного боя",
    ["Inspired by TIME CRISIS arcade game."] = "Вдохновлено аркадой TIME CRISIS.",
    ["Enable Time Crisis Mode"] = "Включить режим Time Crisis",
    ["Block movement while in cover"] = "Блокировать движение в укрытии",
    ["Ground Holster Settings"] = "Настройки напольных кобур",
    ["Holster distance"] = "Расстояние кобуры",
    ["Detection radius"] = "Радиус обнаружения",
    ["Holster Slot Contents"] = "Содержимое слотов кобур",
    ["Store weapons by crouching and using the pickup button near a slot."] = "Сохраняйте оружие приседая и нажимая кнопку подбора рядом со слотом.",
    ["Clear a slot with the button below."] = "Очистите слот кнопкой ниже.",
    ["[ Empty ]"] = "[ Пусто ]",
    ["Clear"] = "Очистить",
    ["Console Commands"] = "Консольные команды",
    ["COVER"] = "УКРЫТИЕ",
})

-- ----- vrmod_melee -----
AddSettings("ru", {
    ["Basic Settings"] = "Основные настройки",
    ["Use Gun Melee"] = "Удар оружием",
    ["Use Fist Attacks"] = "Удары кулаками",
    ["Use Kick Attacks [FBT]"] = "Удары ногами [FBT]",
    ["Play Hit Sounds"] = "Звуки попадания",
    ["Enable Hit Feedback"] = "Обратная связь попадания",
    ["Attack Range"] = "Дальность атаки",
    ["Fist Collision Effects"] = "Эффекты столкновения кулака",
    ["Visible Collision Model"] = "Видимая модель столкновения",
    ["Damage Settings"] = "Настройки урона",
    ["Damage (Low)"] = "Урон (низкий)",
    ["Damage (Medium)"] = "Урон (средний)",
    ["Damage (High)"] = "Урон (высокий)",
    ["Velocity Threshold (Low)"] = "Порог скорости (низкий)",
    ["Velocity Threshold (Medium)"] = "Порог скорости (средний)",
    ["Velocity Threshold (High)"] = "Порог скорости (высокий)",
    ["Impact Force"] = "Сила удара",
    ["Attack Delay"] = "Задержка атаки",
    ["Attack Cooldown"] = "Перезарядка атаки",
    ["Hitbox Width"] = "Ширина хитбокса",
    ["Hitbox Length"] = "Длина хитбокса",
    ["Reset to Defaults"] = "Сброс настроек",
    ["Advanced Settings"] = "Дополнительно",
    ["Left Hand Hit Command"] = "Команда удара левой",
    ["Right Hand Hit Command"] = "Команда удара правой",
    ["Left Foot Hit Command"] = "Команда удара левой ногой",
    ["Right Foot Hit Command"] = "Команда удара правой ногой",
    ["Gun Hit Command"] = "Команда удара оружием",
    ["Collision Effect Model"] = "Модель эффекта столкновения",
    ["Enable Blocking"] = "Включить блокировку",
    ["Block Button"] = "Кнопка блока",
    ["Block Release"] = "Отпускание блока",
    ["Block Angle Min"] = "Мин. угол блока",
    ["Block Angle Max"] = "Макс. угол блока",
    ["Server Settings"] = "Настройки сервера",
    ["NOTE: Server settings require admin/server owner privileges to change."] = "ВНИМАНИЕ: Для изменения серверных настроек нужны права админа.",
    ["Allow Gun Melee"] = "Разрешить удар оружием",
    ["Allow Fist Attacks"] = "Разрешить удары кулаками",
    ["Allow Kick Attacks (FBT)"] = "Разрешить удары ногами (FBT)",
    ["Enable/disable different types of melee attacks"] = "Включение/выключение типов ближнего боя",
    ["Damage (Low Velocity)"] = "Урон (низкая скорость)",
    ["Damage (Medium Velocity)"] = "Урон (средняя скорость)",
    ["Damage (High Velocity)"] = "Урон (высокая скорость)",
    ["Damage values for different velocity levels"] = "Значения урона для разных скоростей",
    ["Velocity thresholds to determine damage level"] = "Пороги скорости для уровня урона",
    ["Other server-side melee settings"] = "Другие серверные настройки ближнего боя",
    ["High Velocity Fire Bullets"] = "Пули при высокой скорости",
    ["Enable bullet firing for high velocity attacks (compatibility mode)"] = "Стрельба пулями при быстрых атаках (режим совместимости)",
    ["Reset Server Settings to Defaults"] = "Сброс серверных настроек",
    ["Server melee settings reset to defaults"] = "Серверные настройки ближнего боя сброшены",
    ["VR Melee settings have been reset to defaults."] = "Настройки VR ближнего боя сброшены.",
})

-- ----- vrmod_realmech -----
AddSettings("ru", {
    ["RealMech - Realistic Gun Mechanics"] = "RealMech - Реалистичная механика оружия",
    ["Automatically detects weapon bones and adds realistic animations."] = "Автоматически определяет кости оружия и добавляет реалистичные анимации.",
    ["Master Control"] = "Главное управление",
    ["Enable RealMech"] = "Включить RealMech",
    ["Slide / Bolt"] = "Затвор / Болт",
    ["Slide Blowback Animation"] = "Анимация отката затвора",
    ["Slide Return Speed"] = "Скорость возврата затвора",
    ["Default Blowback Distance"] = "Расстояние отката по умолчанию",
    ["VR Slide Grab"] = "VR захват затвора",
    ["Slide Grab Range"] = "Дальность захвата затвора",
    ["Trigger"] = "Спусковой крючок",
    ["Trigger Pull Animation"] = "Анимация нажатия спуска",
    ["Trigger Pull Angle"] = "Угол нажатия спуска",
    ["Animation Interact Reload"] = "Анимация интерактивной перезарядки",
    ["Enable Reload Animation Interact"] = "Включить интерактивную перезарядку",
    ["vrmod_magbone not found - Reload system disabled"] = "vrmod_magbone не найден - Система перезарядки отключена",
    ["Freeze Delay (seconds)"] = "Задержка заморозки (сек)",
    ["Freeze Playback Rate"] = "Скорость воспроизведения заморозки",
    ["Return to Idle on VRMag Pickup (ON=pistol, OFF=revolver/break-action)"] = "Возврат в покой при подборе VRMag (ON=пистолет, OFF=револьвер/переламывающийся)",
    ["Reload animation plays, then freezes.\nPick up VRMag to insert. Press Reload again to cancel.\nOFF: keeps frozen pose during insert (revolver/break-action)."] = "Анимация перезарядки проигрывается и замирает.\nПодберите VRMag для вставки. Нажмите перезарядку снова для отмены.\nOFF: сохраняет замершую позу при вставке (револьвер/переламывающийся).",
    ["Other Mechanics"] = "Другие механики",
    ["Bullet Bone Visibility"] = "Видимость кости пули",
    ["Hammer Animation"] = "Анимация курка",
    ["Fire Selector Animation"] = "Анимация переводчика огня",
    ["Advanced"] = "Дополнительно",
    ["Slide Direction Override (auto, -x, +x, -y, +y, -z, +z)"] = "Направление затвора (auto, -x, +x, -y, +y, -z, +z)",
    ["Debug Tools"] = "Инструменты отладки",
    ["Debug: Log Detected Bones"] = "Отладка: Логировать найденные кости",
    ["Print Detected Bones to Console"] = "Вывести найденные кости в консоль",
    ["Refresh Bone Cache"] = "Обновить кэш костей",
    ["Restore Default Settings"] = "Восстановить настройки по умолчанию",
    ["RealMech settings reset to defaults."] = "Настройки RealMech сброшены.",
    ["Note: RealMech auto-detects bones from weapon viewmodels.\nArcVR weapons and VR-class weapons are automatically excluded."] = "Примечание: RealMech автоматически определяет кости из моделей оружия.\nОружие ArcVR и VR-класса автоматически исключается.",
})

-- ----- vrmod_expression -----
AddSettings("ru", {
    ["Expression Settings"] = "Настройки выражений",
    ["Enable Expression System"] = "Включить систему выражений",
    ["Enables VRChat-style facial expressions driven by VR controller gestures.\nYour character's face will change based on hand poses (peace sign, fist, thumbs up, etc.)."] = "Включает мимику в стиле VRChat на основе жестов VR-контроллеров.\nЛицо персонажа меняется в зависимости от жестов рук (мир, кулак, палец вверх и т.д.).",
    ["Auto-detect gestures (finger tracking)"] = "Авто-распознавание жестов (отслеживание пальцев)",
    ["ON: Automatically detect hand gestures from finger tracking data (best with Index controllers).\nOFF: Use only manual expression selection."] = "ON: Автоматически определять жесты из данных пальцев (лучше всего с Index).\nOFF: Только ручной выбор выражений.",
    ["Detection Sensitivity"] = "Чувствительность распознавания",
    ["Low (wide dead zone)"] = "Низкая (широкая мёртвая зона)",
    ["Medium (default)"] = "Средняя (по умолчанию)",
    ["High (narrow dead zone)"] = "Высокая (узкая мёртвая зона)",
    ["Adjusts how easily gestures are triggered.\nLow = harder to trigger (fewer false positives).\nHigh = easier to trigger (more responsive)."] = "Настройка лёгкости срабатывания жестов.\nНизкая = труднее сработать (меньше ложных).\nВысокая = легче сработать (отзывчивее).",
    ["Expression Intensity (%)"] = "Интенсивность выражения (%)",
    ["Maximum expression intensity when gesture is fully matched.\n100% = normal, 200%+ = exaggerated (GMod broken face style).\nWorks as analog blend with Index controllers."] = "Максимальная интенсивность при полном совпадении жеста.\n100% = нормально, 200%+ = преувеличенно (стиль ломаного лица GMod).\nРаботает как аналоговое смешивание с Index.",
    ["Manual Expression Select"] = "Ручной выбор выражения",
    ["Expression Override"] = "Принудительное выражение",
    ["Select an expression manually, or choose Auto to use gesture detection.\nManual selection overrides gesture detection until Auto is selected again."] = "Выберите выражение вручную или выберите Авто для определения жестов.\nРучной выбор отменяет жесты до повторного выбора Авто.",
    ["Flex Editor (per gesture)"] = "Редактор Flex (по жестам)",
    ["Expand a gesture to edit its flex weights. Changes are saved automatically."] = "Разверните жест для редактирования flex-весов. Изменения сохраняются автоматически.",
    ["Reset to Default"] = "Сброс по умолчанию",
    ["Reset All Expressions to Default"] = "Сбросить все выражения",
    ["All expressions reset to default.\nReopen the menu to see changes."] = "Все выражения сброшены.\nПереоткройте меню для просмотра изменений.",
    ["Expression Reset"] = "Сброс выражений",
})

-- ----- vrmod_puppeteer -----
AddSettings("ru", {
    ["VR Ragdoll Puppeteer (Experimental)"] = "VR Кукловод (Экспериментально)",
    ["Control a ragdoll puppet with VR tracking.\nDriven bones follow VR (kinematic). Free bones use physics (ragdoll).\nRigging settings are saved to data/vrmod/puppeteer_rig.json."] = "Управляйте куклой-рэгдоллом через VR.\nУправляемые кости следуют за VR (кинематика). Свободные кости — физика (рэгдолл).\nНастройки привязки сохраняются в data/vrmod/puppeteer_rig.json.",
    ["Puppet Control"] = "Управление куклой",
    ["Toggle Puppet ON/OFF"] = "Кукла ВКЛ/ВЫКЛ",
    ["Force ON"] = "Принудительно ВКЛ",
    ["Force OFF"] = "Принудительно ВЫКЛ",
    ["Freeze All Bones (Pose Mode)"] = "Заморозить все кости (режим позы)",
    ["Unfreeze (Resume Rigging)"] = "Разморозить (продолжить привязку)",
    ["Enable Module"] = "Включить модуль",
    ["Show in Quick Menu"] = "Показать в быстром меню",
    ["Hide Player Model"] = "Скрыть модель игрока",
    ["Leg Animation (auto: procedural walk / FBT IK)"] = "Анимация ног (авто: процедурная ходьба / FBT IK)",
    ["Physics Affects Player (momentum)"] = "Физика влияет на игрока (импульс)",
    ["Body Tuning"] = "Настройка тела",
    ["Pelvis Offset (from HMD)"] = "Смещение таза (от HMD)",
    ["Shoulder Half-Width"] = "Полуширина плеч",
    ["Momentum Scale"] = "Масштаб импульса",
    ["VR Input Binding"] = "Привязка VR-ввода",
    ["Toggle Action"] = "Действие переключения",
    ["Head Hiding (VR First Person)"] = "Скрытие головы (VR от первого лица)",
    ["Hide the puppet's head from your VR view to prevent it blocking your vision.\nOther players and desktop view will still see the head normally."] = "Скрывает голову куклы в VR чтобы не загораживать обзор.\nДругие игроки и экран будут видеть голову нормально.",
    ["Hide Head Mode"] = "Режим скрытия головы",
    ["Scale (hide completely)"] = "Масштаб (полностью скрыть)",
    ["Offset (push behind)"] = "Смещение (сдвинуть назад)",
    ["Disabled (show head)"] = "Выключено (показать голову)",
    ["Show HUD Indicator"] = "Показать индикатор HUD",
    ["Bone Rigging (Driven vs Physics)"] = "Привязка костей (Управление vs Физика)",
    ["DRIVEN (checked) = follows VR tracking, stable\nPHYSICS (unchecked) = ragdoll physics, dangles\nChanges auto-save and apply immediately."] = "УПРАВЛЕНИЕ (✓) = следует за VR, стабильно\nФИЗИКА (пусто) = рэгдолл, болтается\nИзменения сохраняются и применяются сразу.",
    ["Quick Actions"] = "Быстрые действия",
    ["All DRIVEN"] = "Всё управляемое",
    ["All PHYSICS (full ragdoll)"] = "Всё физика (полный рэгдолл)",
    ["Head + Hands Only (recommended)"] = "Голова + Руки (рекомендуется)",
})

-- ----- vrmod_desktop_mirror -----
AddSettings("ru", {
    ["Enable Desktop Mirror"] = "Включить зеркало рабочего стола",
})

print("[VRMod] Localization subaddons2 loaded")
