-- VRMod Semi-Official - Sub-Addon Localization
-- Translations for all sub-addon UI strings
-- Loaded after vrmod_localization.lua via VRMOD_LANG tables

if SERVER then return end
if not VRMOD_LANG then return end

local function AddSettings(lang, entries)
    if not VRMOD_LANG[lang] then return end
    for k, v in pairs(entries) do
        VRMOD_LANG[lang][k] = v
    end
end

-- ============================================================================
-- Japanese
-- ============================================================================
AddSettings("ja", {
    -- ==============================
    -- vrmod_arcvr_fix (ArcticVR)
    -- ==============================
    ["ArcticVR"] = "ArcticVR",
    ["Settings1"] = "設定1",
    ["Settings2"] = "設定2",
    ["GunMelee"] = "銃近接攻撃",
    ["MagPouch"] = "マグポーチ",
    ["Server"] = "サーバー",
    ["Presets"] = "プリセット",
    ["[arcticvr_grip_with_reloadkey]\nON = Reloadkey with\nOFF = Boolean_left_secondaryfire"] = "[arcticvr_grip_with_reloadkey]\nON = リロードキー併用\nOFF = Boolean_left_secondaryfire",
    ["[mag_bumpreload] \n You can reload a magazine with the Reload key enabled gun \n by popping the magazine with the magazine."] = "[mag_bumpreload]\nリロードキー有効時、マガジン同士をぶつけて\nリロードできます。",
    ["[frontgrip alternative mode] \n The leftpickup key will no longer allow you to grip the foregrip\nbut only while pressing the reload or left_secondary_fire set above\nThis reduces the chance of accidentally removing the magazine."] = "[フォアグリップ代替モード]\n左ピックアップキーではフォアグリップを\n掴めなくなり、リロードキーまたは\nleft_secondary_fire押下中のみ有効になります。\nマガジンの誤脱落を防止します。",
    ["[slide_magnification]\n A higher value allows \n cocking even when the \n hand is away from the slide."] = "[スライド倍率]\n値が大きいほど\n手がスライドから離れていても\nコッキングできます。",
    ["[arcticvr_grip_magnification]\nThe larger the value\nthe greater the decision\nto start holding the foregrip"] = "[グリップ倍率]\n値が大きいほど\nフォアグリップの\n掴み判定が広がります。",
    ["[arcticvr_disable_reload_with_key]"] = "[リロードキー無効化]",
    ["[arcticvr_disable_grabreload]"] = "[グラブリロード無効化]",
    ["[ArcticVR Virtualstock] \n Using a VR weapon with a stock close to the shoulder or head \n will help stabilize the sight."] = "[ArcticVR バーチャルストック]\nストック付きVR武器を肩や頭に近づけると\n照準が安定します。",
    ["[Frontgrip_Power]\nhow much the movement\nof your left hand affects\nthe sight of the gun\nwhen you grab the foregrip"] = "[フォアグリップ感度]\nフォアグリップを掴んでいる時に\n左手の動きが照準に\nどの程度影響するか",
    ["[Grenade_pin_enable] \n When set to false\n the specification allows a grenade to be thrown without\npulling out the safety pin."] = "[グレネードピン有効]\nOFFにすると安全ピンを\n抜かずにグレネードを\n投げることができます。",
    ["[test_cl_misc_fix]\nFor some ArcVR weapons\ncheck the box if the magazine cannot be removed."] = "[cl_misc修正テスト]\n一部のArcVR武器でマガジンが\n外せない場合はチェックを入れてください。",
    ["[Shoot System Fix] \n Check the box if the shotgun sights are significantly misaligned \n and uncheck the box if some ArcVR weapons become unusable."] = "[射撃システム修正]\nショットガンの照準が大きくずれる場合は\nチェックを入れ、一部のArcVR武器が\n使えなくなる場合は外してください。",
    ["[gunmelee]"] = "[銃近接攻撃]",
    ["[gunmelee_client]"] = "[銃近接攻撃クライアント]",
    ["[fist]"] = "[拳]",
    ["[fist_client]"] = "[拳クライアント]",
    ["[kick]-FBTOnly-(buggy)"] = "[キック]-FBT専用-(不安定)",
    ["[kick_client]-FBTOnly-(buggy)"] = "[キッククライアント]-FBT専用-(不安定)",
    ["gunmelee_velthreshold"] = "銃近接攻撃 速度閾値",
    ["gunmelee_damage"] = "銃近接攻撃 ダメージ",
    ["gunmelee_Delay"] = "銃近接攻撃 ディレイ",
    ["Default Pouch Distance"] = "デフォルトポーチ距離",
    ["[hybridpouch]"] = "[ハイブリッドポーチ]",
    ["Hybrid Pouch Distance"] = "ハイブリッドポーチ距離",
    ["[headpouch]"] = "[ヘッドポーチ]",
    ["head Pouch Distance"] = "ヘッドポーチ距離",
    ["[infinity range pouch]"] = "[無限範囲ポーチ]",
    ["[arcticvr_allgun_allow_reloadkey]"] = "[全銃リロードキー許可]",
    ["[arcticvr_allgun_allow_reloadkey_client]"] = "[全銃リロードキー許可クライアント]",
    ["[arcticvr_bumpreload_allgun]"] = "[全銃バンプリロード]",
    ["[arcticvr_bumpreload_allgun_client]"] = "[全銃バンプリロードクライアント]",
    ["[defaultammo_normalize]"] = "[デフォルト弾薬正規化]",
    ["[alternative_phys_bullet]"] = "[代替物理弾]",
    ["[mag pickup delay]\nTry raising it\nby 0.01 when the\nclient cannot hold the\nmag properly online"] = "[マグピックアップ遅延]\nオンラインでマガジンを\n正常に保持できない場合\n0.01ずつ値を上げてください。",
    ["Attachment Preset System"] = "アタッチメントプリセットシステム",
    ["Save your current weapon's attachments.\nPresets auto-restore on respawn/re-equip."] = "現在の武器のアタッチメントを保存します。\nプリセットはリスポーン/再装備時に自動適用されます。",
    ["Current weapon: ---"] = "現在の武器: ---",
    ["Preset: (checking...)"] = "プリセット: (確認中...)",
    ["Save Preset"] = "プリセット保存",
    ["Clear Preset"] = "プリセット消去",
    ["[arcticvr_preset_auto]\nAuto-apply saved presets on weapon equip"] = "[arcticvr_preset_auto]\n武器装備時にプリセットを自動適用",
    ["No ArcVR weapon equipped."] = "ArcVR武器が装備されていません。",

    -- ==============================
    -- vrmod_pickup_assist
    -- ==============================
    ["Enable Cone Pickup Assist"] = "コーンピックアップアシスト有効",
    ["Pickup Assist Range (units)"] = "ピックアップアシスト範囲 (単位)",
    ["Max Retry Ticks"] = "最大リトライTick数",
    ["Max Pickup Weight (Server)"] = "最大ピックアップ重量 (サーバー)",
    ["Client Weight Limit (0=off)"] = "クライアント重量制限 (0=オフ)",
    ["Client Pickup Limit (0=off,1=std,2=strict,3=disable)"] = "クライアントピックアップ制限 (0=オフ,1=標準,2=厳格,3=無効)",
    ["Enable Held Entity Rotation (SecFire + Wrist Twist)"] = "保持エンティティの回転有効 (SecFire + 手首ひねり)",
    ["Rotation Sensitivity"] = "回転感度",
    ["Enable Ragdoll Beam Damage"] = "ラグドールビームダメージ有効",
    ["Beam Damage Amount"] = "ビームダメージ量",
    ["Show Held Entity Info on HUD"] = "保持エンティティ情報をHUDに表示",
    ["Restore Default Settings"] = "デフォルト設定に戻す",

    -- ==============================
    -- vrmod_magbone
    -- ==============================
    ["Enable VR Magazine System"] = "VRマガジンシステム有効",
    ["Enable Magazine Pouch (spawn vrmagent from body pouch)"] = "マガジンポーチ有効 (ボディポーチからvrmagent生成)",
    ["VR Magazine bone or bonegroup"] = "VRマガジン ボーンまたはボーングループ",
    ["Magazine Enter Sound"] = "マガジン挿入サウンド",
    ["Magazine Enter Range"] = "マガジン挿入範囲",
    ["Magazine Enter Model"] = "マガジン挿入モデル",
    ["[WIP]WeaponModel Mag Grab/Eject"] = "[WIP]武器モデル マグ掴み/排出",
    ["Mag Bone Hide Delay (seconds)"] = "マグボーン非表示遅延 (秒)",
    ["Apply Magazine Bone Names"] = "マガジンボーン名を適用",
    ["Default Magazine Bone Names"] = "デフォルトマガジンボーン名",
    ["Magazine Bone Names (comma-separated):"] = "マガジンボーン名 (カンマ区切り):",
    ["--- Pouch Settings (ArcVR Sync) ---"] = "--- ポーチ設定 (ArcVR連動) ---",
    ["Pouch Location:"] = "ポーチ位置:",
    ["Pelvis (Hip)"] = "骨盤 (ヒップ)",
    ["Head"] = "頭",
    ["Spine (Chest)"] = "背骨 (胸)",
    ["Pouch Distance"] = "ポーチ距離",
    ["Infinite Pouch (any distance)"] = "無限ポーチ (任意の距離)",
    ["Sync to ArcVR ConVars"] = "ArcVR ConVarと同期",
    ["Sync to ArcVR ConVars (ArcVR not found)"] = "ArcVR ConVarと同期 (ArcVR未検出)",
    ["Unified Pouch system not loaded"] = "統合ポーチシステム未読み込み",
    ["--- ARC9 Weapon Settings ---"] = "--- ARC9武器設定 ---",
    ["Enable ARC9 VR Integration"] = "ARC9 VR統合を有効化",
    ["Enable ARC9 Magazine Bone Fix"] = "ARC9マガジンボーン修正を有効化",
    ["ARC9 Mag Bone: Follow Left Hand (New) / Hide Only (Old)"] = "ARC9マグボーン: 左手追従(新) / 非表示のみ(旧)",

    -- ==============================
    -- vrmod_physgun
    -- ==============================
    ["Physgun Left"] = "Physgun 左手",
    ["Physgun Right"] = "Physgun 右手",
    ["VR Physgun Settings (LEFT HAND)"] = "VR Physgun設定 (左手)",
    ["VR Physgun Settings (RIGHT HAND)"] = "VR Physgun設定 (右手)",
    ["Enable Physgun Beams"] = "Physgunビーム有効",
    ["Beam Range"] = "ビーム射程",
    ["Enable Beam Damage"] = "ビームダメージ有効",
    ["Beam Offset X (Forward)"] = "ビームオフセット X (前方)",
    ["Beam Offset Y (Left/Right)"] = "ビームオフセット Y (左右)",
    ["Beam Offset Z (Up/Down)"] = "ビームオフセット Z (上下)",
    ["Enable Pull Feature (Left Secondary Fire Button)"] = "プル機能有効 (左セカンダリファイアボタン)",
    ["Enable Pull Feature (Secondary Fire Button)"] = "プル機能有効 (セカンダリファイアボタン)",
    ["Noclip Collision (Don't collide with player when pulling)"] = "ノークリップ衝突 (プル時にプレイヤーと衝突しない)",
    ["Use the left hand trigger to grab objects and grip button to pull them closer"] = "左手トリガーでオブジェクトを掴み、グリップボタンで引き寄せます",
    ["Use the right hand trigger to grab objects and grip button to pull them closer"] = "右手トリガーでオブジェクトを掴み、グリップボタンで引き寄せます",

    -- ==============================
    -- vrmod_foregrip
    -- ==============================
    ["Foregrip Mode Range"] = "フォアグリップモード範囲",
    ["Enable Foregrip Mode"] = "フォアグリップモード有効",
    ["Foregrip[boolean_left_primary]Key"] = "フォアグリップ[boolean_left_primary]キー",
    ["Foregrip[boolean_left_pickup]Key"] = "フォアグリップ[boolean_left_pickup]キー",
    ["Rotation Blend"] = "回転ブレンド",
    ["Offset X"] = "オフセット X",
    ["Offset Y"] = "オフセット Y",
    ["Offset Z"] = "オフセット Z",
    ["Angle Pitch"] = "角度 ピッチ",
    ["Angle Yaw"] = "角度 ヨー",
    ["Angle Roll"] = "角度 ロール",
    ["Restore Advanced Defaults"] = "詳細設定をデフォルトに戻す",

    -- ==============================
    -- vrmod_holster_type1
    -- ==============================
    ["Right Hand Holster"] = "右手ホルスター",
    ["Left Hand Holster"] = "左手ホルスター",
    ["=== Pelvis ==="] = "=== 骨盤 ===",
    ["=== Head ==="] = "=== 頭 ===",
    ["=== Spine ==="] = "=== 背骨 ===",
    ["Enable Pelvis Holster"] = "骨盤ホルスター有効",
    ["Enable Head Holster"] = "ヘッドホルスター有効",
    ["Enable Spine Holster"] = "背骨ホルスター有効",
    ["Range"] = "範囲",
    ["Weapon Lock"] = "武器ロック",
    ["Stored Weapon (Read-only)"] = "格納武器 (読み取り専用)",
    ["Enable Custom Command"] = "カスタムコマンド有効",
    ["Custom Pickup Command"] = "カスタムピックアップコマンド",
    ["Custom Put Command"] = "カスタム配置コマンド",
    ["Restore Defaults (Right)"] = "デフォルトに戻す (右手)",
    ["Restore Defaults (Left)"] = "デフォルトに戻す (左手)",
    ["Display Settings"] = "表示設定",
    ["Visible Range (Right)"] = "範囲表示 (右手)",
    ["Visible Name (Right)"] = "名前表示 (右手)",
    ["Visible Range (Left)"] = "範囲表示 (左手)",
    ["Visible Name (Left)"] = "名前表示 (左手)",

    -- ==============================
    -- vrmod_holster_type2
    -- ==============================
    ["Basic Settings"] = "基本設定",
    ["System Enable"] = "システム有効",
    ["Visible Name (3D)"] = "名前表示 (3D)",
    ["Visible HUD"] = "HUD表示",
    ["Left Hand Weapon Enable"] = "左手武器有効",
    ["L/R Sync Mode (share slots between hands)"] = "左右同期モード (スロット共有)",
    ["Pickup Sound"] = "ピックアップサウンド",
    ["Release / Tediore"] = "リリース / テディオール",
    ["[release -> Emptyhand] Enable"] = "[リリース -> 空手] 有効",
    ["[Tediore like reload] Enable"] = "[テディオール式リロード] 有効",
    ["Trash Weapon on Drop"] = "ドロップ時に武器破棄",
    ["Dupe Settings"] = "複製設定",
    ["Reusable Dupe (infinite retrieve)"] = "再利用可能な複製 (無限回収)",
    ["Enable"] = "有効",
    ["Weapon (Read-only)"] = "武器 (読み取り専用)",
    ["Left Hand Weapon (Read-only)"] = "左手武器 (読み取り専用)",
    ["Sphere Size"] = "球体サイズ",
    ["Shape"] = "形状",
    ["Box Width (X)"] = "ボックス幅 (X)",
    ["Box Height (Y)"] = "ボックス高さ (Y)",
    ["Box Depth Up (Z+)"] = "ボックス深さ上 (Z+)",
    ["Box Depth Down (Z-)"] = "ボックス深さ下 (Z-)",
})

-- ============================================================================
-- Chinese (Simplified)
-- ============================================================================
AddSettings("zh", {
    -- ==============================
    -- vrmod_arcvr_fix (ArcticVR)
    -- ==============================
    ["ArcticVR"] = "ArcticVR",
    ["Settings1"] = "设置1",
    ["Settings2"] = "设置2",
    ["GunMelee"] = "枪械近战",
    ["MagPouch"] = "弹匣袋",
    ["Server"] = "服务器",
    ["Presets"] = "预设",
    ["[arcticvr_grip_with_reloadkey]\nON = Reloadkey with\nOFF = Boolean_left_secondaryfire"] = "[arcticvr_grip_with_reloadkey]\nON = 换弹键配合\nOFF = Boolean_left_secondaryfire",
    ["[mag_bumpreload] \n You can reload a magazine with the Reload key enabled gun \n by popping the magazine with the magazine."] = "[mag_bumpreload]\n启用换弹键的枪可以通过\n弹匣碰撞来换弹。",
    ["[frontgrip alternative mode] \n The leftpickup key will no longer allow you to grip the foregrip\nbut only while pressing the reload or left_secondary_fire set above\nThis reduces the chance of accidentally removing the magazine."] = "[前握把替代模式]\n左拾取键将不再直接握住前握把，\n仅在按下换弹键或left_secondary_fire时生效。\n减少意外移除弹匣的概率。",
    ["[slide_magnification]\n A higher value allows \n cocking even when the \n hand is away from the slide."] = "[滑套放大倍率]\n数值越大，手离滑套\n越远也能拉动。",
    ["[arcticvr_grip_magnification]\nThe larger the value\nthe greater the decision\nto start holding the foregrip"] = "[握把放大倍率]\n数值越大，开始\n握住前握把的判定范围越广。",
    ["[arcticvr_disable_reload_with_key]"] = "[禁用按键换弹]",
    ["[arcticvr_disable_grabreload]"] = "[禁用抓取换弹]",
    ["[ArcticVR Virtualstock] \n Using a VR weapon with a stock close to the shoulder or head \n will help stabilize the sight."] = "[ArcticVR 虚拟枪托]\n将有枪托的VR武器靠近肩膀或头部\n可以稳定瞄准。",
    ["[Frontgrip_Power]\nhow much the movement\nof your left hand affects\nthe sight of the gun\nwhen you grab the foregrip"] = "[前握把力度]\n握住前握把时\n左手移动对枪械\n瞄准的影响程度",
    ["[Grenade_pin_enable] \n When set to false\n the specification allows a grenade to be thrown without\npulling out the safety pin."] = "[手雷保险销启用]\n关闭时允许不拔保险销\n直接投掷手雷。",
    ["[test_cl_misc_fix]\nFor some ArcVR weapons\ncheck the box if the magazine cannot be removed."] = "[cl_misc修复测试]\n如果某些ArcVR武器无法移除弹匣，\n请勾选此项。",
    ["[Shoot System Fix] \n Check the box if the shotgun sights are significantly misaligned \n and uncheck the box if some ArcVR weapons become unusable."] = "[射击系统修复]\n如果霰弹枪准星严重偏移请勾选，\n如果某些ArcVR武器变得无法使用请取消勾选。",
    ["[gunmelee]"] = "[枪械近战]",
    ["[gunmelee_client]"] = "[枪械近战客户端]",
    ["[fist]"] = "[拳头]",
    ["[fist_client]"] = "[拳头客户端]",
    ["[kick]-FBTOnly-(buggy)"] = "[踢]-仅FBT-(不稳定)",
    ["[kick_client]-FBTOnly-(buggy)"] = "[踢客户端]-仅FBT-(不稳定)",
    ["gunmelee_velthreshold"] = "枪械近战速度阈值",
    ["gunmelee_damage"] = "枪械近战伤害",
    ["gunmelee_Delay"] = "枪械近战延迟",
    ["Default Pouch Distance"] = "默认弹匣袋距离",
    ["[hybridpouch]"] = "[混合弹匣袋]",
    ["Hybrid Pouch Distance"] = "混合弹匣袋距离",
    ["[headpouch]"] = "[头部弹匣袋]",
    ["head Pouch Distance"] = "头部弹匣袋距离",
    ["[infinity range pouch]"] = "[无限范围弹匣袋]",
    ["[arcticvr_allgun_allow_reloadkey]"] = "[所有枪允许换弹键]",
    ["[arcticvr_allgun_allow_reloadkey_client]"] = "[所有枪允许换弹键客户端]",
    ["[arcticvr_bumpreload_allgun]"] = "[所有枪碰撞换弹]",
    ["[arcticvr_bumpreload_allgun_client]"] = "[所有枪碰撞换弹客户端]",
    ["[defaultammo_normalize]"] = "[默认弹药标准化]",
    ["[alternative_phys_bullet]"] = "[替代物理子弹]",
    ["[mag pickup delay]\nTry raising it\nby 0.01 when the\nclient cannot hold the\nmag properly online"] = "[弹匣拾取延迟]\n在线游戏中客户端无法\n正常持有弹匣时，\n请尝试每次增加0.01。",
    ["Attachment Preset System"] = "配件预设系统",
    ["Save your current weapon's attachments.\nPresets auto-restore on respawn/re-equip."] = "保存当前武器的配件。\n预设在重生/重新装备时自动恢复。",
    ["Current weapon: ---"] = "当前武器: ---",
    ["Preset: (checking...)"] = "预设: (检查中...)",
    ["Save Preset"] = "保存预设",
    ["Clear Preset"] = "清除预设",
    ["[arcticvr_preset_auto]\nAuto-apply saved presets on weapon equip"] = "[arcticvr_preset_auto]\n装备武器时自动应用保存的预设",
    ["No ArcVR weapon equipped."] = "未装备ArcVR武器。",

    -- ==============================
    -- vrmod_pickup_assist
    -- ==============================
    ["Enable Cone Pickup Assist"] = "启用锥形拾取辅助",
    ["Pickup Assist Range (units)"] = "拾取辅助范围 (单位)",
    ["Max Retry Ticks"] = "最大重试Tick数",
    ["Max Pickup Weight (Server)"] = "最大拾取重量 (服务器)",
    ["Client Weight Limit (0=off)"] = "客户端重量限制 (0=关)",
    ["Client Pickup Limit (0=off,1=std,2=strict,3=disable)"] = "客户端拾取限制 (0=关,1=标准,2=严格,3=禁用)",
    ["Enable Held Entity Rotation (SecFire + Wrist Twist)"] = "启用持有实体旋转 (副射击 + 手腕转动)",
    ["Rotation Sensitivity"] = "旋转灵敏度",
    ["Enable Ragdoll Beam Damage"] = "启用布娃娃光束伤害",
    ["Beam Damage Amount"] = "光束伤害量",
    ["Show Held Entity Info on HUD"] = "在HUD上显示持有实体信息",
    ["Restore Default Settings"] = "恢复默认设置",

    -- ==============================
    -- vrmod_magbone
    -- ==============================
    ["Enable VR Magazine System"] = "启用VR弹匣系统",
    ["Enable Magazine Pouch (spawn vrmagent from body pouch)"] = "启用弹匣袋 (从身体袋生成vrmagent)",
    ["VR Magazine bone or bonegroup"] = "VR弹匣骨骼或骨骼组",
    ["Magazine Enter Sound"] = "弹匣插入音效",
    ["Magazine Enter Range"] = "弹匣插入范围",
    ["Magazine Enter Model"] = "弹匣插入模型",
    ["[WIP]WeaponModel Mag Grab/Eject"] = "[开发中]武器模型弹匣抓取/弹出",
    ["Mag Bone Hide Delay (seconds)"] = "弹匣骨骼隐藏延迟 (秒)",
    ["Apply Magazine Bone Names"] = "应用弹匣骨骼名称",
    ["Default Magazine Bone Names"] = "默认弹匣骨骼名称",
    ["Magazine Bone Names (comma-separated):"] = "弹匣骨骼名称 (逗号分隔):",
    ["--- Pouch Settings (ArcVR Sync) ---"] = "--- 弹匣袋设置 (ArcVR同步) ---",
    ["Pouch Location:"] = "弹匣袋位置:",
    ["Pelvis (Hip)"] = "骨盆 (臀部)",
    ["Head"] = "头部",
    ["Spine (Chest)"] = "脊椎 (胸部)",
    ["Pouch Distance"] = "弹匣袋距离",
    ["Infinite Pouch (any distance)"] = "无限弹匣袋 (任意距离)",
    ["Sync to ArcVR ConVars"] = "同步到ArcVR ConVar",
    ["Sync to ArcVR ConVars (ArcVR not found)"] = "同步到ArcVR ConVar (未找到ArcVR)",
    ["Unified Pouch system not loaded"] = "统一弹匣袋系统未加载",
    ["--- ARC9 Weapon Settings ---"] = "--- ARC9武器设置 ---",
    ["Enable ARC9 VR Integration"] = "启用ARC9 VR集成",
    ["Enable ARC9 Magazine Bone Fix"] = "启用ARC9弹匣骨骼修复",
    ["ARC9 Mag Bone: Follow Left Hand (New) / Hide Only (Old)"] = "ARC9弹匣骨骼: 跟随左手(新) / 仅隐藏(旧)",

    -- ==============================
    -- vrmod_physgun
    -- ==============================
    ["Physgun Left"] = "Physgun 左手",
    ["Physgun Right"] = "Physgun 右手",
    ["VR Physgun Settings (LEFT HAND)"] = "VR Physgun设置 (左手)",
    ["VR Physgun Settings (RIGHT HAND)"] = "VR Physgun设置 (右手)",
    ["Enable Physgun Beams"] = "启用Physgun光束",
    ["Beam Range"] = "光束范围",
    ["Enable Beam Damage"] = "启用光束伤害",
    ["Beam Offset X (Forward)"] = "光束偏移 X (前方)",
    ["Beam Offset Y (Left/Right)"] = "光束偏移 Y (左右)",
    ["Beam Offset Z (Up/Down)"] = "光束偏移 Z (上下)",
    ["Enable Pull Feature (Left Secondary Fire Button)"] = "启用拉取功能 (左副射击按钮)",
    ["Enable Pull Feature (Secondary Fire Button)"] = "启用拉取功能 (副射击按钮)",
    ["Noclip Collision (Don't collide with player when pulling)"] = "无碰撞 (拉取时不与玩家碰撞)",
    ["Use the left hand trigger to grab objects and grip button to pull them closer"] = "使用左手扳机抓取物体，握把按钮拉近",
    ["Use the right hand trigger to grab objects and grip button to pull them closer"] = "使用右手扳机抓取物体，握把按钮拉近",

    -- ==============================
    -- vrmod_foregrip
    -- ==============================
    ["Foregrip Mode Range"] = "前握把模式范围",
    ["Enable Foregrip Mode"] = "启用前握把模式",
    ["Foregrip[boolean_left_primary]Key"] = "前握把[boolean_left_primary]键",
    ["Foregrip[boolean_left_pickup]Key"] = "前握把[boolean_left_pickup]键",
    ["Rotation Blend"] = "旋转混合",
    ["Offset X"] = "偏移 X",
    ["Offset Y"] = "偏移 Y",
    ["Offset Z"] = "偏移 Z",
    ["Angle Pitch"] = "角度 俯仰",
    ["Angle Yaw"] = "角度 偏航",
    ["Angle Roll"] = "角度 翻滚",
    ["Restore Advanced Defaults"] = "恢复高级默认设置",

    -- ==============================
    -- vrmod_holster_type1
    -- ==============================
    ["Right Hand Holster"] = "右手枪套",
    ["Left Hand Holster"] = "左手枪套",
    ["=== Pelvis ==="] = "=== 骨盆 ===",
    ["=== Head ==="] = "=== 头部 ===",
    ["=== Spine ==="] = "=== 脊椎 ===",
    ["Enable Pelvis Holster"] = "启用骨盆枪套",
    ["Enable Head Holster"] = "启用头部枪套",
    ["Enable Spine Holster"] = "启用脊椎枪套",
    ["Range"] = "范围",
    ["Weapon Lock"] = "武器锁定",
    ["Stored Weapon (Read-only)"] = "存储武器 (只读)",
    ["Enable Custom Command"] = "启用自定义命令",
    ["Custom Pickup Command"] = "自定义拾取命令",
    ["Custom Put Command"] = "自定义放置命令",
    ["Restore Defaults (Right)"] = "恢复默认 (右手)",
    ["Restore Defaults (Left)"] = "恢复默认 (左手)",
    ["Display Settings"] = "显示设置",
    ["Visible Range (Right)"] = "范围显示 (右手)",
    ["Visible Name (Right)"] = "名称显示 (右手)",
    ["Visible Range (Left)"] = "范围显示 (左手)",
    ["Visible Name (Left)"] = "名称显示 (左手)",

    -- ==============================
    -- vrmod_holster_type2
    -- ==============================
    ["Basic Settings"] = "基本设置",
    ["System Enable"] = "系统启用",
    ["Visible Name (3D)"] = "名称显示 (3D)",
    ["Visible HUD"] = "HUD显示",
    ["Left Hand Weapon Enable"] = "启用左手武器",
    ["L/R Sync Mode (share slots between hands)"] = "左右同步模式 (共享槽位)",
    ["Pickup Sound"] = "拾取音效",
    ["Release / Tediore"] = "释放 / Tediore",
    ["[release -> Emptyhand] Enable"] = "[释放 -> 空手] 启用",
    ["[Tediore like reload] Enable"] = "[Tediore式换弹] 启用",
    ["Trash Weapon on Drop"] = "丢弃时销毁武器",
    ["Dupe Settings"] = "复制设置",
    ["Reusable Dupe (infinite retrieve)"] = "可重复复制 (无限取回)",
    ["Enable"] = "启用",
    ["Weapon (Read-only)"] = "武器 (只读)",
    ["Left Hand Weapon (Read-only)"] = "左手武器 (只读)",
    ["Sphere Size"] = "球体大小",
    ["Shape"] = "形状",
    ["Box Width (X)"] = "方框宽度 (X)",
    ["Box Height (Y)"] = "方框高度 (Y)",
    ["Box Depth Up (Z+)"] = "方框深度上 (Z+)",
    ["Box Depth Down (Z-)"] = "方框深度下 (Z-)",
})

-- ============================================================================
-- Russian
-- ============================================================================
AddSettings("ru", {
    -- ==============================
    -- vrmod_arcvr_fix (ArcticVR)
    -- ==============================
    ["ArcticVR"] = "ArcticVR",
    ["Settings1"] = "Настройки 1",
    ["Settings2"] = "Настройки 2",
    ["GunMelee"] = "Ближний бой",
    ["MagPouch"] = "Подсумок",
    ["Server"] = "Сервер",
    ["Presets"] = "Пресеты",
    ["[arcticvr_grip_with_reloadkey]\nON = Reloadkey with\nOFF = Boolean_left_secondaryfire"] = "[arcticvr_grip_with_reloadkey]\nВКЛ = С клавишей перезарядки\nВЫКЛ = Boolean_left_secondaryfire",
    ["[mag_bumpreload] \n You can reload a magazine with the Reload key enabled gun \n by popping the magazine with the magazine."] = "[mag_bumpreload]\nМожно перезарядить оружие с клавишей перезарядки,\nстолкнув магазины друг с другом.",
    ["[frontgrip alternative mode] \n The leftpickup key will no longer allow you to grip the foregrip\nbut only while pressing the reload or left_secondary_fire set above\nThis reduces the chance of accidentally removing the magazine."] = "[Альтернативный режим цевья]\nКлавиша левого подбора больше не захватывает цевьё,\nтолько при нажатии перезарядки или left_secondary_fire.\nСнижает вероятность случайного извлечения магазина.",
    ["[slide_magnification]\n A higher value allows \n cocking even when the \n hand is away from the slide."] = "[Увеличение затвора]\nЧем выше значение, тем дальше\nможет быть рука от затвора\nдля взведения.",
    ["[arcticvr_grip_magnification]\nThe larger the value\nthe greater the decision\nto start holding the foregrip"] = "[Увеличение захвата]\nЧем выше значение,\nтем шире зона\nзахвата цевья.",
    ["[arcticvr_disable_reload_with_key]"] = "[Откл. перезарядку клавишей]",
    ["[arcticvr_disable_grabreload]"] = "[Откл. перезарядку захватом]",
    ["[ArcticVR Virtualstock] \n Using a VR weapon with a stock close to the shoulder or head \n will help stabilize the sight."] = "[ArcticVR Виртуальный приклад]\nПриближение приклада VR-оружия к плечу или голове\nпомогает стабилизировать прицел.",
    ["[Frontgrip_Power]\nhow much the movement\nof your left hand affects\nthe sight of the gun\nwhen you grab the foregrip"] = "[Сила цевья]\nНасколько движение\nлевой руки влияет на\nприцел при захвате цевья",
    ["[Grenade_pin_enable] \n When set to false\n the specification allows a grenade to be thrown without\npulling out the safety pin."] = "[Чека гранаты]\nПри выключении можно бросить гранату\nне вытаскивая предохранительную чеку.",
    ["[test_cl_misc_fix]\nFor some ArcVR weapons\ncheck the box if the magazine cannot be removed."] = "[Исправление cl_misc]\nДля некоторых ArcVR-оружий:\nвключите, если магазин не извлекается.",
    ["[Shoot System Fix] \n Check the box if the shotgun sights are significantly misaligned \n and uncheck the box if some ArcVR weapons become unusable."] = "[Исправление стрельбы]\nВключите, если прицел дробовика сильно сбит.\nОтключите, если некоторые ArcVR-оружия перестают работать.",
    ["[gunmelee]"] = "[Удар оружием]",
    ["[gunmelee_client]"] = "[Удар оружием (клиент)]",
    ["[fist]"] = "[Кулак]",
    ["[fist_client]"] = "[Кулак (клиент)]",
    ["[kick]-FBTOnly-(buggy)"] = "[Удар ногой]-только FBT-(нестабильно)",
    ["[kick_client]-FBTOnly-(buggy)"] = "[Удар ногой (клиент)]-только FBT-(нестабильно)",
    ["gunmelee_velthreshold"] = "Порог скорости удара оружием",
    ["gunmelee_damage"] = "Урон удара оружием",
    ["gunmelee_Delay"] = "Задержка удара оружием",
    ["Default Pouch Distance"] = "Расстояние подсумка по умолч.",
    ["[hybridpouch]"] = "[Гибридный подсумок]",
    ["Hybrid Pouch Distance"] = "Расстояние гибридного подсумка",
    ["[headpouch]"] = "[Подсумок на голове]",
    ["head Pouch Distance"] = "Расстояние подсумка на голове",
    ["[infinity range pouch]"] = "[Бесконечная дальность подсумка]",
    ["[arcticvr_allgun_allow_reloadkey]"] = "[Все оружия: разрешить клавишу перезарядки]",
    ["[arcticvr_allgun_allow_reloadkey_client]"] = "[Все оружия: клавиша перезарядки (клиент)]",
    ["[arcticvr_bumpreload_allgun]"] = "[Все оружия: перезарядка столкновением]",
    ["[arcticvr_bumpreload_allgun_client]"] = "[Все оружия: столкновение (клиент)]",
    ["[defaultammo_normalize]"] = "[Нормализация боеприпасов]",
    ["[alternative_phys_bullet]"] = "[Альтернативные физ. пули]",
    ["[mag pickup delay]\nTry raising it\nby 0.01 when the\nclient cannot hold the\nmag properly online"] = "[Задержка подбора магазина]\nПопробуйте увеличить на 0.01,\nесли клиент не может нормально\nдержать магазин онлайн.",
    ["Attachment Preset System"] = "Система пресетов модулей",
    ["Save your current weapon's attachments.\nPresets auto-restore on respawn/re-equip."] = "Сохранить модули текущего оружия.\nПресеты автоматически восстанавливаются при респауне.",
    ["Current weapon: ---"] = "Текущее оружие: ---",
    ["Preset: (checking...)"] = "Пресет: (проверка...)",
    ["Save Preset"] = "Сохранить пресет",
    ["Clear Preset"] = "Очистить пресет",
    ["[arcticvr_preset_auto]\nAuto-apply saved presets on weapon equip"] = "[arcticvr_preset_auto]\nАвтоприменение пресетов при экипировке оружия",
    ["No ArcVR weapon equipped."] = "ArcVR-оружие не экипировано.",

    -- ==============================
    -- vrmod_pickup_assist
    -- ==============================
    ["Enable Cone Pickup Assist"] = "Вкл. конусный подбор",
    ["Pickup Assist Range (units)"] = "Дальность подбора (единицы)",
    ["Max Retry Ticks"] = "Макс. попыток (тиков)",
    ["Max Pickup Weight (Server)"] = "Макс. вес подбора (сервер)",
    ["Client Weight Limit (0=off)"] = "Лимит веса клиента (0=выкл)",
    ["Client Pickup Limit (0=off,1=std,2=strict,3=disable)"] = "Лимит подбора клиента (0=выкл,1=станд,2=строг,3=откл)",
    ["Enable Held Entity Rotation (SecFire + Wrist Twist)"] = "Вращение объекта (SecFire + поворот запястья)",
    ["Rotation Sensitivity"] = "Чувствительность вращения",
    ["Enable Ragdoll Beam Damage"] = "Вкл. урон лучом рэгдоллу",
    ["Beam Damage Amount"] = "Величина урона лучом",
    ["Show Held Entity Info on HUD"] = "Показ инфо объекта на HUD",
    ["Restore Default Settings"] = "Восстановить настройки",

    -- ==============================
    -- vrmod_magbone
    -- ==============================
    ["Enable VR Magazine System"] = "Вкл. VR-систему магазинов",
    ["Enable Magazine Pouch (spawn vrmagent from body pouch)"] = "Вкл. подсумок (спавн vrmagent из подсумка)",
    ["VR Magazine bone or bonegroup"] = "VR-магазин: кость или группа",
    ["Magazine Enter Sound"] = "Звук вставки магазина",
    ["Magazine Enter Range"] = "Дальность вставки магазина",
    ["Magazine Enter Model"] = "Модель вставки магазина",
    ["[WIP]WeaponModel Mag Grab/Eject"] = "[WIP] Захват/извлечение магазина",
    ["Mag Bone Hide Delay (seconds)"] = "Задержка скрытия кости (сек)",
    ["Apply Magazine Bone Names"] = "Применить имена костей",
    ["Default Magazine Bone Names"] = "Имена костей по умолчанию",
    ["Magazine Bone Names (comma-separated):"] = "Имена костей магазина (через запятую):",
    ["--- Pouch Settings (ArcVR Sync) ---"] = "--- Настройки подсумка (синхр. ArcVR) ---",
    ["Pouch Location:"] = "Расположение подсумка:",
    ["Pelvis (Hip)"] = "Таз (бедро)",
    ["Head"] = "Голова",
    ["Spine (Chest)"] = "Позвоночник (грудь)",
    ["Pouch Distance"] = "Расстояние подсумка",
    ["Infinite Pouch (any distance)"] = "Бесконечный подсумок (любая дист.)",
    ["Sync to ArcVR ConVars"] = "Синхр. с ArcVR ConVar",
    ["Sync to ArcVR ConVars (ArcVR not found)"] = "Синхр. с ArcVR ConVar (ArcVR не найден)",
    ["Unified Pouch system not loaded"] = "Система подсумка не загружена",
    ["--- ARC9 Weapon Settings ---"] = "--- Настройки ARC9-оружия ---",
    ["Enable ARC9 VR Integration"] = "Вкл. интеграцию ARC9 VR",
    ["Enable ARC9 Magazine Bone Fix"] = "Вкл. исправление кости ARC9",
    ["ARC9 Mag Bone: Follow Left Hand (New) / Hide Only (Old)"] = "ARC9: следовать за левой рукой (новый) / только скрыть (старый)",

    -- ==============================
    -- vrmod_physgun
    -- ==============================
    ["Physgun Left"] = "Physgun левая",
    ["Physgun Right"] = "Physgun правая",
    ["VR Physgun Settings (LEFT HAND)"] = "VR Physgun (ЛЕВАЯ РУКА)",
    ["VR Physgun Settings (RIGHT HAND)"] = "VR Physgun (ПРАВАЯ РУКА)",
    ["Enable Physgun Beams"] = "Вкл. лучи Physgun",
    ["Beam Range"] = "Дальность луча",
    ["Enable Beam Damage"] = "Вкл. урон лучом",
    ["Beam Offset X (Forward)"] = "Смещение луча X (вперёд)",
    ["Beam Offset Y (Left/Right)"] = "Смещение луча Y (лево/право)",
    ["Beam Offset Z (Up/Down)"] = "Смещение луча Z (верх/низ)",
    ["Enable Pull Feature (Left Secondary Fire Button)"] = "Вкл. притяжение (левая доп. кнопка)",
    ["Enable Pull Feature (Secondary Fire Button)"] = "Вкл. притяжение (доп. кнопка)",
    ["Noclip Collision (Don't collide with player when pulling)"] = "Без столкновений (не сталкиваться с игроком при притяжении)",
    ["Use the left hand trigger to grab objects and grip button to pull them closer"] = "Используйте триггер левой руки для захвата и кнопку хвата для притяжения",
    ["Use the right hand trigger to grab objects and grip button to pull them closer"] = "Используйте триггер правой руки для захвата и кнопку хвата для притяжения",

    -- ==============================
    -- vrmod_foregrip
    -- ==============================
    ["Foregrip Mode Range"] = "Дальность режима цевья",
    ["Enable Foregrip Mode"] = "Вкл. режим цевья",
    ["Foregrip[boolean_left_primary]Key"] = "Цевьё[boolean_left_primary]Клавиша",
    ["Foregrip[boolean_left_pickup]Key"] = "Цевьё[boolean_left_pickup]Клавиша",
    ["Rotation Blend"] = "Смешивание вращения",
    ["Offset X"] = "Смещение X",
    ["Offset Y"] = "Смещение Y",
    ["Offset Z"] = "Смещение Z",
    ["Angle Pitch"] = "Угол наклона",
    ["Angle Yaw"] = "Угол рыскания",
    ["Angle Roll"] = "Угол крена",
    ["Restore Advanced Defaults"] = "Сброс доп. настроек",

    -- ==============================
    -- vrmod_holster_type1
    -- ==============================
    ["Right Hand Holster"] = "Кобура правой руки",
    ["Left Hand Holster"] = "Кобура левой руки",
    ["=== Pelvis ==="] = "=== Таз ===",
    ["=== Head ==="] = "=== Голова ===",
    ["=== Spine ==="] = "=== Позвоночник ===",
    ["Enable Pelvis Holster"] = "Вкл. кобуру на тазе",
    ["Enable Head Holster"] = "Вкл. кобуру на голове",
    ["Enable Spine Holster"] = "Вкл. кобуру на спине",
    ["Range"] = "Дальность",
    ["Weapon Lock"] = "Блокировка оружия",
    ["Stored Weapon (Read-only)"] = "Хранимое оружие (только чтение)",
    ["Enable Custom Command"] = "Вкл. пользовательскую команду",
    ["Custom Pickup Command"] = "Пользов. команда подбора",
    ["Custom Put Command"] = "Пользов. команда размещения",
    ["Restore Defaults (Right)"] = "Сброс настроек (правая)",
    ["Restore Defaults (Left)"] = "Сброс настроек (левая)",
    ["Display Settings"] = "Настройки отображения",
    ["Visible Range (Right)"] = "Показ дальности (правая)",
    ["Visible Name (Right)"] = "Показ имени (правая)",
    ["Visible Range (Left)"] = "Показ дальности (левая)",
    ["Visible Name (Left)"] = "Показ имени (левая)",

    -- ==============================
    -- vrmod_holster_type2
    -- ==============================
    ["Basic Settings"] = "Основные настройки",
    ["System Enable"] = "Вкл. систему",
    ["Visible Name (3D)"] = "Показ имени (3D)",
    ["Visible HUD"] = "Показ HUD",
    ["Left Hand Weapon Enable"] = "Вкл. оружие левой руки",
    ["L/R Sync Mode (share slots between hands)"] = "Синхр. L/R (общие слоты)",
    ["Pickup Sound"] = "Звук подбора",
    ["Release / Tediore"] = "Отпустить / Tediore",
    ["[release -> Emptyhand] Enable"] = "[Отпустить -> Пустая рука] Вкл.",
    ["[Tediore like reload] Enable"] = "[Перезарядка Tediore] Вкл.",
    ["Trash Weapon on Drop"] = "Уничтожить оружие при сбросе",
    ["Dupe Settings"] = "Настройки дубликатов",
    ["Reusable Dupe (infinite retrieve)"] = "Многоразовый дубликат (беск. извлечение)",
    ["Enable"] = "Включить",
    ["Weapon (Read-only)"] = "Оружие (только чтение)",
    ["Left Hand Weapon (Read-only)"] = "Оружие левой руки (только чтение)",
    ["Sphere Size"] = "Размер сферы",
    ["Shape"] = "Форма",
    ["Box Width (X)"] = "Ширина блока (X)",
    ["Box Height (Y)"] = "Высота блока (Y)",
    ["Box Depth Up (Z+)"] = "Глубина блока вверх (Z+)",
    ["Box Depth Down (Z-)"] = "Глубина блока вниз (Z-)",
})
